import keyboard

import colorama
from colorama import Fore, init
init()
print(Fore.RED,"1'den 10' a Sayılar")
print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print(Fore.WHITE,"eins = ?, zwei = ?, drei = ?, vier = ?, fünf = ?, sechs = ?, sieben = ?, acht = ?, neun = ?, zehn = ?")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")
mesaj = "Karşılık gelen rakamları giriniz:"
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

eins   = input(mesaj)
zwei   = input(mesaj)
drei   = input(mesaj)
vier   = input(mesaj)
fünf   = input(mesaj)
sechs  = input(mesaj)
sieben = input(mesaj)
acht   = input(mesaj)
neun   = input(mesaj)
zehn   = input(mesaj)
print("")

print("Devam etmek için spacebar'a basınız.")
keyboard.wait("space")

print("")

print("eins = 1, zwei = 2, drei  = 3, vier = 4, fünf = 5, sechs = 6, sieben = 7, acht = 8, neun = 9, zehn = 10")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print("İşlemler")

print("")
sayi1 = int(input("Birinci sayiyi giriniz:"))
sayi2 = int(input("İkinci sayiyi giriniz:"))
print("")

toplam = sayi1 + sayi2
print("")
print(toplam)
print("")

print(Fore.RED, "Lesson 2 - Greetings")
print("")

print(Fore.WHITE,"Hallo = Hello")
print("Wie geht es Ihnen = How are you?")
print("Freut mich, Sie kennen zu lernen = Nice to meet you")
print("Bis morgen = See you tomorrow")
print("Guten Morgen = Good morning")
print("Guten Machmittag = Good afternoon")
print("Guten Abend = Good Evening")
print("Gute Nacht = Good night")
print("Wie heissen sie ? = What is your name ?")
print("Mein name ist____ = My name is ___")
print("Wo wohnst du ? = Where do you live?")
print("Woher kommen Sie ? = Where are you from?")
print("Freut mich, Sie zu sehen = Nice to see you")
print("İch wünsche Ihnen einen schönen Tag = Have a nice day")
print("Bis spater = See you later")
print("Auf Wiedersehen = Goodbye")
print("Biyye = Please")
print("Danke = Thank you")

print(Fore.RED, "Lessson 3 - Regular Verbs")
print("")
print(Fore.WHITE, "arbeiten = to work")
print("lernen = to learn")
print("leben = to live")
print("spielen = to play")
print("fragen = to ask")
print("machen = to do / make")
print("sagen = to say")
print("kaufen = to buy")
print("hören = to hear / listen")
print("wohnen = to live (reside)")
print("lieben = to love")
print("reden = to talk")
print("lernen = to learn")
print("öffnen = to open")
print("warten = to wait")
print("zeigen = to show")
print("brauchen = to need")
print("tanzen = to dance")
print("glauben = to believe")
print("spielen = to play")
print("arbeiten = to work")
print("reisen = to travel")

print(Fore.RED,"Lesson 3.1 - Present Tense")           

print(Fore.WHITE,"I = ich")
print("you = du")
print("he/she/it = er/sie/es")
print("we = wir")
print("you = ihr")
print("they = Sie")

print("Example for lernen = to learn")

print("ich lerne")
print("du lernst")
print("er/sie/es lernt")
print("wir lernen")
print("ihr lernt")
print("Sie lernen")

print(Fore.BLUE, "Lesson 4 = Adjectives")

print(Fore.WHITE, "Glücklich = Happy")
print("Traurig = Sad")
print("Wütend = Angry")
print("Angst = Afraid")
print("Freude = Joy")
print("Überrascht = Surprised")
print("Ruhig = Calm")
print("Gelangweilt = Bored")
print("Leicht = Easy")
print("Schwer = Difficult")
print("Schlecht = Bad")
print("Gut = Good")
print("Laut = Noisy")
print("Leise = Quiet")
print("Stark = Strong")
print("Schwach = Weak")
print("Hart = Hard")
print("Weich = Soft")
print("Mehr = More")
print("Weniger = Less")
print("Sauber = Clean")
print("Schmutzig = Dirty")
print("Alt = Old")
print("Neu = New")
print("Groß = Big")
print("Klein = Small")
print("Jung = Young")
print("Dünn = Skinny")
print("Dick = Fat")
print("Hübsch = Pretty")
print("Hässlich = Ugly")
print("Dick = Thick")
print("Dünn = Thin")
print("Rau = Rough")
print("Glatt = Smooth")

print(Fore.RED,"Lesson 5 - Days and Months")
print("")

print(Fore.BLUE,"Lesson 5.1 - Days of the week")
print("")

print(Fore.WHITE, "Die Wochentage = The days of the week")
print("(der) Tag = Day")
print("(die) Woche = Week")
print("Montag = Monday")
print("Dienstag = Tuesday")
print("Mittwoch = Wednesday")
print("Donnerstag = Thursday")
print("Freitag = Friday")
print("Samstag = Saturday")
print("Sonntag = Sunday")
print("(das) Wochenende = Weekend")

print(Fore.RED, "Lesson 5.2 - Months of the year")
print("")

print(Fore.WHITE, "Die Monate des Jahres = The months of the year")
print("(der)Monat = Month")
print("(das)Jahr = Year")
print("Januar = January")
print("Februar = February")
print("März = March")
print("April = April")
print("Mai = May")
print("Juni = June")
print("Juli = July")
print("August = August")
print("September = September")
print("Oktober = October")
print("November = November")
print("Dezember = December")

print(Fore.RED,"Lesson 6 - Seasons and Weathers")
print("")

print(Fore.WHITE, "Jahreszeiten = Seasons")
print("(der) Winter = Winter")
print("(der) Sommer = Summer")
print("(der) Frühling = Spring") 
print("(der) Herbst = Autumn")
print("(der) Himmel = Sky")
print("(die)Wolke = Cloud")
print("(der) Regenbogen = Rainbow")
print("Kalt = Cold (weather)")
print("Heiß = Hot (weather)")
print("Es ist heiß = It is hot")
print("Es ist kalt = It is cold")
print("Es ist sonnig = It is sunny")
print("Es ist bewölkt = It is cloudy")
print("Es ist schwül = It is humid")
print("Es regnet = It is raining")
print("Es schneit = It is snowing")
print("Es ist windig = It is windy")
print("Wie ist das Wetter? = How is the weather?")
print("Gutes Wetter = Good weather")
print("Schlechtes Wetter = Bad weather")
print("Wie viel Grad ist es? = What is the temperature")
print("Es ist vierundzwanzig Grad = It is 24 degrees")
          
print(Fore.RED,"Lesson 7 - Colors")
print("")

print(Fore.WHITE, "Schwarz = Black")
print("Blau = Blue")
print("Braun = Brown")
print("Grün = Green")
print("Orange = Orange")
print("Lila = Purple")
print("Rot = Red")
print("Weiß = White")
print("Gelb = Yellow")
print("Grau = Gray")
print("Gold = Gold")
print("Silber = Silver")
print("Welche Farbe ist das? = What color is it?")
print("Das ist ___ = The color is ___")
      
print(Fore.RED,"Lesson 8 - Family and Friends")
print("")

print(Fore.BLUE,"Lesson 8.1 - Family members")
print("")

print(Fore.WHITE, "(die) Mutter = Mother")
print("(der) Vater = Father")
print("(der) Bruder = Brother")
print("(die) Schwester = Sister")
print("(der) Sohn = Son")
print("(die) Tochter = Daughter")
print("(die) Eltern = Parents")
print("(die) Kinder = Children")
print("(das) Kind = Child")
print("(die) Stiefmutter = Stepmother")
print("(der) Stiefvater = Stepfather")
print("(die) Stiefschwester = Stepsister")
print("(der) Stiefbruder = Stepbrother")
print("(der) Schwiegersohn = Son-in-law")
print("(die) Schwiegertochter = Daughter-in-law")
print("(die) Ehefrau = Wife")
print("(der) Ehemann = Husband")
print("(die) Großeltern = Grandparents")
print("(der) Opa = Grandfather")
print("(die) Oma = Grandmother")
print("(der) Enkel = Grandson")
print("(die) Enkelin = Granddaughter")
print("(die) Enkelkinder = Grandchildren")
print("(das) Enkelkind  Grandchild")
print("(die) Tante = Aunt")
print("(der) Onkel = Uncle")
print("(die) Cousine = Cousin (female)")
print("(der) Cousin = Cousin (male)")
print("(der) Neffe = Nephew")
print("(die) Nichte = Niece")
print("(der) Schwiegervater = Father-in-law")
print("(die) Schwiegermutter = Mother-in-law")
print("(der) Schwager = Brother-in-law")
print("(die) Schwägerin = Sister-in-law")
print("(der) Verwandter = Relative")

print(Fore.BLUE,"Lesson 8.2 - Friends")
print("")

print(Fore.WHITE, "Fräulein = Miss")
print("(der) Junge = Boy")
print("(das) Mädchen = Girl")
print("(das) Baby = Baby")
print("(die) Frau = Woman")
print("(der) Mann = Man")
print("(der) Freund = Friend (male)")
print("(die) Freundin = Friend (female)")
print("(der) Freund = Boyfriend")
print("(die) Freundin = Girlfriend")
print("(der) Gentleman = Gentleman")
print("(die) Dame = Lady")
print("(der) Nachbar = Neighbor (male)")
print("(die) Nachbarin = Neighbor (female)")


print(Fore.BLUE,"Lesson 9 - Numbers from 11 to 30")
print("")

print(Fore.WHITE, "Elf = 11")
print("Zwölf = 12")
print("Dreizehn = 13")
print("Vierzehn = 14")
print("Fünfzehn = 15")
print("Sechzehn = 16")
print("Siebzehn = 17")
print("Achtzehn = 18")
print("Neunzehn = 19")
print("Zwanzig = 20")
print("Einundzwanzig = 21")
print("Zweiundzwanzig = 22")
print("Dreiundzwanzig = 23")
print("Vierundzwanzig = 24")
print("Fünfundzwanzig = 25")
print("Sechsundzwanzig = 26")
print("Siebenundzwanzig = 27")
print("Achtundzwanzig = 28")
print("Neunundzwanzig = 29")
print("Dreißig = 30")


print(Fore.RED,"Lesson 10 - Prepositions and Useful words")
print("")

print(Fore.BLUE,"Lesson 10.1 - Prepositions")
print("")

print(Fore.WHITE, "Für = For")
print("Von = From")
print("In = In")
print("Drinnen = Inside")    
print("In = Into")
print("Nah = Near")   
print("Von = Of") 
print("Aus = Out")    
print("Draußen = Outside")    
print("Zu = To")
print("Unter = Under")    
print("Mit = With")
print("Ohne = Without")    
print("Über = Above")
print("Über = Across")   
print("Nach = After") 
print("Gegen = Against")   
print("Entlang = Along") 
print("Um = Around")
print("Am = At")
print("Hinter = Behind")   
print("Unten = Below")
print("Neben = Beside")  
print("Zwischen = Between")   
print("An = By")
print("Während = During")    
print("Außer = Except")
print("Und = And")
print("Weil = Because")  
print("Aber = But")
print("Oder = Or") 
print("Überall = Everywhere")    
print("Jeder = Everyone")
print("Alles = Everything")    
print("Wenige = Few") 
print("Einige = Some")      
print("Viele = Many")


print(Fore.BLUE,"Lesson 10.2 - Useful Words")
print("")

print(Fore.WHITE, "(die) Frage = Question")   
print("(die) Antwort = Answer")
print("(die) Wahrheit = Truth") 
print("(die) Lüge = Lie")
print("Nichts = Nothing")  
print("Etwas = Something")  
print("Gleich = Same")
print("Unterschiedlich = Different")     
print("Ziehen = Pull")
print("Drücken = Push") 
print("Lang = Long")
print("Kurz = Short")  
print("Kalt = Cold") 
print("Heiß = Hot")  
print("Hell = Light")    
print("Dunkel = Dark")   
print("Nass = Wet")
print("Trocken = Dry")     
print("Leer = Empty") 
print("Voll = Full")  
print("Wie? = How?")
print("Was? = What?")
print("Wann? = When?")
print("Wo? = Where?")
print("Welche? = Which?")
print("Wer? = Who?")
print("Warum? = Why?")
print("Wie lange? = How long?")
print("Wie viel? = How much?")
      

print(Fore.RED,"Lesson 11 - Drinks and Meals")
print("")

print(Fore.BLUE,"Lesson 11.1 - Drinks")
print("")

print(Fore.WHITE, "(der) Kaffee = Coffee")
print("(der) Tee = Tea")
print("(das) Erfrischungsgetränk = Soft drink")
print("(das) Wasser = Water")
print("(die) Zitronenlimonade = Lemonade")
print("(der) Saft = Juice")
print("(der) Orangensaft = Orange juice")
print("Ich hätte gerne ein Glas Wasser, bitte = I would like a glass of water please")
print("Mit Eis = With ice")


print(Fore.BLUE,"Lesson 11.2 - Dairy Products")
print("")

print(Fore.WHITE, "(die) Milch = Milk")
print("(das) Eis = Ice cream")
print("(die) Butter = Butter")
print("(der) Käse = Cheese")
print("(der) Hüttenkäse = Cottage cheese")
print("(die) Sahne = Cream")
print("(die) Saure Sahne = Sour cream")
print("(der) Joghurt = Yogurt")
print("(die) Eier = Eggs")
print("(die) Schlagsahne = Whipping cream")
print("(die) Bäckerei = Bakery")
print("(das) Baguette = Baguette")
print("(der) Krapfen = Doughnut")
print("(das) Plätzchen = Cookie")
print("(das) Brötchen = Roll")
print("(der) Nachtisch = Dessert")
print("(der) Kuchen = Cake")
print("(das) Brot = Bread")
print("(die) Torte = Pie")


print(Fore.BLUE,"Lesson 11.3 - Meats")
print("")

print(Fore.WHITE, "(das) Rindfleisch = Beef")
print("(das) Kalbfleisch = Veal")
print("(der) Schinken = Ham")
print("(das) Huhn = Chicken")
print("(die) Pute = Turkey")
print("(die) Ente = Duck")
print("(der) Speck = Bacon")
print("(das) Schweinefleisch = Pork")
print("(das) Filet Mignon = Filet mignon")
print("(die) Würst = Sausage")
print("(das) Lammkotelett = Lamb chop")
print("(das) Schweinekotelett = Pork chop")
print("(das) Fleisch = Meat")
      

print(Fore.BLUE,"Lesson 11.4 - Seafoods")
print("")

print(Fore.WHITE, "(der) Fisch = Fish")
print("(die) Schalentier = Shellfish")
print("(der) Barsch = Bass")
print("(der) Lachs = Salmon")
print("(der) Hummer = Lobster")
print("(die) Krabbe = Crab")
print("(die) Muscheln = Mussel")
print("(die) Austern = Oyster")
print("(der) Kabeljau = Cod")
print("(die) Venusmuscheln = Clam")
print("(die) Garnelen = Shrimp")
print("(der) Thunfisch = Tuna")
print("(die) Forelle = Trout")
print("(die) Seezunge = Sole")
print("(der) Hai = Shark")
print("(der) Karpfen = Carp")
print("(der) Tilapia = Tilapia")
print("(der) Aal = Eel")
print("(der) Wels = Catfish")
print("(der) Schwertfisch = Swordfish")


print(Fore.BLUE,"Lesson 11.5 - Herbs and Spices")
print("")

print(Fore.WHITE, "(das) Salz = Salt")
print("(der) Pfeffer = Pepper")
print("(der) Kümmel = Caraway")
print("(der) Knoblauch = Garlic")
print("(das) Basilikum = Basil")
print("(der) Koriander = Coriander")
print("(der) Fenchel = Fennel")
print("(der) Majoran = Marjoram")
print("(der) Oregano = Oregano")
print("(die) Petersilie = Parsley")
print("(der) Rosmarin = Rosemary")
print("(der) Salbei = Sage")
print("(der) Thymian = Thyme")
print("(die) Muskatnuss = Nutmeg")
print("(der) Paprika = Paprika")
print("(der) Cayenne-Pfeffer = Cayenne")
print("(der) Ingwer = Ginger")


print(Fore.BLUE,"Lesson 11.6 - Vegetables")
print("")

print(Fore.WHITE, "(der) Sellerie = Celery")
print("(die) Aubergine = Eggplant")
print("(die) Zucchini = Zucchini")
print("(die) Zwiebel = Onion")
print("(der) Spinat = Spinach")
print("(der) Salat = Salad")
print("(die) Grüne Bohnen = Green beans")
print("(die) Gurke = Cucumber")
print("(das) Radieschen = Radish")
print("(der) Kohl = Cabbage")
print("(die) Pilze = Mushrooms")
print("(der) Salat = Lettuce")
print("(der) Mais = Corn")
print("(die) Kartoffeln = Potatoes")
print("(die) Tomate = Tomato")
print("(die) Möhre = Carrot")
print("(die) Kochbanane = Plantain")
print("(die) Bohnen = Beans")
print("(der) Lauch = Leek")
print("(die) Lotuswurzel = Lotus root")
print("(die) Bambussprosse = Bamboo shoot")
print("(die) Artischocke = Artichoke")
print("(der) Spargel = Asparagus")
print("(der) Rosenkohl = Brussels sprouts")
print("(der) Brokkoli = Broccoli")
print("(die) Erbsen = Peas")
print("(der) Blumenkohl = Cauliflower")
print("(der) Chili-Pfeffer = Chili pepper")


print(Fore.BLUE,"Lesson 11.7 - Fruits")
print("")

print(Fore.WHITE, "(die) Kirschen = Cherries")
print("(die) Himbeeren = Raspberries")
print("(die) Heidelbeeren = Blueberries")
print("(die) Erdbeeren = Strawberries")
print("(die) Zitrone = Lemon")
print("(die) Limette = Lime")
print("(der) Apfel = Apple")
print("(die) Orange = Orange")
print("(die) Birne = Pear")
print("(die) Banane = Banana")
print("(die) Trauben = Grapes")
print("(die) Grapefruit = Grapefruit")
print("(die) Wassermelone = Watermelon")
print("(die) Ananas = Pineapple")
print("(die) Pflaume = Plum")
print("(der) Pfirsich = Peach")
print("(die) Mango = Mango")
print("(die) Aprikose = Apricot")
print("(der) Granatapfel = Pomegranate")
print("(die) Kaki = Persimmon")
print("(die) Kiwi-Frucht = Kiwi")
print("(die) Litschi = Litchi")
print("(die) Longan-Frucht = Longan")
print("(die) Balsam-Birne = Balsam pear")
print("(die) Passionsfrucht = Passion fruit")
print("(die) Avocado = Avocado")
print("(die) Kokosnuss = Coconut")

print(Fore.BLUE,"Lesson 12 - Numbers from 31 to 50")
print("")

print(Fore.WHITE, "einunddreißig = 31")
print("zweiunddreißig = 32")
print("dreiunddreißig = 33")
print("vierunddreißig = 34")
print("fünfunddreißig = 35")
print("sechsunddreißig = 36")
print("siebenunddreißig = 37")	
print("achtunddreißig = 38")
print("neununddreißig = 39")
print("vierzig = 40")
print("einundvierzig = 41")	
print("zweiundvierzig = 42")	
print("dreiundvierzig = 43")
print("vierundvierzig = 44")
print("fünfundvierzig = 45")
print("sechsundvierzig = 46")
print("siebenundvierzig = 47")	
print("achtundvierzig = 48")
print("neunundvierzig = 49")
print("fünfzig = 50")

print(Fore.RED,"Lesson 13 - Irregular Verbs")

print(Fore.WHITE, "sein = to be")
print("haben = to have")
print("gehen = to go")
print("kommen = to come")
print("sehen = to see")
print("geben = to give")
print("essen = to eat")
print("trinken = to drink")
print("wissen = to know (fact)")
print("wollen = to want")
print("finden = to find")
print("laufen = to run")
print("sitzen = to sit")
print("liegen = to lie down")
print("stehen = to stand")
print("verstehen = to understand")
print("sagen = to say")
print("nehmen = to take")
print("schreiben = to write")
print("fallen = to fall")
print("beginnen = to begin")
print("brechen = to break")
print("bauen = to build")
print("wählen = to choose")
print("machen = to do/make")
print("fahren = to drive")
print("vergessen = to forget")
print("bekommen = to get")
print("hören = to hear")
print("halten = to hold")
print("verlassen = to leave")
print("treffen = to meet")
print("bezahlen = to pay")
print("legen/stellen = to put")
print("lesen = to read")
print("laufen = to run")
print("sehen = to see")
print("senden = to send")
print("schlafen = to sleep")
print("sprechen = to speak")
print("verbringen = to spend (time)")
print("schwimmen = to swim")
print("lehren = to teach")
print("erzählen = to tell")
print("denken = to think")
print("werfen = to throw")
print("verstehen = to understand")
print("gewinnen = to win")
print("schreiben = to write")
print("bringen = to bring")

print(Fore.RED,"Lesson 14 - Present Simple")

print(Fore.BLUE, "Example for sein = to be, essen = to eat, gehen = to go")

print(Fore.WHITE, "ich bin - ich esse - ich gehe")
print("du bist - du isst - el du gehst")
print("er/sie/es ist - er/sie/es isst - er/sie/es geht")
print("wir sind - wir essen - wir gehen")
print("ihr seid - ihr esst - ihr geht")
print("sie sind - sie essen - sie gehen") 



print(Fore.RED,"Lesson 15 - Physical Appearance")

print(Fore.WHITE, "groß = Tall")
print("klein = Short (height)")
print("schlank = Slim")
print("dick = Fat")
print("muskulös = Muscular")
print("blond = Blonde (hair)")
print("braunhaarig = Brown-haired")
print("schwarzhaarig = Black-haired")
print("lockiges Haar = Curly Hair")
print("glattes Haar = Straight Hair")
print("blaue Augen = Blue Eyes")
print("braune Augen = Brown Eyes")
print("grüne Augen = Green Eyes")
print("schön = Beautiful")
print("gutaussehend = Handsome")
print("hässlich = Ugly")
print("jung = Young")
print("alt = Old")
print("Bart = Beard")
print("helle Haut = Light-skinned")
print("dunkle Haut = Dark-skinned")
print("Sommersprossen = Freckles")
print("Falten = Wrinkles")
print("kahl = Bald")
print("behaart = Hairy (body)")
print("gerade Nase = Straight Nose")
print("große Nase = Big Nose")
print("kleine Nase = Small Nose")
print("schmale Lippen = Thin Lips")
print("volle Lippen = Full Lips")
print("breite Schultern = Broad Shoulders")
print("schmale Schultern = Narrow Shoulders")
print("gebräunte Haut = Tanned Skin")
print("blasse Haut = Pale Skin")
print("welliges Haar = Wavy Hair")
print("Pferdeschwanz = Ponytail")
print("Zöpfe = Braids")
print("Bart und Schnurrbart = Beard and Mustache")

print(Fore.RED,"Lesson  16 - Occupations")

print(Fore.WHITE, "Arzt / Ärztin = Doctor")
print("Lehrer / Lehrerin = Teacher")
print("Ingenieur / Ingenieurin = Engineer")
print("Anwalt / Anwältin = Lawyer")
print("Verkäufer / Verkäuferin = Salesperson")
print("Polizist / Polizistin = Police Officer")
print("Feuerwehrmann / Feuerwehrfrau = Firefighter")
print("Programmierer / Programmiererin = Programmer")
print("Koch / Köchin = Cook/Chef")
print("Journalist / Journalistin = Journalist")
print("Krankenpfleger / Krankenschwester = Nurse")
print("Architekt / Architektin = Architect")
print("Buchhalter / Buchhalterin = Accountant")
print("Apotheker / Apothekerin = Pharmacist")
print("Fahrer / Fahrerin = Driver")
print("Mechaniker / Mechanikerin = Mechanic")
print("Wissenschaftler / Wissenschaftlerin = Scientist")
print("Zahnarzt / Zahnärztin = Dentist")
print("Musiker / Musikerin = Musician")
print("Schauspieler / Schauspielerin = Actor")
print("Künstler / Künstlerin = Artist")
print("Pilot / Pilotin = Pilot")
print("Landwirt / Landwirtin = Farmer")
print("Fotograf / Fotografin = Photographer")
print("Kellner / Kellnerin = Waiter/Waitress")

print(Fore.RED,"Lesson 17 - Sports")

print(Fore.WHITE, "Fußball = Football / Soccer")
print("Basketball = Basketball")
print("Volleyball = Volleyball")
print("Tennis = Tennis")
print("Schwimmen = Swimming")
print("Laufen / Leichtathletik = Running / Athletics")
print("Eishockey = Ice Hockey")
print("Skifahren = Skiing")
print("Radfahren = Cycling")
print("Boxen = Boxing")
print("Kampfsport = Martial Arts")
print("Golf = Golf")
print("Tischtennis = Table Tennis")
print("Ringen = Wrestling")
print("Handball = Handball")
print("Baseball = Baseball")
print("Surfen = Surfing")
print("Eislaufen = Skating")
print("Reiten = Horse Riding")
print("Tauchen = Diving")
print("Kricket = Cricket")
print("Rugby = Rugby")
print("Ballett = Ballet")
print("Bowling = Bowling")
print("Gewichtheben = Weightlifting")
print("Windsurfen = Windsurfing")
print("Eislaufen = Ice Skating")
print("Rudern = Rowing")
print("Bogenschießen = Archery")
print("Klettern = Climbing")

print(Fore.RED,"Lesson 18 - Numbers 51-75")

print(Fore.WHITE, "einundfünfzig = 51")
print("zweiundfünfzig = 52")
print("dreiundfünfzig = 53")
print("vierundfünfzig = 54")
print("fünfundfünfzig = 55")
print("sechsundfünfzig = 56")
print("siebenundfünfzig = 57")
print("achtundfünfzig = 58")
print("neunundfünfzig = 59")
print("sechzig = 60")
print("einundsechzig = 61")
print("zweiundsechzig = 62")
print("dreiundsechzig = 63")
print("vierundsechzig = 64")
print("fünfundsechzig = 65")
print("sechsundsechzig = 66")
print("siebenundsechzig = 67")
print("achtundsechzig = 68")
print("neunundsechzig = 69")
print("siebzig = 70")
print("einundsiebzig = 71")
print("zweiundsiebzig = 72")
print("dreiundsiebzig = 73")
print("vierundsiebzig = 74")
print("fünfundsiebzig = 75")

print(Fore.RED,"Lesson 19 - Clothing")

print(Fore.WHITE, "das Hemd = Shirt")
print("das T-Shirt = T-shirt")
print("die Bluse = Blouse")
print("der Pullover = Sweater / Jumper")
print("die Jacke = Jacket")
print("der Mantel = Coat")
print("das Kleid = Dress")
print("der Rock = Skirt")
print("die Hose = Pants / Trousers")
print("die Shorts= Shorts (plural)")
print("die Schuhe = Shoes (plural)")
print("die Stiefel = Boots (plural)")
print("die Turnschuhe = Sneakers (plural)")
print("die Sandalen = Sandals (plural)")
print("die Mütze / der Hut = Hat / Cap")
print("der Schal = Scarf")
print("die Handschuhe = Gloves (plural)")
print("der Gürtel = Belt")
print("die Socken = Socks (plural)")
print("Wintermantel = Winter Coat")
print("Wollmütze = Wool Hat")
print("Schal = Scarf")
print("Handschuhe = Gloves")
print("Schneestiefel = Snow Boots")
print("Badeanzug = Swimsuit")
print("Sonnenbrille = Sunglasses")
print("Flip-Flops = Flip-flops")
print("Shorts = Shorts")
print("Top = Tank Top")
print("Anzug = Suit")
print("Krawatte = Tie")
print("Blazer = Blazer")
print("High Heels = High Heels")
print("Abendkleid = Evening Dress")
print("schwarz = Black")
print("weiß = White")
print("rot = Red")
print("blau = Blue")
print("grün = Green")
print("Baumwolle = Cotton")
print("Wolle = Wool")
print("Leder = Leather")
print("Seide = Silk")
print("Leinen = Linen")

print(Fore.RED,"Lesson 20 - Avderbs")

print(Fore.WHITE, "schnell = quickly")
print("langsam = slowly")
print("immer = always")
print("nie = never")
print("oft = often")
print("manchmal = sometimes")
print("selten = rarely")
print("schon = already")
print("noch = still")
print("noch = yet")
print("bald = soon")
print("jetzt = now")
print("später = later")
print("heute = today")
print("morgen = tomorrow")
print("gestern = yesterday")
print("klar = clearly")
print("zusammen = together")
print("getrennt = apart")
print("für immer = forever")

print(Fore.RED,"Lesson 21 - Animals")

print(Fore.WHITE, "Hund = dog")
print("Katze = cat")
print("Pferd = horse")
print("Kuh = cow")
print("Schaf = sheep")
print("Schwein = pig")
print("Ziege = goat")
print("Huhn = chicken")
print("Ente = duck")
print("Vogel = bird")
print("Kaninchen = rabbit")
print("Maus = mouse")
print("Löwe = lion")
print("Tiger = tiger")
print("Bär = bear")
print("Elefant = elephant")
print("Affe = monkey")
print("Fuchs = fox")
print("Wolf = wolf")
print("Reh = deer")

print(Fore.RED,"Lesson 22 - Place in town")

print(Fore.WHITE, "Schule = school")
print("Krankenhaus = hospital")
print("Bank = bank")
print("Restaurant = restaurant")
print("Bibliothek = library")
print("Supermarkt = supermarket")
print("Kino = cinema")
print("Post = post office")
print("Polizeistation = police station")
print("Park = park")
print("Museum = museum")
print("Theater = theatre")
print("Hotel = hotel")
print("Stadion = stadium")
print("Kirche = church")
print("Apotheke = pharmacy")
print("Bäckerei = bakery")
print("Metzgerei = butcher")
print("Markt = market")
print("Friseur = hairdresser")

print(Fore.RED,"Lesson 23 - School Supplies")

print(Fore.WHITE, "Buch = book")
print("Stift = pen")
print("Bleistift = pencil")
print("Radiergummi = eraser")
print("Heft = notebook")
print("Lineal = ruler")
print("Schere = scissors")
print("Rucksack = backpack")
print("Ordner = folder")
print("Taschenrechner = calculator")
print("Marker = marker")
print("Kreide = chalk")
print("Karte = map")
print("Textmarker = highlighter")
print("Projektor = projector")
print("Laptop = laptop")
print("Drucker = printer")
print("USB-Stick = USB stick")
print("Schultasche = schoolbag")
print("Spitzer = sharpener")

print(Fore.RED,"Lesson 24 - Transportation")

print(Fore.WHITE, "Auto = car")
print("Bus = bus")
print("Zug = train")
print("Fahrrad = bicycle")
print("Motorrad = motorcycle")
print("Flugzeug = airplane")
print("Boot = boat")
print("Straßenbahn = tram")
print("Taxi = taxi")
print("U-Bahn = subway")
print("Fähre = ferry")
print("Yacht = yacht")
print("Heißluftballon = hot air balloon")
print("Raumschiff = spaceship")
print("Rikscha = rickshaw")
print("Gondel = gondola")
print("Zeppelin = zeppelin")
print("Inlineskates = rollerblades")
print("Kanu = canoe")
print("U-Boot = submarine")

print(Fore.BLUE,"Lesson 25 - Numbers 76 - 110")

print(Fore.WHITE)


print(Fore.RED,"Lesson 26 - Numbers 111 - 150")
print(Fore.WHITE)

print(Fore.RED,"Lesson 27 - Past Simple")
print(Fore.WHITE)

print(Fore.RED,"Lesson 28 - Personality_ Treats")
print(Fore.WHITE)

print(Fore.RED,"Lesson 29 - Present perfect")
print(Fore.WHITE)

print(Fore.RED,"Lesson 30 - Numbers 151 - 190")
print(Fore.WHITE)

print(Fore.RED,"Lesson 31 - Countries")
print(Fore.WHITE)

print(Fore.RED,"Lesson 32 - Ordering")
print(Fore.WHITE)

print(Fore.RED,"Lesson 33 - Shops in town")
print(Fore.WHITE)

print(Fore.RED,"Lesson 34 - Numbers 191 - 230")
print(Fore.WHITE)

print(Fore.RED,"Lesson 35 - Thing in the street")
print(Fore.WHITE)

print(Fore.RED,"Lesson 36 - Instruments")
print(Fore.WHITE)







