import keyboard

import colorama
from colorama import Fore, init
init()
print(Fore.RED,"1'den 10' a Sayılar")
print(Fore.WHITE,"uno = ?, due = ?, tre = ?, quattro = ?, cinque = ?, sei = ?, sette = ?, otto = ?, nove = ?, dieci = ?")
print("")

mesaj = "uno: "
uno     = input(mesaj)
mesaj = "dos: "
due     = input(mesaj)
mesaj = "tre: "
tre     = input(mesaj)
mesaj = "quattro:"
quattro = input(mesaj)
mesaj = "cinque:"
cinque  = input(mesaj)
mesaj = "sei: "
sei     = input(mesaj)
mesaj = "sette: "
sette   = input(mesaj)
mesaj = "otto: "
otto    = input(mesaj)
mesaj = "nove: "
nove    = input(mesaj)
mesaj = "dieci: "
dieci   = input(mesaj)
print("")

print("Devam etmek için spacebar'a basınız.")
keyboard.wait("space")

print("")

print("uno = 1, dos = 2, tres = 3, cuatro = 4, cinco = 5, seis = 6, siete = 7, ocho = 8, nueve = 9, diez = 10")
print("")

print("İşlemler")

print("")
sayi1 = int(input("Birinci sayiyi giriniz:"))
sayi2 = int(input("İkinci sayiyi giriniz:"))
print("")

toplam = sayi1 + sayi2
print("")
print(toplam)

print(Fore.RED, "Lesson 2 - Greeting")
print("")
print(Fore.WHITE,"Cioa = Hello")
print("Come stai = How are you?")
print("Felice di vederti = Nice to see you")
print("Piacere di conoscerti = Nice to meet you")
print("A domani = See you tomorrow")
print("Buon giorno  = Good morning")
print("Buon pomeriggio = Good afternoon")
print("Buona srea = Godd evening")
print("Buona notte = Good night")
print("Come ti chiami ?  = What is your name ?")
print("Mi chiamo____ = My name is ___")
print("Dóve vive ? = Where do you live?")
print("Di dove sei ? = Where are you from?")
print("Buona giornata = Have a nice day")
print("A dopo = See you later")
print("Arrivederci = Goodbye")
print("Per favore = Please")
print("Grazie = Thank you")

print(Fore.RED, "Lesson_3 = Regular Verbs,")

print(Fore.WHITE,"Regular verbs are divided into 3 categories")

print(Fore.BLUE, "1. -Are Verbs")

print(Fore.WHITE, "abitare to live, inhabit")
print("aiutare = to help")
print("amare = to love")
print("arrivare	= to arrive")
print("ascoltare = to listen to")
print("aspettare = to wait for")
print("baciare*	= to kiss")
print("conservare = to conserve, keep")
print("considerare = to consider")
print("consigliare*	= to advise")
print("costare = to cost")
print("causare = to cause")
print("cenare = to have dinner")
print("chiamare = to call")
print("cominciare* = to begin, start")
print("comprare	= to buy")
print("insegnare = to teach")
print("lamentare = to complain")
print("lasciare* = to leave")
print("lavare = to wash")
print("lavorare	= to work")
print("mangiare* = to eat")
print("nuotare = to swim")
print("cucinare	= to cook")
print("curare = to take care of, treat")
print("disegnare = to draw")
print("incontrare = to meet, encounter")
print("indossare = to wear, put on")
print("diventare = to become")
print("dubitare	= to doubt")
print("entrare = to enter")
print("evitare = to avoid")
print("fumare = to smoke")
print("guardare	= to watch, look")
print("guidare = to drive")
print("imparare	= to learn")
print("bastare = to suffice, be enough")
print("camminare = to walk")
print("cantare = to sing")
print("ordinare	= to organize, sort, put in order")
print("parlare = to speak")
print("passare = to pass, go by; to drop in; to spend time")
print("pensare = to think")
print("portare = to take, bring")
print("pranzare	= to have lunch")
print("prenotare = to book, reserve")
print("provare = to try")
print("restare = to stay, remain")
print("ricordare = to remember")
print("salutare	= to greet, say hello")
print("salvare = to save")
print("sbagliare* = to make a mistake, be wrong")
print("sperare = to hope")
print("studiare* = to study")
print("tagliare* = to cut")
print("tornare = to return, go back")
print("trovare = to find")
print("viaggiare* = to travel")
print("visitare	= to visit")

print(Fore.BLUE, "2. -Ere Verbs")

print(Fore.WHITE, "accedere to access")
print("accendere = to turn on")
print("apprendere = to learn")
print("assumere = to assume; to hire, employ")
print("attendere = to wait for")
print("battere = to beat")
print("chiedere = to ask")
print("chiudere = to close")
print("comprendere = to understand, to include")
print("conoscere = to know")
print("correre	= to run, hurry")
print("credere	= to believe")
print("decedere = to die")
print("decidere = to decide")
print("descrivere = to describe")
print("dibattere = to debate")
print("discutere = to discuss")
print("mettere	= to put")
print("perdere	= to lose")
print("precedere = to precede")
print("premere	= to press")
print("prendere = to take")
print("pretendere = to claim")
print("promettere = to promise")
print("rendere	= to give back, return")
print("ricevere = to receive")
print("ridere = to laugh")
print("ripetere = to repeat")
print("rispondere = to answer")
print("rompere = to break")
print("scendere = to descend, go down")
print("scrivere = to write")
print("sorridere = to smile")
print("spendere = to spend")
print("temere = to fear")
print("tessere	= to weave")
print("vedere = to see")
print("vendere	= to sell")
print("vivere = to live")

print(Fore.BLUE, "3. -Ire Verbs")

print(Fore.WHITE, "aborrire** = to abhor")
print("acconsentire = to agree, consent")
print("applaudire** = to applaud, clap")
print("aprire = to open")
print("assentire = to assent")
print("assorbire** =  to absorb")
print("avvertire = to warn")
print("bollire = to boil")
print("compartire** = to share, to divide")
print("convertire = to convert")
print("coprire = to cover")
print("cucire*** = to sew")
print("divertire = to enjoy, amuse")
print("dormire = to sleep")
print("fuggire = to escape, flee")
print("inghiottire** = to swallow")
print("mentire** = to lie")
print("nutrire** = to feed")
print("offrire = to offer")
print("partire = to leave, to start")
print("riaprire = to reopen")
print("riempire = to fill")
print("scoprire = to discover, to uncover")
print("seguire = to follow")
print("sentire = to feel, hear, smell, taste, sense")
print("servire = to serve")
print("soffrire = to suffer")
print("tossire** = to cough")
print("vestire to dress, to wear")

print(Fore.RED,"Lesson 3.1 - Present Tense")           

print(Fore.WHITE,"I = io")
print("you = tu")
print("he/she/it = lui/lei")
print("we = noi")
print("you = voi")
print("they = loro")

print("Example for parlare = to speak, credere = to believe and dormire = to sleep")

print("yo parlo - yo credo - yo dormo")
print("tu parli - tu credi dormi")
print("lui/lei parla - lui/lei corede - lui/lei dorme")
print("noi parliamo - nosotros crediamo, noi dormiamo")
print("voi parlatr - vosotros credete - voi dormite")
print("loro parlano - loro credono - loro dormono")

print(Fore.BLUE, "Lesson 4 = Adjectives")

print(Fore.WHITE, "Felice = Happy")
print("Triste = Sad")
print("Arrabbiato = Angry")
print("Spaventato = Afraid")
print("Gioia = Joy")
print("Sorpreso = Surprised")
print("Calmo = Calm")
print("Annoiato = Bored")
print("Facile = Easy")
print("Difficile = Difficult")
print("Cattivo = Bad")
print("Buono = Good")
print("Rumoroso = Noisy")
print("Silenzioso = Quiet")
print("Forte = Strong")
print("Debole = Weak")
print("Duro = Hard")
print("Morbido = Soft")
print("Più = More")
print("Meno = Less")
print("Pulito = Clean")
print("Sporco = Dirty")
print("Vecchio = Old")
print("Nuovo = New")
print("Grande = Big")
print("Piccolo = Small")
print("Giovane = Young")
print("Magro = Skinny")
print("Grasso = Fat")
print("Bello = Pretty") 
print("Brutto = Ugly")
print("Spesso = Thick")
print("Sottile = Thin")
print("Ruvido = Rough")
print("Liscio = Smooth")
print("")

print(Fore.RED,"Lesson 5 - Days and Months")
print("")

print(Fore.BLUE,"Lesson 5.1 - Days of the week")
print("")

print(Fore.WHITE,"I giorni della settimana = The days of the week")
print("Giorno = Day")
print("Settimana = Week")
print("Lunedì = Monday")
print("Martedì = Tuesday")
print("Mercoledì = Wednesday")
print("Giovedì = Thursday")
print("Venerdì = Friday")
print("Sabato = Saturday")
print("Domenica = Sunday")
print("Fine settimana = Weekend")
print("")

print(Fore.RED,"Lesson 5.2 - Months of the year")
print("")

print(Fore.WHITE,"I mesi dell’anno = The months of the year")
print("Mese = Month")
print("Anno = Year")
print("Gennaio = January")
print("Febbraio = February")
print("Marzo = March")
print("Aprile = April")
print("Maggio = May")
print("Giugno = June")
print("Luglio = July")
print("Agosto = August")
print("Settembre = September")
print("Ottobre = October")
print("Novembre = November")
print("Dicembre = December")
print("")

print(Fore.RED,"Lesson 6 - Seasons and Weathers")
print("")

print(Fore.WHITE, "Stagioni = Seasons")
print("Inverno = Winter")
print("Estate = Summer")
print("Primavera = Spring")
print("Autunno = Autumn")
print("Cielo = Sky")
print("Nuvola = Cloud")
print("Arcobaleno = Rainbow")
print("Freddo = Cold (weather)")
print("Caldo = Hot (weather)")
print("Fa caldo = It is hot")
print("Fa freddo = It is cold")
print("C’è il sole = It is sunny")
print("È nuvoloso = It is cloudy")
print("È umido = It is humid")
print("Piove = It is raining")
print("Nevica = It is snowing")
print("C’è vento = It is windy")
print("Com’è il tempo? = How is the weather?")
print("Bel tempo = Good weather")
print("Maltempo = Bad weather")
print("Che temperatura c’è? = What is the temperature?")
print("Ci sono ventiquattro gradi = It is 24 degrees")
print("")     

print(Fore.RED,"Lesson 7 - Colors")
print("")

print(Fore.WHITE,"Nero = Black")
print("Blu = Blue")
print("Marrone = Brown")
print("Verde = Green")
print("Arancione = Orange")
print("Viola = Purple")
print("Rosso = Red")
print("Bianco = White")
print("Giallo = Yellow")
print("Grigio = Gray")
print("Oro = Gold")
print("Argento = Silver")
print("Che colore è? = What color is it?")
print("Il colore è ____ = The color is ___")
print("")

print(Fore.RED,"Lesson 8 - Family and Friends")
print("")

print(Fore.BLUE,"Lesson 8.1 - Family members")
print("")

print(Fore.WHITE,"Madre = Mother")
print("Padre = Father")
print("Fratello = Brother")
print("Sorella = Sister")
print("Figlio = Son")
print("Figlia = Daughter")
print("Genitori = Parents")
print("Bambini = Children")
print("Bambino = Child")
print("Madre acquisita = Stepmother")
print("Padre acquisito = Stepfather")
print("Sorella acquisita = Stepsister")
print("Fratello acquisito = Stepbrother")
print("Genero = Son-in-law")
print("Nuora = Daughter-in-law")
print("Moglie = Wife")
print("Marito = Husband")
print("Nonni = Grandparents")
print("Nonno = Grandfather")
print("Nonna = Grandmother")
print("Nipotino = Grandson")
print("Nipotina = Granddaughter")
print("Nipotini = Grandchildren")
print("Nipotino = Grandchild")
print("Zia = Aunt")
print("Zio = Uncle")
print("Cugina = Cousin (female)")
print("Cugino = Cousin (male)")
print("Nipote = Nephew")
print("Nipote = Niece")
print("Suocero = Father-in-law")
print("Suocera = Mother-in-law")
print("Cognato = Brother-in-law")
print("Cognata = Sister-in-law")
print("Parente = Relative")
print("")
 
print(Fore.BLUE,"Lesson 8.2 - Friends")
print("")

print(Fore.WHITE,"Signorina = Miss")
print("Ragazzo = Boy")
print("Ragazza = Girl")
print("Bebè = Baby")
print("Donna = Woman")
print("Uomo = Man")
print("Amico = Friend (male)")
print("Amica = Friend (female)")
print("Fidanzato = Boyfriend")
print("Fidanzata = Girlfriend")
print("Signore = Gentleman")
print("Signora = Lady")
print("Vicino = Neighbor (male)")
print("Vicina di casa = Neighbor (female)")
print("")

print(Fore.BLUE,"Lesson 9 - Numbers from 11 to 30")
print("")

print(Fore.WHITE, "Undici = 11")
print("Dodici = 12")
print("Tredici = 13")
print("Quattordici = 14")
print("Quindici = 15")
print("Sedici = 16")
print("Diciassette = 17")
print("Diciotto = 18")
print("Diciannove = 19")
print("Venti = 20")
print("Ventuno = 21")
print("Ventidue = 22")
print("Ventitrè = 23")
print("Ventiquattro = 24")
print("Venticinque = 25")
print("Ventisei = 26")
print("Ventisette = 27")
print("Ventotto = 28")
print("Ventinove = 29")
print("Trenta = 30")

print(Fore.RED,"Lesson 10 - Prepositions and Useful words")
print("")

print(Fore.BLUE,"Lesson 10.1 - Prepositions")
print("")

print(Fore.WHITE, "Per = For")
print("Da = From")
print("In = In")
print("Dentro = Inside")
print("In = Into")
print("Vicino = Near")
print("Di = Of")
print("Fuori = Out")
print("Fuori = Outside")
print("A = To")
print("Sotto = Under")
print("Con = With")
print("Senza = Without")
print("Sopra = Above")
print("Attraverso = Across")
print("Dopo = After")
print("Contro = Against")
print("Lungo = Along")
print("Intorno = Around")
print("A = At")
print("Dietro = Behind")
print("In basso = Below")
print("Accanto a = Beside")
print("Fra = Between")
print("Da = By")
print("Durante = During")
print("Tranne = Except")
print("E = And")
print("Perché = Because")
print("Ma = But")
print("O = Or")
print("Dappertutto = Everywhere")
print("Tutti = Everyone")
print("Tutto = Everything")
print("Pochi = Few")
print("Alcuni = Some")
print("Molti = Many")
    

print(Fore.BLUE,"Lesson 10.2 - Useful Words")
print("")

print(Fore.WHITE, "Domanda = Question")
print("Risposta = Answer")
print("Verità = Truth")
print("Bugia = Lie")
print("Niente = Nothing")
print("Qualcosa = Something")
print("Identico = Same")
print("Diverso = Different")
print("Tirare = Pull")
print("Spingere = Push")
print("Lungo = Long")
print("Corto = Short")
print("Freddo = Cold")
print("Caldo = Hot")
print("Chiaro = Light")
print("Scuro = Dark")
print("Bagnato = Wet")
print("Asciutto = Dry")
print("Vuoto = Empty")
print("Pieno = Full")
print("Come? = How?")
print("Cosa? = What?")
print("Quando? = When?")
print("Dove? = Where?")
print("Quale? = Which?")
print("Chi? = Who?")
print("Perché? = Why?")
print("Quanto tempo? = How long?")
print("Quanto? = How much?")
      

print(Fore.RED,"Lesson 11 - Drinks and Meals")
print("")

print(Fore.BLUE,"Lesson 11.1 - Drinks")
print("")

print(Fore.WHITE, "Caffè = Coffee")
print("Tè = Tea")
print("Bibita = Soft drink")
print("Acqua = Water")
print("Limonata = Lemonade")
print("Succo di frutta = Juice")
print("Aranciata = Orange juice")
print("Un bicchiere d’acqua, per favore = I would like a glass of water please")
print("Con ghiaccio = With ice")


print(Fore.BLUE,"Lesson 11.2 - Dairy Products")
print("")

print(Fore.WHITE, "Latte = Milk")
print("Gelato = Ice cream")
print("Burro = Butter")
print("Formaggio = Cheese")      
print("Fiocchi di latte = Cottage cheese")      
print("Panna = Cream")
print("Panna acida = Sour cream")
print("Yogurt = Yogurt")
print("Uova = Eggs")
print("Panna da montare = Whipping cream")
print("Panificio = Bakery")
print("Filoncino = Baguette")     
print("Ciambella = Doughnut")    
print("Biscotto = Cookie")  
print("Rosetta di pane = Roll")      
print("Dolci = Dessert")
print("Torta = Cake")
print("Pane = Bread")   
print("Crostata = Pie")


print(Fore.BLUE,"Lesson 11.3 - Meats")
print("")

print(Fore.WHITE, "Manzo = Beef")     
print("Vitello = Veal")
print("Prosciutto = Ham")    
print("Pollo = Chicken") 
print("Tacchino = Turkey")    
print("Anatra = Duck")
print("Pancetta = Bacon")    
print("Maiale = Pork")
print("Filetto = Filet mignon")    
print("Salsiccia = Sausage")
print("Braciola di agnello = Lamb chop")     
print("Braciola di maiale = Pork chop")   
print("Carne = Meat")
      

print(Fore.BLUE,"Lesson 11.4 - Seafoods")
print("")

print(Fore.WHITE, "Pesce = Fish") 
print("Crostacei = Shellfish")
print("Branzino = Bass")
print("Salmone = Salmon")     
print("Aragosta = Lobster")     
print("Granchio = Crab") 
print("Cozza = Mussel")   
print("Ostrica = Oyster")     
print("Merluzzo = Cod") 
print("Vongola = Clam")   
print("Gambero = Shrimp")    
print("Tonno = Tuna")
print("Trota = Trout")   
print("Sogliola = Sole")   
print("Squalo = Shark") 
print("Carpa = Carp")
print("Tilapia = Tilapia")   
print("Anguilla = Eel")
print("Pesce gatto = Catfish")     
print("Pesce spada = Swordfish")


print(Fore.BLUE,"Lesson 11.5 - Herbs and Spices")
print("")

print(Fore.WHITE, "Sale = Salt")
print("Pepe = Pepper")
print("Cumino = Caraway")     
print("Aglio = Garlic")  
print("Basilico = Basil")    
print("Coriandolo = Coriander")     
print("Finocchio = Fennel")
print("Maggiorana = Marjoram")     
print("Origano = Oregano")
print("Prezzemolo = Parsley")      
print("Rosmarino = Rosemary")    
print("Salvia = Sage")
print("Timo = Thyme")  
print("Noce moscata = Nutmeg")     
print("Paprika = Paprika")
print("Pepe di Caienna = Cayenne")    
print("Ginger = Zenzero")


print(Fore.BLUE,"Lesson 11.6 - Vegetables")
print("")

print(Fore.WHITE, "Sedano = Celery")
print("Melanzana = Eggplant")
print("Zucchine = Zucchini") 
print("Cipolla = Onion")
print("Spinaci = Spinach")    
print("Insalata = Salad")  
print("Fagiolini = Green beans")     
print("Cetriolo = Cucumber")
print("Ravanello = Radish") 
print("Cavolo = Cabbage") 
print("Funghi = Mushrooms")     
print("Lattuga = Lettuce")  
print("Mais = Corn")
print("Patate = Potatoes")    
print("Pomodoro = Tomato") 
print("Carota = Carrot")
print("Banana platano = Plantain")
print("Fagioli = Beans")
print("Porro = Leek")
print("Radice di loto = Lotus root")    
print("Germoglio di bambù = Bamboo shoot")     
print("Carciofo = Artichoke")
print("Asparagi = Asparagus")  
print("Cavolini di Bruxelles = Brussels sprouts")    
print("Broccoli = Broccoli")
print("Piselli = Peas")
print("Cavolfiore = Cauliflower")    
print("Peperoncino = Chili pepper")


print(Fore.BLUE,"Lesson 11.7 - Fruits")
print("")

print(Fore.WHITE, "Ciliegie = Cherries") 
print("Lamponi = Raspberries")
print("Mirtilli = Blueberries")   
print("Fragole = Strawberries")  
print("Limone = Lemon")
print("Lime = Lime")
print("Mela = Apple")    
print("Arancia = Orange")   
print("Pera = Pear")
print("Banana = Banana")
print("Uva = Grapes")
print("Pompelmo = Grapefruit")    
print("Anguria = Watermelon") 
print("Ananas = Pineapple")
print("Prugna = Plum")
print("Pesca = Peach")   
print("Mango = Mango")
print("Albicocca = Apricot")   
print("Melograno = Pomegranate")   
print("Caco = Persimmon")
print("Kiwi = Kiwi")
print("Litchi = Litchi")
print("Longan = Longan")
print("Zucca amara = Balsam pear")    
print("Frutto della passione = Passion fruit")     
print("Avocado = Avocado")
print("Cocco = Coconut")


print(Fore.BLUE,"Lesson 12 - Numbers from 31 to 50")
print("")

print(Fore.WHITE, "trentuno = 31")
print("trentadue = 32")
print("trentatré = 33")
print("trentaquattro = 34")	
print("trentacinque = 35")
print("trentasei = 36")
print("trentasette = 37")	
print("trentotto = 38")
print("trentanove = 39")	
print("quaranta = 40")
print("quarantuno = 41")	
print("quarantadue = 42")
print("quarantatré = 43")
print("quarantaquattro = 44")	
print("quarantacinque = 45")
print("quarantasei = 46")
print("quarantasette = 47")	
print("quarantotto = 48")
print("quarantanove = 49")	
print("cinquanta = 50")

print(Fore.RED,"Lesson 13 - Irregular Verbs")

print(Fore.BLUE,"Lesson 13.1 - -Are Verbs")

print(Fore.WHITE, "andare = to go")
print("dare = to give")
print("trovare = to find")
print("stare = to stand")
print("cominciare = to begin")
print("fare = to do/make")
print("guidare = to drive")
print("dimenticare = to forget")
print("incontrare = to meet")
print("pagare = to pay")
print("parlare = to speak")
print("passare = to spend (time)")
print("nuotare = to swim")
print("insegnare = to teach")
print("raccontare = to tell")
print("pensare = to think")
print("lanciare = to throw")
print("portare = to bring")
print("inviare = to send")


print(Fore.RED,"Lesson 13.2 - -Ere Verbs")

print(Fore.WHITE, "essere = to be")
print("avere = to have")
print("vedere = to see")
print("bere = to drink")
print("sapere = to know (fact)")
print("volere = to want")
print("correre = to run")
print("sedere = to sit")
print("giacere = to lie down")
print("prendere = to take")
print("scrivere = to write")
print("cadere = to fall")
print("rompere = to break")
print("mettere = to put")
print("leggere = to read")
print("correre = to run")
print("vedere = to see")
print("ottenere = to get")
print("tenere = to hold")
print("vincere = to win")
print("scegliere = to choose")
print("scrivere = to write")

print(Fore.RED,"Lesson 13.3 - Ire Verbs")

print(Fore.WHITE, "venire = to come")
print("mangiare = to eat")
print("capire = to understand")
print("dire = to say")
print("dormire = to sleep")
print("costruire = to build")
print("capire = to understand")
print("sentire = to hear")
print("partire = to leave")

print(Fore.RED,"Lesson 14 - Present Simple")

print(Fore.BLUE, "Example for essere = to be, mangiare = to eat and andare = to go")

print(Fore.WHITE, "io sono - io mangio - io vado")
print("tu sei - tu mangi - tu vai - tu vas")
print("lui/lei è - lui/lei mangia - lui/lei va")
print("noi siamo - noi mangiamo, noi andiamo")
print("voi siete - voi mangiate - voi andate")
print("loro sono - loro mangiano - loro vanno")

print(Fore.RED,"Lesson 15 - Physical Appearance")

print(Fore.WHITE, "alto = Tall")
print("basso = Short (height)")
print("snello = Slim")
print("grasso = Fat")
print("muscoloso = Muscular")
print("biondo = Blonde (hair)")
print("castano = Brown-haired")
print("moro = Black-haired")
print("ricci = Curly Hair")
print("lisci = Straight Hair")
print("occhi azzurri = Blue Eyes")
print("occhi castani = Brown Eyes")
print("occhi verdi = Green Eyes")
print("bello / bella = Beautiful")
print("bello = Handsome")
print("brutto = Ugly")
print("giovane = Young")
print("vecchio = Old")
print("barba = Beard")
print("pelle chiara = Light-skinned")
print("pelle scura = Dark-skinned")
print("lentiggini = Freckles")
print("rughe = Wrinkles")
print("calvo = Bald")
print("peloso = Hairy (body)")
print("naso dritto = Straight Nose")
print("naso grande = Big Nose")
print("naso piccolo = Small Nose")
print("labbra sottili = Thin Lips")
print("labbra carnose = Full Lips")
print("spalle larghe = Broad Shoulders")
print("spalle strette = Narrow Shoulders")
print("pelle abbronzata = Tanned Skin")
print("pelle pallida = Pale Skin")
print("capelli mossi = Wavy Hair")
print("coda di cavallo = Ponytail")
print("trecce = Braids")
print("barba e baffi = Beard and Mustache")

print(Fore.RED,"Lesson  16 - Occupations")

print(Fore.WHITE, "dottore / medico = Doctor")
print("insegnante = Teacher")
print("ingegnere = Engineer")
print("avvocato = Lawyer")
print("commesso = Salesperson")
print("poliziotto = Police Officer")
print("pompiere = Firefighter")
print("programmatore = Programmer")
print("cuoco = Cook/Chef")
print("giornalista = Journalist")
print("infermiere/infermiera = Nurse")
print("architetto = Architect")
print("contabile = Accountant")
print("farmacista = Pharmacist")
print("autista = Driver")
print("meccanico = Mechanic")
print("scienziato = Scientist")
print("dentista = Dentist")
print("musicista = Musician")
print("attore/attrice = Actor")
print("artista = Artist")
print("pilota = Pilot")
print("contadino = Farmer")
print("fotografo = Photographer")
print("cameriere/cameriera = Waiter/Waitress")

print(Fore.RED,"Lesson 17 - Sports")

print(Fore.WHITE, "calcio = Football / Soccer")
print("pallacanestro = Basketball")
print("pallavolo = Volleyball")
print("tennis = Tennis")
print("nuoto = Swimming")
print("corsa / atletica = Running / Athletics")
print("hockey su ghiaccio = Ice Hockey")
print("sci = Skiing")
print("ciclismo = Cycling")
print("pugilato / boxe = Boxing")
print("arti marziali = Martial Arts")
print("golf = Golf")
print("tennis da tavolo = Table Tennis")
print("lotta = Wrestling")
print("pallamano = Handball")
print("baseball = Baseball")
print("surf = Surfing")
print("pattinaggio = Skating")
print("equitazione = Horse Riding")
print("immersione = Diving")
print("cricket = Cricket")
print("rugby = Rugby")
print("balletto = Ballet")
print("bowling = Bowling")
print("sollevamento pesi = Weightlifting")
print("windsurf = Windsurfing")
print("pattinaggio su ghiaccio = Ice Skating")
print("canottaggio = Rowing")
print("tiro con l'arco	= rchery")
print("arrampicata = Climbing")

print(Fore.RED, "Lesson 18 - Numbers 51-75")

print(Fore.WHITE, "cinquantuno = 51")
print("cinquantadue = 52")
print("cinquantatré = 53")
print("cinquantaquattro = 54")
print("cinquantacinque = 55")
print("cinquantasei = 56")
print("cinquantasette = 57")
print("cinquantotto = 58")
print("cinquantanove = 59")
print("sessanta = 60")
print("sessantuno = 61")
print("sessantadue = 62")
print("sessantatré = 63")
print("sessantaquattro = 64")
print("sessantacinque = 65")
print("sessantasei = 66")
print("sessantasette = 67")
print("sessantotto = 68")
print("sessantanove = 69")
print("settanta = 70")
print("settantuno = 71")
print("settantadue = 72")
print("settantatré = 73")
print("settantquattro = 74")
print("settantacinque = 75")

print(Fore.RED,"Lesson 19 - Clothing")

print(Fore.WHITE, "la camicia = Shirt")
print("la maglietta = T-shirt")
print("la blusa = Blouse")
print("il maglione = Sweater / Jumper")
print("la giacca = Jacket")
print("il cappotto = Coat")
print("il vestito = Dress")
print("la gonna = Skirt")
print("i pantaloni = Pants / Trousers (plural)")
print("i pantaloncini = Shorts")
print("le scarpe = Shoes (plural)")
print("gli stivali = Boots (plural)")
print("le scarpe da ginnastica = Sneakers")
print("i sandali = Sandals (plural)")
print("il cappello = Hat / Cap")
print("la sciarpa = Scarf")
print("i guanti = Gloves (plural)")
print("la cintura = Belt")
print("le calze = Socks (plural)")
print("cappotto invernale = Winter Coat")
print("berretto di lana = Wool Hat")
print("sciarpa = Scarf")
print("guanti = Gloves")
print("doposci = Snow Boots")
print("costume da bagno = Swimsuit")
print("occhiali da sole = Sunglasses")
print("infradito = Flip-flops")
print("pantaloncini = Shorts")
print("canottiera = Tank Top")
print("abito = Suit")
print("cravatta = Tie")
print("blazer = Blazer")
print("tacchi alti = High Heels")
print("abito da sera = Evening Dress")
print("nero = Black")
print("bianco = White")
print("rosso = Red")
print("blu = Blue")
print("verde = Green")
print("cotone = Cotton")
print("lana = Wool")
print("pelle = Leather")
print("seta = Silk")
print("lino = Linen")

print(Fore.RED,"Lesson 20 - Avderbs")

print(Fore.WHITE, "velocemente = quickly")
print("lentamente = slowly")
print("sempre = always")
print("mai = never")
print("spesso = often")
print("qualche volta = sometimes")
print("raramente = rarely")
print("già = already")
print("ancora = still")
print("ancora = yet")
print("presto = soon")
print("ora = now")
print("più tardi = later")
print("oggi = today")
print("domani = tomorrow")
print("ieri = yesterday")
print("chiaramente = clearly")
print("insieme = together")
print("separatamente = apart")
print("per sempre = forever")

print(Fore.RED,"Lesson 21 - Animals")

print(Fore.WHITE, "cane = dog")
print("gatto = cat")
print("cavallo = horse")
print("mucca = cow")
print("pecora = sheep")
print("maiale = pig")
print("capra = goat")
print("pollo = chicken")
print("anatra = duck")
print("uccello = bird")
print("coniglio = rabbit")
print("topo = mouse")
print("leone = lion")
print("tigre = tiger")
print("orso = bear")
print("elefante = elephant")
print("scimmia = monkey")
print("volpe = fox")
print("lupo = wolf")
print("cervo = deer")

print(Fore.BLUE,"Lesson 22 - Numbers 76 - 110")

print(Fore.WHITE)

print(Fore.RED,"Lesson 23 - Place in town")

print(Fore.WHITE, "scuola = school")
print("ospedale = hospital")
print("banca = bank")
print("ristorante = restaurant")
print("biblioteca = library")
print("supermercato = supermarket")
print("cinema = cinema")
print("posta = post office")
print("stazione di polizia = police station")
print("parco = park")
print("museo = museum")
print("teatro = theatre")
print("hotel = hotel")
print("stadio = stadium")
print("chiesa = church")
print("farmacia = pharmacy")
print("panetteria = bakery")
print("macelleria = butcher")
print("mercato = market")
print("parrucchiere = airdresser")

print(Fore.RED,"Lesson 24 - School Supplies")

print(Fore.WHITE, "libro = book")
print("penna = pen")
print("matita = pencil")
print("gomma = eraser")
print("quaderno = notebook")
print("righello = ruler")
print("forbici = scissors")
print("zaino = backpack")
print("cartella = folder")
print("calcolatrice = calculator")
print("pennarello = marker")
print("gesso = chalk")
print("mappa = map")
print("evidenziatore = highlighter")
print("proiettore = projector")
print("portatile = laptop")
print("stampante = printer")
print("chiavetta USB = USB stick")
print("cartella = schoolbag")
print("temperino = sharpener")

print(Fore.RED,"Lesson 25 - Transportation")

print(Fore.WHITE, "macchina = car")
print("autobus = bus")
print("treno = train")
print("bicicletta = bicycle")
print("moto = motorcycle")
print("aereo = airplane")
print("barca = boat")
print("tram = tram")
print("taxi = taxi")
print("metropolitana = subway")
print("traghetto = ferry")
print("yacht = yacht")
print("mongolfiera = hot air balloon")
print("astronave = spaceship")
print("risciò = rickshaw")
print("gondola = gondola")
print("dirigibile = zeppelin")
print("pattini in linea = rollerblades")
print("canoa = canoe")
print("sottomarino = submarine")


print(Fore.RED,"Lesson 26 - Numbers 111 - 150")

print(Fore.WHITE)

print(Fore.RED,"Lesson 27 - Past Simple")

print(Fore.WHITE)

print(Fore.RED,"Lesson 28 - Personality_ Treats")

print(Fore.WHITE)

print(Fore.RED,"Lesson 29 - Present perfect")

print(Fore.WHITE)

print(Fore.RED,"Lesson 30 - Numbers 151 - 190")

print(Fore.WHITE)

print(Fore.RED,"Lesson 31 - Countries")

print(Fore.WHITE)

print(Fore.RED,"Lesson 32 - Ordering")

print(Fore.WHITE)

print(Fore.RED,"Lesson 33 - Shops in town")

print(Fore.WHITE)

print(Fore.RED,"Lesson 34 - Numbers 191 - 230")

print(Fore.WHITE)

print(Fore.RED,"Lesson 35 - Thing in the street")

print(Fore.WHITE)

print(Fore.RED,"Lesson 36 - Instruments")
print(Fore.WHITE)




