import keyboard

import colorama
from colorama import Fore, init
init()
print(Fore.RED,"1'den 10' a Sayılar")
print("jeden = 1, dva = 2, tri = 3, styri = 4, pat = 5, sest = 6, sedem = 7, osem = 8, devat = 9, desat = 10")
print("")

print(Fore.RED, "Lesson 2 - Greeting")
print("")
print(Fore.WHITE,"Ahoj = Hello")
print("Ako sa mate = How are you?")
print("Rad vas spoznavam = Nice to meet you")
print("Uvidime sa zajtra = See you tomorrow")
print("Dobre rano = Good morning")
print("Dobre den = Good afternoon")
print("Dobry vecer = Good evening")
print("Dobru noc = Good night")
print("Ako sa volate ? = What is your name ?")
print("Moje meno je ____ = My name is ___")
print("kde byvas ? = Where do you live?")
print("Odkial ste ? = Where are you from?")
print("Rad vas opat'vidim = Nice to see you")
print("Pekny den = Have a nice day")
print("Uvidime sa neskor = See you later")
print("Dovidenia = Goodbye")
print("Prosim = Please")
print("Dakujem = Thank you")

print(Fore.RED, "Lesson_3 = Regular Verbs,")

print(Fore.WHITE,"Regular verbs are divided into 3 categories")

print(Fore.BLUE, "1. -AŤ/AŤ sa Verbs")

print(Fore.WHITE, "pýtať = to ask")
print("hrať = to play")
print("čítať = to read")
print("počúvať = to listen")
print("ležať = to lie down")
print("vstávať = to get up")
print("otvárať = to open")
print("zatvárať = to close")
print("zavolať	= to call")
print("hrať sa = to play (refl.)")
print("napísať = to write")
print("smiať sa = to laugh")
print("plakať = to cry")
print("kráčať =to walk")
print("počítavať = to calculate")
print("skúšať = to try")
print("napomínať = to admonish")
print("nosievať = to wear")
print("prechádzať = to walk")
print("používať = to use")
print("predpokladať = to assume")
print("vysnívať = to dream")

print(Fore.BLUE, "2. -OVAŤ Verbs")

print(Fore.WHITE, "pracovať = to work")
print("študovať = to study")
print("milovať = to love")
print("tancovať = to dance")
print("maľovať = to paint")
print("zapisovať = to note down")
print("budovať = to build")

print(Fore.BLUE, "3. -IŤ Verbs")

print(Fore.WHITE,"variť = to cook")
print("učiť = to teach")
print("kresliť = to draw")
print("pocítiť = to feel")
print("čistiť = to clean")
print("riešiť = to solve")
print("žiť = to live")
print("veriť = to believe")
print("tvrdiť = to claim")
print("vlastniť = to own")
print("hodnotiť = to evaluate")

print("Lesson 3.1 - Present Tense")           

print("I = Ja")
print("you = Ty")
print("he/she = on/ona")
print("we = my")
print("you = vy")
print("they = oni")

print("Example for robiť = to do\n, milovať = to love\n, čítať = to read\n")

print("1. Example = robiť\n, Ją robím\n, Ty robíš\n, On/Ona robí\n, My robíme\n, Vy robíte\n, Oni robia\n")

print("2. Examle = milovať\n, Ja milujem\n, Ty miluješ\n, On/ona miluje\n, My milujeme\n, Vy milujete\n, Oni milujú\n")

print("3. exapmle = čítať\n, Ja počúvam\n,	Ty počúvaš\n, On/ona počúva\n, My počúvame\n, Vy počúvate\n, Oni počúvajú\n")

print(Fore.BLUE, "Lesson 4 = Adjectives")

print(Fore.WHITE, "Šťastn = Happyý")
print("Smutný = Sad")
print("Nahnevaný = Angry")  
print("Vystrašený = Afraid") 
print("Radosť = Joy")
print("Prekvapený = Surprised")
print("Pokojný = Calm")
print("Znudený = Bored")
print("Ľahký = Easy") 
print("Ťažký = Difficult")
print("Zlý = Bad")
print("Dobrý = Good")
print("Hlučný = Noisy") 
print("Tichý = Quiet")
print("Silný = Strong")        
print("Slabý = Weak")     
print("Tvrdý = Hard")     
print("Mäkký = Soft")
print("Viac = More") 
print("Menej = Less")     
print("Čistý = Clean")
print("Špinavý = Dirty")  
print("Starý = Old")
print("Nový = New")
print("Veľký = Big")  
print("Malý = Small") 
print("Mladý = Young")     
print("Vychudnutý  = Skinny")
print("Tučný = Fat")
print("Pekný = Pretty") 
print("Škaredý = Ugly") 
print("Hrubý = Thick") 
print("Tenký = Thin")  
print("Drsný = Rough")    
print("Hladký = Smooth")

print(Fore.RED, "Lesson 5 - Days and Months")

print(Fore.BLUE,"Lesson 5.1 - Days of the week")
print("")

print(Fore.WHITE,"Los dias de la semana = The days of the week")
print("Den = day")
print("Týždeň = week")
print("Pondelok = Monday")
print("Utorak = Tuesday")
print("Streda = Wednesday")
print("Stvrtok = Thursday")
print("Piiatok = Friday")
print("Sobota = Saturday")
print("Nedela = Sunday")
print("Vikend = Weekend")     

print(Fore.BLUE,"Lesson 5.2 - Months of the year")
print("")

print(Fore.WHITE,"Mesiace Roka = The months of the year")
print("Mesiac = Months")
print("Rok = Year")
print("Januar = January")
print("Februar = February")
print("Marec = March")
print("April = April")
print("Maj = May")
print("Jun = June")
print("Jul = July")
print("August = August")
print("September = September")
print("Oktober = October")
print("November = November")
print("December = December")
print("")

print(Fore.RED,"Lesson 6 - Seasons and Weathers")
print("")

print(Fore.WHITE, "Ročné obdobia = Seasons")
print("Zima = Winter")
print("Leto = Summer")
print("Jar = Spring")
print("Jeseň = Autumn")
print("Obloha = Sky")
print("Mrak = Cloud")
print("Dúha = Rainbow")
print("Studený = Cold (weather)")
print("Horúci = Hot (weather)")
print("Je horúco = It is hot")
print("Je zima = It is cold")
print("Je slnečno = It is sunny")
print("Je oblačno = It is cloudy")
print("Je vlhko = It is humid")
print("Prší = It is raining")
print("Sneží = It is snowing")
print("Fúka = It is windy")
print("Aké je počasie? = How is the weather?")
print("Dobré počasie = Good weather")
print("Zlé počasie = Bad weather")
print("Aká je teplota? = What is the temperature?")
print("Je 24 stupňov = It is 24 degrees")

print(Fore.RED,"Lesson 7 - Colors")
print("")

print(Fore.WHITE,"Clerny = Black")
print("Mordy = Blue")
print("Hnedy = Brown")
print("Zeleny = Green")
print("Oranzovy = Orange")
print("Purpurovy = Purple")
print("Cerveny = Red")
print("Biely = White")
print("Žltý = Yellow")
print("Sedy = Gray")
print("Zlaty = Gold")
print("Strieborny = Silver")
print("Aku to ma farbu = What color is it?")
print("Farbe je  ___ = The color is ___")
print("")

print(Fore.RED,"Lesson 8 - Family and Friends")
print("")

print(Fore.BLUE,"Lesson 8.1 - Family members")
print("")

print(Fore.WHITE, "Matka = Mother")
print("Otec = Father")
print("Brat = Brother")
print("Sestra = Sister")
print("Syn = Son")
print("Dcéra = Daughter")
print("Rodičia = Parents")
print("Deti = Children")
print("Dieťa = Child")
print("Nevlastná matka = Stepmother")
print("Nevlastný otec = Stepfather")
print("Nevlastná sestra = Stepsister")
print("Nevlastný brat = Stepbrother")
print("Zať = Son-in-law")
print("Nevesta = Daughter-in-law")
print("Manželka = Wife")
print("Manžel = Husband")
print("Starí rodičia = Grandparents")
print("Starý otec = Grandfather")
print("Stará mama = Grandmother")
print("Vnuk = Grandson")
print("Vnučka = Granddaughter")
print("Vnúčatá = Grandchildren")
print("Vnúča = Grandchild")
print("Teta = Aunt")
print("Strýko = Uncle")
print("Sesternica = Cousin (female)")
print("Bratranec = Cousin (male)")
print("Synovec = Nephew")
print("Neter = Niece")
print("Svokor = Father-in-law")
print("Svokra = Mother-in-law")
print("Švagor = Brother-in-law")
print("Švagriná = Sister-in-law")
print("Príbuzný = Relative")

print(Fore.BLUE,"Lesson 8.2 - Friends")
print("")

print(Fore.WHITE, "Pani = Miss")
print("Chlapec = Boy")
print("Dievča = Girl")
print("Dieťa = Baby")
print("Žena = Woman")
print("Muž = Man")
print("Kamarát = Friend (male)")
print("Kamarátka = Friend (female)")
print("Priateľ = Boyfriend")
print("Priateľka = Girlfriend")
print("Pán = Gentleman")
print("Dáma = Lady")
print("Sused = Neighbor (male)")
print("Suseda = Neighbor (female)")

print(Fore.BLUE,"Lesson 9 - Numbers from 11 to 30")
print("")

print(Fore.WHITE, "jedenásť = 11")
print("dvanásť = 12")
print("trinásť = 13")
print("štrnásť = 14")
print("pätnásť = 15")
print("šestnásť = 16")
print("sedemnásť = 17")
print("osemnásť = 18")
print("devätnásť = 19")
print("dvadsať = 20")
print("dvadsaťjeden = 21")
print("dvadsaťdva = 22")
print("dvadsaťtri = 23")
print("dvadsaťštyri = 24")
print("dvadsaťpäť = 25")
print("dvadsaťšesť = 26")
print("dvadsaťsedem = 27")
print("dvadsaťosem = 28")
print("dvadsaťdeväť = 29")
print("tridsať = 30")

print(Fore.RED,"Lesson 10 - Prepositions and Useful words")
print("")

print(Fore.BLUE,"Lesson 10.1 - Prepositions")
print("")

print(Fore.WHITE, "Pre = For")
print("Z = From")
print("V = In")
print("Vnútri = Inside")
print("Do = Into")
print("Najbližšie = Near")
print("Z = Of")
print("Von = Out")
print("Vonku = Outside")
print("Na = To")
print("Pod = Under")
print("S = With")
print("Bez = Without")
print("Vyššie = Above")
print("Naprieč = Across")
print("Po = After")
print("Proti = Against")
print("Pozdĺž = Along")
print("Okolo = Around")
print("V/Na = At")
print("Za = Behind")
print("Nižšie = Below")
print("Vedľa = Beside")
print("Medzi = Between")
print("Podľa = By")
print("Počas = During")
print("Okrem = Except")
print("A = And")
print("Pretože = Because")
print("Ale = But")
print("Alebo = Or")
print("Všade = Everywhere")
print("Všetci = Everyone")
print("Všetko = Everything")
print("Málo = Few")
print("Niektorí = Some")
print("Veľa = Many")
      

print(Fore.BLUE,"Lesson 10.2 - Useful Words")
print("")

print(Fore.WHITE, "Otázka = Question")
print("Odpoveď = Answer")
print("Pravda = Truth")
print("Lož = Lie")
print("Nič = Nothing")
print("Niečo = Something")
print("Rovnaký = Same")
print("Odlišný = Different")
print("Ťahať = Pull")
print("Tlačiť = Push")
print("Dlhý = Long")
print("Krátky = Short")
print("Studený = Cold")
print("Horúci = Hot")
print("Svetlý = Light")
print("Tmavý = Dark")
print("Mokrý = Wet")
print("Suchý = Dry")
print("Prázdny = Empty")
print("Plný = Full")
print("Ako? = How?")
print("Čo? = What?")
print("Kedy? = When?")
print("Kde? = Where?")
print("Ktorý? = Which?")
print("Kto? = Who?")
print("Prečo? = Why?")
print("Ako dlho? = How long?")
print("Koľko? = How much?")


print(Fore.RED,"Lesson 11 - Drinks and Meals")

print(Fore.BLUE,"Lesson 11.1 - Drinks")

print(Fore.WHITE, "Káva = Coffee")
print("Čaj = Tea")
print("Nealkoholický nápoj = Soft drink")
print("Voda = Water")
print("Limonáda = Lemonade")
print("Džús = Juice")
print("Pomarančový džús = Orange juice")
print("Poprosím o pohár vody = I would like a glass of water please")
print("S ľadom = With ice") 

print(Fore.BLUE,"Lesson 11.2 - Dairy Products")

print(Fore.WHITE, "Mlieko = Milk")  
print("Zmrzlina = Ice cream")
print("Maslo = Butter")
print("Syr = Cheese")
print("Tvaroh = Cottage cheese")  
print("Šľahačka = Cream")
print("Kyslá smotana = Sour cream")   
print("Jogurt = Yogurt")
print("Vajcia = Eggs")
print("Šľahačka = Whipping cream")  
print("Pekáreň = Bakery")
print("Bageta = Baguette")
print("Šiška = Doughnut")
print("Koláčik = Cookie") 
print("Rožok = Roll")
print("Dezert = Dessert")  
print("Koláč = Cake")
print("Chlieb = Bread")   
print("Koláč = Pie")
print(Fore.BLUE,"Lesson 11.3 - Meats")

print(Fore.WHITE, "Hovädzie = Beef")
print("Teľacie = Veal")
print("Šunka = Ham")
print("Kuracie = Chicken")   
print("Morčacie = Turkey") 
print("Kačica = Duck")
print("Slanina = Bacon")   
print("Bravčové = Pork")  
print("Filet mignon = Filet mignon") 
print("Klobása = Sausage")
print("Jahňacia kotleta = Lamb chop")   
print("Bravčová kotleta = Pork chop")  
print("Mäso = Meat")


print(Fore.BLUE,"Lesson 11.4 - Seafoods")

print(Fore.WHITE, "Ryba = Fish")
print("Mušle = Shellfish")
print("Morský ostriež = Bass")
print("Losos = Salmon")
print("Homár = Lobster")
print("Krab = Crab")
print("Slávka jedlá = Mussel")
print("Ustrica = Oyster")
print("Treska = Cod")
print("Mušle = Clam")
print("Krevety = Shrimp")
print("Tuniak = Tuna")
print("Pstruh = Trout")
print("Morský jazyk = Sole")
print("Žralok = Shark")
print("Kapor = Carp")
print("Tilapia = Tilapia")
print("Úhor = Eel")
print("Sumec = Catfish")
print("Mečúň = Swordfish")


print(Fore.BLUE,"Lesson 11.5 - Herbs and Spices")

print(Fore.WHITE, "Soľ = Salt")
print("Čierne korenie = Pepper")
print("Rasca = Caraway")
print("Cesnak = Garlic")
print("Bazalka = Basil")
print("Koriander = Coriander")
print("Fenikel = Fennel")
print("Majoránka = Marjoram")
print("Oregano = Oregano")
print("Petržlen = Parsley")
print("Rozmarín = Rosemary")
print("Šalvia = Sage")
print("Tymián = Thyme")
print("Muškátový oriešok = Nutmeg")
print("Paprika = Paprika")
print("Kajenské korenie = Cayenne")
print("Zázvor = Ginger")


print(Fore.BLUE,"Lesson 11.6 - Vegetables")

print(Fore.WHITE, "Zeler = Celery")
print("Baklažán = Eggplant")
print("Cuketa = Zucchini")
print("Cibuľa = Onion")
print("Špenát = Spinach")
print("Šalát = Salad")
print("Zelená fazuľka = Green beans")
print("Uhorka = Cucumber")
print("Reďkovka = Radish")
print("Kapusta = Cabbage")
print("Huby = Mushrooms")
print("Šalát = Lettuce")
print("Kukurica = Corn")
print("Zemiaky = Potatoes")
print("Paradajka = Tomato")
print("Mrkva = Carrot")
print("Banán = Plantain")
print("Fazuľa = Beans")
print("Pór = Leek")
print("Lotosový koreň = Lotus root")
print("Bambusové výhonky = Bamboo shoot")
print("Artičok = Artichoke")
print("Špargľa = Asparagus")
print("Ružičkový kel = Brussels sprouts")
print("Brokolica = Broccoli")
print("Hrach = Peas")
print("Karfiol = Cauliflower")
print("Čili paprička = Chili pepper")


print(Fore.BLUE,"Lesson 11.7 - Fruits")

print(Fore.WHITE, "Čerešne = Cherries")
print("Maliny = Raspberries")
print("Čučoriedky = Blueberries")
print("Jahody = Strawberries")
print("Citrón = Lemon")
print("Limetka = Lime")
print("Jablko = Apple")
print("Pomaranč = Orange")
print("Hruška = Pear")
print("Banán = Banana")
print("Hrozno = Grapes")
print("Grapefruit = Grapefruit")
print("Vodný melón = Watermelon")
print("Ananás = Pineapple")
print("Slivka = Plum")
print("Broskyňa = Peach")
print("Mango = Mango")
print("Marhuľa = Apricot")
print("Granátové jablko = Pomegranate")
print("Tomel = Persimmon")
print("Kiwi = Kiwi")
print("Liči = Litchi")
print("Longan = Longan")
print("Balzamová hruška = Balsam pear")
print("Mučenky = Passion fruit")
print("Avokádo = Avocado")
print("Kokos = Coconut")


print(Fore.RED,"Lesson 12 - Irregular Verbs")
print(Fore.WHITE, "byť = to be")
print("mať = to have")
print("ísť = to go")
print("prísť = to come")
print("vidieť = to see")
print("dať = to give")
print("jesť = to eat")
print("piť = to drink")
print("vedieť = to know")
print("môcť = can")
print("chcieť = to want")
print("zostať = to stay")
print("nájsť = to find")
print("bežať = to run")
print("sedieť = to sit")
print("ležať = to lie")
print("stáť = to stand")
print("rozumieť = to understand")
print("povedať = to say")
print("nosiť = to carry")
print("zobrať = to take")
print("čítať = to read")
print("písať = to write")
print("hrať = to play")
print("kúpiť = to buy")
print("stratiť = to lose")
print("žiť = to live")
print("vrátiť = to return")
print("poznať = to know")
print("umrieť = to die")
print("dostať = to get")
print("vstať = to get up")
print("pozerať = to watch")
print("myslieť = to think")
print("chytiť = to catch")
print("povedať = to say")
print("objednať = to order")
print("stráviť = to spend (time)")
print("dokončiť = to finish")
print("rozbiť = to break")
print("vysvetliť = to explain")
print("preložiť = to translate")
print("zavolať = to call")
print("platiť = to pay")
print("počúvať = to listen")
print("baviť = to entertain")
print("zabudnúť = to forget")
print("otvoriť = to open")
print("zatvoriť = to close")
print("snívať = to dream")

print(Fore.RED,"Lesson 13 - Present Simple")

print(Fore.BLUE, "Example for byť = to be, mať = to have, ísť = to go")

print(Fore.WHITE, "ja som - ja mám - ja idem")
print("ty sis - ty máš - ty ideš")
print("on/ona/ono je - on/ona/ono má - on/ona/ono ide")
print("my sme - my máme - my ideme")
print("vy ste - vy máte - vy idete")
print("oni/ony sú - oni/ony majú - oni/ony idú")

print(Fore.RED,"Lesson 14 - Numbers from 31-50")

print(Fore.WHITE, "tridsaťjeden = 31")
print("tridsaťdva = 32")
print("tridsaťtri = 33")
print("tridsaťštyri = 34")
print("tridsaťpäť = 35")
print("tridsaťšesť = 36")
print("tridsaťsedem = 37")
print("tridsaťosem = 38")
print("tridsaťdeväť = 39")
print("štyridsať = 40")
print("štyridsaťjeden = 41")
print("štyridsaťdva = 42")
print("štyridsaťtri = 43")
print("štyridsaťštyri = 44")
print("štyridsaťpäť = 45")
print("štyridsaťšesť = 46")
print("štyridsaťsedem = 47")
print("štyridsaťosem = 48")
print("štyridsaťdeväť = 49")
print("päťdesiat = 50")


print(Fore.RED,"Lesson 15 - Physical Appearance")

print(Fore.WHITE, "vysoký = Tall")
print("nízky = Short (height)é")
print("štíhly = Slim")
print("tučný = Fat")
print("svalnatý = Muscular")
print("blond = Blonde (hair)")
print("hnedovlasý = Brown-haired")
print("čiernovlasý = Black-haired")
print("kučeravé vlasy = Curly Hair")
print("rovné vlasy = Straight Hair")
print("modré oči = Blue Eyes")
print("hnedé oči = Brown Eyes")
print("zelené oči = Green Eyes")
print("krásny = Beautiful")
print("pekný = Handsome")
print("škaredý = Ugly")
print("mladý = Young")
print("starý = Old")
print("brada = Beard")
print("svetlá pokožka = Light-skinned")
print("tmavá pokožka = Dark-skinned")
print("pehy = Freckles")
print("vrásky = Wrinkles")
print("plešatý = Bald")
print("chlpatý = Hairy (body)")
print("rovný nos = Straight Nose")
print("veľký nos = Big Nose")
print("malý nos = Small Nose")
print("tenké pery = Thin Lips")
print("plné pery = Full Lips")
print("široké plecia = Broad Shoulders")
print("úzke plecia = Narrow Shoulders")
print("opálená pokožka = Tanned Skin")
print("bledá pokožka = Pale Skin")
print("vlnité vlasy = Wavy Hair")
print("konský chvost = Ponytail")
print("vrkoče = Braids")
print("brada a fúzy = Beard and Mustache")

print(Fore.RED,"Lesson  16 - Occupations")

print(Fore.WHITE, "lekár = Doctor")
print("učiteľ = Teacher")
print("inžinier = Engineer")
print("právnik = Lawyer")
print("predavač = Salesperson")
print("policajt = Police Officer")
print("hasič = Firefighter")
print("programátor = Programmer")
print("kuchár = Cook/Chef")
print("novinár = Journalist")
print("zdravotná sestra = Nurse")
print("architekt = Architect")
print("účtovník = Accountant")
print("lekárnik =Pharmacist")
print("vodič = Driver")
print("mechanik = Mechanic")
print("vedec = Scientist")
print("zubár = Dentist")
print("hudobník = Musician")
print("herec = Actor")
print("umelec = Artist")
print("pilot = Pilot")
print("farmár = Farmer")
print("fotograf = Photographer")
print("čašník/čašníčka = Waiter/Waitress")

print(Fore.RED,"Lesson 17 - Sports")

print(Fore.WHITE, "futbal = Football / Soccer")
print("basketbal = Basketball")
print("volejbal = Volleyball")
print("tenis = Tennis")
print("plávanie = Swimming")
print("beh / atletika = Running / Athletics")
print("hokej = Ice Hockey")
print("lyžovanie = Skiing")
print("cyklistika = Cycling")
print("box = Boxing")
print("bojové umenia = Martial Arts")
print("golf = Golf")
print("stolný tenis = Table Tennis")
print("zápasenie = Wrestling")
print("hádzaná = Handball")
print("baseball = Baseball")
print("surfovanie = Surfing")
print("korčuľovanie = Skating")
print("jazdectvo = Horse Riding")
print("potápanie = Diving")
print("kriket = Cricket")
print("ragby = Rugby")
print("balet = Ballet")
print("bowling = Bowling")
print("vzpieranie = Weightlifting")
print("windsurfing = Windsurfing")
print("korčuľovanie = Ice Skating")
print("veslovanie = Rowing")
print("lukostreľba = Archery")
print("lezenie = Climbing")

print(Fore.RED,"Lesson 18 - Numbers “51-75")

print(Fore.WHITE, "päťdesiatjeden = 51")
print("päťdesiatdva = 52")
print("päťdesiattri = 53")
print("päťdesiatštyri = 54")
print("päťdesiatpäť = 55")
print("päťdesiatšesť = 56")
print("päťdesiatsedem = 57")
print("päťdesiatosem = 58")
print("päťdesiatdeväť = 59")
print("šesťdesiat = 60")
print("šesťdesiatjeden = 61")
print("šesťdesiatdva = 62")
print("šesťdesiattri = 63")
print("šesťdesiatštyri = 64")
print("šesťdesiatpäť = 65")
print("šesťdesiatšesť = 66")
print("šesťdesiatsedem = 67")
print("šesťdesiatosem = 68")
print("šesťdesiatdeväť = 69")
print("sedemdesiat = 70")
print("sedemdesiatjeden = 71")
print("sedemdesiatdva = 72")
print("sedemdesiattri = 73")
print("sedemdesiatštyri = 74")
print("sedemdesiatpäť = 75")

print(Fore.RED,"Lesson 19 - Clothing")

print(Fore.WHITE, "košeľa = Shirt")
print("tričko = T-shirt")
print("blúzka = Blouse")
print("sveter = Sweater / Jumper")
print("bunda = Jacket")
print("kabát = Coat")
print("šaty = Dress (plural)")
print("sukňa = Skirt")
print("nohavice  = Pants / Trousers (plural)")
print("krátke nohavice = Shorts")
print("topánky = Shoes (plural)")
print("čižmy = Boots (plural)")
print("tenisky = Sneakers (plural)")
print("sandále = Sandals (plural)")
print("čiapka = Hat / Cap")
print("šál = Scarf")
print("rukavice = Gloves (plural)")
print("opasok = Belt")
print("ponožky = Socks (plural)")
print("zimný kabát = Winter Coat")
print("vlnená čiapka = Woolen Hat")
print("snehule = Snow Boots")
print("plavky = Swimsuit")
print("slnečné okuliare = Sunglasses")
print("žabky = Flip-flops")
print("krátke nohavice = Shorts")
print("tielko = Tank Top")
print("oblek = Suit")
print("kravata = Tie")
print("sako = Blazer")
print("topánky na podpätku = High Heels")
print("večerné šaty = Evening Dress")
print("čierny = Black")
print("biely = White")
print("červený = Red")
print("modrý = Blue")
print("zelený = Green")
print("bavlna = Cotton")
print("vlna = Wool")
print("koža = Leather")
print("hodváb = Silk")
print("ľan = Linen")

print(Fore.RED,"Lesson 20 - Avderbs")

print(Fore.WHITE, "rýchlo = quickly")
print("pomaly = slowly")
print("vždy = always")
print("nikdy = never")
print("často = often")
print("niekedy = sometimes")
print("zriedka = rarely")
print("už = already")
print("stále = still")
print("ešte = yet")
print("čoskoro = soon")
print("teraz = now")
print("neskôr = later")
print("dnes = today")
print("zajtra = tomorrow")
print("včera = yesterday")
print("jasne = clearly")
print("spolu = together")
print("oddelené = apart")
print("navždy = forever")

print(Fore.RED,"Lesson 21 - Animals")

print(Fore.WHITE, "pes = dog")
print("mačka = cat")
print("kôň = horse")
print("krava = cow")
print("ovca = sheep")
print("prasa = pig")
print("koza = goat")
print("kura = chicken")
print("kačica = duck")
print("vták = bird")
print("králik = rabbit")
print("myš = mouse")
print("lev = lion")
print("tiger = tiger")
print("medveď = bear")
print("slon = elephant")
print("opica = monkey")
print("líška = fox")
print("vlk = wolf")
print("jeleň = deer")

print(Fore.BLUE, "Lesson 22 - Numbers 76 - 110")

print(Fore.RED, "Lesson 23 - Place in town")

print(Fore.WHITE)

print(Fore.WHITE, "škola = school")
print("nemocnica = hospital")
print("banka = bank")
print("reštaurácia = restaurant")
print("knižnica = library")
print("supermarket = supermarket")
print("kino = cinema")
print("pošta = post office")
print("policajná stanica = police station")
print("park = park")
print("múzeum = museum")
print("divadlo = theatre")
print("hotel = hotel")
print("štadión = stadium")
print("kostol = church")
print("lekáreň = pharmacy")
print("pekáreň = bakery")
print("mäsiarstvo = butcher")
print("trh = market")
print("kaderníctvo = hairdresser")

print(Fore.RED,"Lesson 24 - School Supplies")

print(Fore.WHITE, "kniha = book")
print("pero = pen")
print("ceruzka = pencil")
print("guma = eraser")
print("zošit = notebook")
print("pravítko = ruler")
print("nožnice = scissors")
print("batoh = backpack")
print("zložka = folder")
print("kalkulačka = calculator")
print("fixka = marker")
print("krieda = chalk")
print("mapa = map")
print("zvýrazňovač = highlighter")
print("projektor = projector")
print("notebook = laptop")
print("tlačiareň = printer")
print("USB kľúč = USB stick")
print("školská taška = schoolbag")
print("strúhadlo = sharpener")

print(Fore.RED,"Lesson 25 - Transportation")

print(Fore.WHITE, "auto = car")
print("autobus = bus")
print("vlak = train")
print("bicykel = bicycle")
print("motorka = motorcycle")
print("lietadlo = airplane")
print("loď = boat")
print("električka = tram")
print("taxík = taxi")
print("metro = subway")
print("trajekt = ferry")
print("jachta = yacht")
print("teplovzdušný balón = hot air balloon")
print("kozmická loď = spaceship")
print("rikša = rickshaw")
print("gondola = gondola")
print("zeppelin = zeppelin")
print("kolieskové korčule = rollerblades")
print("kanoe = canoe")
print("ponorka = submarine")

print(Fore.RED,"Lesson 26 - Numbers 111 - 150")

print(Fore.WHITE)

print(Fore.RED,"Lesson 27 - Past Simple")

print(Fore.WHITE)

print(Fore.RED,"Lesson 28 - Personality_ Treats")

print(Fore.WHITE)

print(Fore.RED,"Lesson 29 - Present perfect")

print(Fore.WHITE)

print(Fore.RED,"Lesson 30 - Numbers 151 - 190")

print(Fore.WHITE)

print(Fore.RED,"Lesson 31 - Countries")

print(Fore.WHITE)

print(Fore.RED,"Lesson 32 - Ordering")

print(Fore.WHITE)

print(Fore.RED,"Lesson 33 - Shops in town")

print(Fore.WHITE)

print(Fore.RED,"Lesson 34 - Numbers 191 - 230")

print(Fore.WHITE)

print(Fore.RED,"Lesson 35 - Thing in the street")

print(Fore.WHITE)

print(Fore.RED,"Lesson 36 - Instruments")
print(Fore.WHITE)






