print("Arena of Valor")

print(" 1. Tank Karakterler")
print("Thane,") 
print("Arum") 
print("Mina") 
print("Lumburr") 
print("Maloch") 
print("Grakk")
print("Cresht") 
print("Ata") 
print("Omega") 
print("Taara") 
print("Arum")
print("Toro") 
print("Cresht")

print(" 2. Savaşçılar")
print("Florentino") 
print("Riktor") 
print("Omen") 
print("Maloch")
print("Ormarr") 
print("Florentino")
print("Arthur") 
print("Lu Bu") 
print("Superman")
print("Astrid") 
print("Skud")
print("Errol") 
print("Arduin")