import keyboard

import colorama
from colorama import Fore, init
init()

print("1'den 10' a Sayılar")
print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print("üks =?, kaks =?, kolm =?, neil =?, viis =?, kuus =?, seitse =?, kaheksa =?, üheksa =?, kümme =?")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

mesaj = "Karşılık gelen rakamları giriniz:"

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

üks     = input(mesaj)
kaks    = input(mesaj)
kolm    = input(mesaj)
neil    = input(mesaj)
viis    = input(mesaj)
kuus    = input(mesaj)
seitse  = input(mesaj)
kaheksa = input(mesaj)
üheksa  = input(mesaj)
kümme   = input(mesaj)

print("Devam etmek için spacebar'a basınız.")
keyboard.wait("space")
print("")

print("üks = 1, kaks = 2, kolm = 3, neil = 4, viis = 5, kuus = 6, seitse = 7, kaheksa = 8, üheksa = 9, kümme = 10")
print("")
print("Devam etmek için spacebar'a basınız.")
keyboard.wait("space")
print("")

print("İşlemler")

sayi1 = int(input("Birinci sayiyi giriniz:"))
sayi2 = int(input("İkinci sayiyi giriniz:"))

toplam = sayi1 + sayi2

print(toplam)


print(Fore.RED, "Lesson 2 - Greeting")
print("")

print(Fore.WHITE,"Tere = Hello")
print("Kuidas sul laheb = How are you?")
print("Tore sind naha = Nice to see you")
print("Meeldiv tutvuda = Nice to meet you")
print("Naeme homme = See you tomorrow")
print("Tere hommikikust  = Good morning")
print("Tere paevast = Good afternoon")
print("Tere ohtust = Godd evening")
print("Head ööd = Good night")
print("Mis si nimi on ?  = What is your name ?")
print("Minu nimi on ____ = My name is ___")
print("Kus sa elad ? = Where do you live?")
print("Kuts sa parit oled ? = Where are you from?")
print("Kena paeva = Have a nice day")
print("Maeme hiljem = See you later")
print("Head aega = Goodbye")
print("Palun = Please")
print("Aitah = Thank you")
print("")

print("Lessson 3 - Regular Verbs")
print("")
print("tõmbuma = to withdraw / shrink")
print("ütlema = to say / tell")
print("tegema = to do / make")
print("mõtlema = to think")
print("esitlema = to present")
print("helistama = to call (on phone)")
print("küsima = to ask")
print("tunduma = to seem")
print("jätma = to leave (behind)")
print("alustama = to begin / start")
print("viirastuma = to hallucinate (become a mirage)")
print("aitama = to help")
print("mängitama = to let play / cause to play")
print("jooksma = to run")
print("kolima = to move (house)")
print("uskuma = to believe")
print("kirjutama = to write")
print("poseerima = to pose")
print("põrama = to rumble / thunder")
print("jätkuma = to continue")
print("seadma = to set / place")
print("õppima = to study / learn")
print("vahetama = to exchange / change")
print("talutama = to tolerate / endure")
print("jälgima = to observe / monitor")
print("seisatama = to stand (cause to stand)")
print("rääkima = to speak / talk")
print("veetma = to spend (time)")
print("õpetama = to teach")
print("kaalutlema = to weigh / consider")
print("ilmuma = to appear / be published")
print("ostma = to buy")
print("servima = to serve")
print("läkitama = to send (official)")
print("ehitama = to build")
print("pusima = to fumble / tinker (colloquial)")
print("lõikama = to cut")
print("müüma = to sell")
print("tagastama = to return (give back)")
print("seletama = to explain")
print("arenema = to develop")
print("hoidma = to keep / hold")
print("tootma = to produce / manufacture")
print("tarvitama = to use / consume")
print("kaanetama = to bind / cover (books)")

print("Lesson 3.1 - Present Tense")           

print("I = ma")
print("you = sa")
print("he/she/it = ta")
print("we = me")
print("you = te")
print("they = nad")

print("Example for raakima = to speak")

print("ma raagin")
print("sa raagid")
print("te raagib")
print("me raagime")
print("te raagite")
print("nad raagivad")

print(Fore.BLUE, "Lesson 4 = Adjectives")

print(Fore.WHITE, "Õnnelik = Happy")
print("Kurb = Sad")
print("Vihane = Angry")
print("Kartlik = Afraid")
print("Rõõmus = Joy")
print("Üllatunud = Surprised")
print("Rahulik = Calm")
print("Igav = Bored")
print("Lihtne = Easy")
print("Raske = Difficult")
print("Halb = Bad")
print("Hea = Good")
print("Lärmakas = Noisy")
print("Vaikne = Quiet")
print("Tugev = Strong")
print("Nõrk = Weak")
print("Kõva = Hard")
print("Pehme = Soft")
print("Rohkem = More")
print("Vähem = Less")
print("Puhas = Clean")
print("Must = Dirty")
print("Vana = Old")
print("Uus = New")
print("Suur = Big")
print("Väike = Small")
print("Noor = Young")
print("Kõhn = Skinny")
print("Paks = Fat")
print("Ilus = Pretty")
print("Inetu = Ugly")
print("Paks = Thick")
print("Õhuke = Thin")
print("Kare = Rough")
print("Sile = Smooth")
      
print(Fore.RED, "Lesson 5 - Days and Months")

print(Fore.BLUE,"Lesson 5.1 - Days of the week")
print("")

print(Fore.WHITE, "Nädalapäevad = The days of the week")
print("Päev = Day")
print("Nädal = Week")
print("Esmaspäev = Monday")
print("Teisipäev = Tuesday")
print("Kolmapäev = Wednesday")
print("Neljapäev = Thursday")
print("Reede = Friday")
print("Laupäev = Saturday")
print("Pühapäev = Sunday")
print("Nädalavahetus = Weekend")


print(Fore.BLUE,"Lesson 5.2 - Months of the year")
print("")

print(Fore.WHITE, "The months of the year = Kalendrikuud")
print("Kuu = Month")
print("Aasta = Year")
print("Jaanuar = January")
print("Veebruar = February")
print("Märts = March")
print("Aprill = April")
print("Mai = May")
print("Juuni = June")
print("Juuli = July")
print("August = August")
print("September = September")
print("Oktoober = October")
print("November = November")
print("Detsember = December")

print(Fore.RED,"Lesson 6 - Seasons and Weathers")
print("")

print(Fore.WHITE, "Aastaajad = Seasons")
print("Talv = Winter")
print("Suvi = Summer")
print("Kevad = Spring")
print("Sügis = Autumn")
print("Taevas = Sky")
print("Pilv = Cloud")
print("Vikerkaar = Rainbow")
print("Külm = Cold (weather)")
print("Palav = Hot (weather)")
print("On palav = It is hot")
print("On külm = It is cold")
print("On päikesepaisteline = It is sunny")
print("On pilvine = It is cloudy")
print("On niiske = It is humid")
print("Vihma sajab = It is raining")
print("Lund sajab = It is snowing")
print("On tuuline = It is windy")
print("Mis ilm on? = How is the weather?")
print("Hea ilm = Good weather")
print("Halb ilm = Bad weather")
print("Milline temperatuur väljas on? = What is the temperature?")
print("On 24 kraadi = It is 24 degrees")

print(Fore.RED,"Lesson 7 - Colors")
print("")

print(Fore.WHITE, "Must = Black")
print("Sinine = Blue")
print("Pruun = Brown")
print("Roheline = Green")
print("Oranž = Orange")
print("Lilla = Purple")
print("Punane = Red")
print("Valge = White")
print("Kollane = Yellow")
print("Hall = Gray")
print("Kuldne = Gold")
print("Hõbedane = Silver")
print("Mis värvi see on? = What color is it?")
print("Värv on ___ = The color is ___")

print(Fore.RED, "Lesson 8 - Family and Friends")
print("")

print(Fore.BLUE, "Lesson 8.1 - Family members")
print("")

print(Fore.WHITE, "Ema = Mother")
print("Isa = Father")
print("Vend = Brother")
print("Õde = Sister")
print("Poeg = Son")
print("Tütar = Daughter")
print("Vanemad = Parents")
print("Lapsed = Children")
print("Laps = Child")
print("Kasuema = Stepmother")
print("Kasuisa = Stepfather")
print("Poolõde = Stepsister")
print("Poolvend = Stepbrother")
print("Väimees = Son-in-law")
print("Minia = Daughter-in-law")
print("Naine = Wife")
print("Mees = Husband")
print("Vanavanemad = Grandparents")
print("Vanaisa = Grandfather")
print("Vanaema = Grandmother")
print("Lapselaps = Grandson")
print("Lapselaps = Granddaughter")
print("Lapselapsed = Grandchildren")
print("Lapselaps = Grandchild")
print("Tädi = Aunt")
print("Onu = Uncle")
print("Onutütar, täditütar = Cousin (female)")
print("Onupoeg, tädipoeg = Cousin (male)")
print("Vennapoeg = Nephew")
print("Vennatütar = Niece")
print("Äi = Father-in-law")
print("Ämm = Mother-in-law")
print("Mehevend, naisevend = Brother-in-law")
print("Meheõde, naiseõde = Sister-in-law")
print("Sugulane = Relative")
      

print(Fore.BLUE, "Lesson 8.2 - Friends")
print("")

print(Fore.WHITE, "Prl = Miss")
print("Poiss = Boy")
print("Tüdruk = Girl")
print("Beebi = Baby")
print("Naine = Woman")
print("Mees = Man")
print("Sõber = Friend (male)")
print("Sõbranna = Friend (female)")
print("Poiss-sõber = Boyfriend")
print("Tüdruksõber = Girlfriend")
print("Härrasmees = Gentleman")
print("Daam = Lady")
print("Naaber = Neighbor (male)")
print("Naaber = Neighbor (female)")      



print(Fore.BLUE, "Lesson 9 - Numbers from 11 to 30")
print("")

print(Fore.WHITE, "üksteist = 11")
print("kaksteist = 12")
print("kolmteist = 13")
print("neliteist = 14")
print("viisteist = 15")
print("kuusteist = 16")
print("seitseteist = 17")
print("kaheksateist = 18")
print("üheksateist = 19")
print("kakskümmend = 20")
print("kakskümmend üks = 21")
print("kakskümmend kaks = 22")
print("kakskümmend kolm = 23")
print("kakskümmend neli = 24")
print("kakskümmend viis = 25")
print("kakskümmend kuus = 26")
print("kakskümmend seitse = 27")
print("kakskümmend kaheksa = 28")
print("kakskümmend üheksa = 29")
print("kolmkümmend = 30")
      

print(Fore.RED, "Lesson 10 - Prepositions and Useful words")
print("")

print(Fore.BLUE, "Lesson 10.1 - Prepositions")
print("")

print(Fore.WHITE, "Jaoks = For")
print("Alates = From")
print("Sisse, sees = In")
print("Sees = Inside")
print("Sisse = Into")
print("Lähedal = Near")
print("Millest = Of")
print("Välja = Out")
print("Väljas = Outside")
print("All = Under")
print("Koos = With")
print("Ilma = Without")
print("Ülalpool = Above")
print("Üle = Across")
print("Pärast = After")
print("Vastu = Against")
print("Mööda = Along")
print("Ümber = Around")
print("Juures = At")
print("Taga = Behind")
print("Allpool = Below")
print("Kõrval = Beside")
print("Vahel = Between")
print("Kõrval = By")
print("Ajal = During")
print("Välja arvatud = Except")
print("Ja = And")
print("Sest = Because")
print("Aga = But")
print("Või = Or")
print("Igal pool = Everywhere")
print("Igaüks = Everyone")
print("Kõik = Everything")
print("Vähe = Few")
print("Mõni = Some")
print("Palju = Many")   

print(Fore.BLUE, "Lesson 10.2 - useful Words")
print("")

print(Fore.WHITE, "Küsimus = Question")
print("Vastus = Answer")
print("Tõde = Truth")
print("Vale = Lie")
print("Mitte midagi = Nothing")
print("Midagi = Something")
print("Sama = Same")
print("Erinev = Different")
print("Tõmba = Pull")
print("Lükka = Pus")
print("Pikk = Long")
print("Lühike = Short")
print("Külm = Cold")
print("Kuum = Hot")
print("Hele = Light")
print("Tume = Dark")
print("Märg = Wet")
print("Kuiv = Dry")
print("Tühi = Empty")
print("Täis = Full")
print("Kuidas? = How?")
print("Mida? = What?")
print("Millal? = When?")
print("Kuhu? = Where?")
print("Milline? = Which?")
print("Kes? = Who?")
print("Miks? = Why?")
print("Kui kaua? = How long?")
print("Kui palju? = How much?")

print(Fore.RED,"Lesson 11 - Drinks and Meals")

print(Fore.BLUE, "Lesson 11.1 - Drinks")

print(Fore.WHITE, "Kohv = Coffee")
print("Tee = Tea")
print("Karastusjook = Soft drink")
print("Vesi = Water")
print("Limonaad = Lemonade")
print("Mahl = Juice")
print("Apelsinimahl = Orange juice")
print("Palun mulle klaas vett = I would like a glass of water please")
print("Jääga = With ice")


print(Fore.BLUE, "Lesson 11.2 - Dairy Products")

print(Fore.WHITE, "Piim = Milk")
print("Jäätis = Ice cream")
print("Või = Butter")
print("Juust = Cheese")
print("Kodujuust = Cottage cheese")
print("Koor = Cream")
print("Hapukoor = Sour cream")
print("Jogurt = Yogurt")
print("Munad = Eggs")
print("Vahukoor = Whipping cream")
print("Pagaritooted = Bakery")
print("Pikk sai = Baguette")
print("Sõõrik = Doughnut")
print("Küpsis = Cookie")
print("Kukkel = Roll")
print("Magustoit = Dessert")
print("Kook = Cake")
print("Leib = Bread")
print("Pirukas = Pie")


print(Fore.BLUE, "Lesson 11.3 - Meats")

print(Fore.WHITE, "Veiseliha = Beef")
print("Vasikaliha = Veal")
print("Sink = Ham")
print("Kanaliha = Chicken")
print("Kalkun = Turkey")
print("Part = Duck")
print("Peekon = Bacon")
print("Sealiha = Pork")
print("Sisefilee = Filet mignon")
print("Vorst = Sausage")
print("Tallekarree = Lamb chop")
print("Seakarbonaad = Pork chop")
print("Liha = Meat")


print(Fore.BLUE, "Lesson 11.4 - Seafoods")

print(Fore.WHITE, "Kala = Fish")
print("Koorikloomad = Shellfish")
print("Ahven = Bass")
print("Lõhe = Salmon")
print("Vähk = Lobster")
print("Krabi = Crab")
print("Rannakarp = Mussel")
print("Auster = Oyster")
print("Tursk = Cod")
print("Merikarp = Clam")
print("Krevett = Shrimp")
print("Tuun = Tuna")
print("Forell = Trout")
print("Lest = Sole")
print("Hai = Shark")
print("Karpkala = Carp")
print("Tilapia = Tilapia")
print("Angerjas = Eel")
print("Säga = Catfish")
print("Mõõkkala = Swordfish")


print(Fore.BLUE, "Lesson 11.5 - Herbs and Spices")

print(Fore.WHITE, "Sool = Salt")
print("Pipar = Pepper")
print("Köömen = Caraway")
print("Küüslauk = Garlic")
print("Basiilik = Basil")
print("Koriander = Coriander")
print("Apteegitill = Fennel")
print("Majoraan = Marjoram")
print("Oregano = Oregano")
print("Petersell = Parsley")
print("Rosmariin = Rosemary")
print("Salvei = Sage")
print("Tüümian = Thyme")
print("Muskaatpähkel = Nutmeg")
print("Paprika = Paprika")
print("Cayenne = Cayenne")
print("Ingver = Ginger")


print(Fore.BLUE, "Lesson 11.6 - Vegetables")

print(Fore.WHITE, "Seller = Celery")
print("Baklažaan = Eggplant")
print("Suvikõrvits = Zucchini")
print("Sibul = Onion")
print("Spinat = Spinach")
print("Salat = Salad")
print("Rohelised oad = Green beans")
print("Kurk = Cucumber")
print("Redis = Radish")
print("Kapsas = Cabbage")
print("Seened = Mushrooms")
print("Lehtsalat = Lettuce")
print("Mais = Corn")
print("Kartul = Potatoes")
print("Tomat = Tomato")
print("Porgand = Carrot")
print("Jahubanaanid = Plantain")
print("Oad = Beans")
print("Porrulauk = Leek")
print("Lootosejuur = Lotus root")
print("Bambusevõrsed = Bamboo shoot")
print("Artišokk = Artichoke")
print("Spargel = Asparagus")
print("Rooskapsas = Brussels sprouts")
print("Brokkoli = Broccoli")
print("Herned = Peas")
print("Lillkapsas = Cauliflower")
print("Tšillipipar = Chili pepper")

print(Fore.BLUE, "Lesson 11.7 - Fruits")

print(Fore.WHITE, "Kirsid = Cherries")
print("Vaarikad = Raspberries")
print("Mustikad = Blueberries")
print("Maasikad = Strawberries")
print("Sidrun = Lemon")
print("Laim = Lime")
print("Õun = Apple")
print("Apelsin = Orange")
print("Pirn = Pear")
print("Banaan = Banana")
print("Viinamarjad = Grapes")
print("Greip = Grapefruit")
print("Arbuus = Watermelon")
print("Ananass = Pineapple")
print("Ploom = Plum")
print("Virsik = Peach")
print("Mango = Mango")
print("Aprikoos = Apricot")
print("Granaatõun = Pomegranate")
print("Hurmaa = Persimmon")
print("Kiivi = Kiwi")
print("Litši = Litchi")
print("Longan = Longan")
print("Karella-kibekurk = Balsam pear")
print("Granadill = Passion fruit")
print("Avokaado = Avocado")
print("Kookospähkel = Coconut")


print(Fore.RED, "Lesson 12 - Irregular Verbs")

print(Fore.WHITE, "olema = to be")
print("omama = to have")
print("minema = to go")
print("tulema = to come")
print("tegema = to do/make")
print("panema = to put")
print("võtma = to take")
print("sõitma = to drive")
print("jääma = to stay")
print("nägema = to see")
print("sööma = to eat")
print("jooma = to drink")
print("ütlema = to say")
print("andma = to give")
print("saama = to get/become")
print("tooma = to bring")
print("viima = to carry")
print("leidma = to find")
print("pesema = to wash")
print("lugema = to read")
print("magama = to sleep")
print("sulgema = to close")
print("kandma = to wear/carry")
print("seisma = to stand")
print("istuma = to sit")
print("jooksma = to run")
print("surema = to die")
print("ärkama = to wake up")
print("õppima = to learn")
print("elama = to live")
print("armastama = to love")
print("uskuma = to believe")
print("kuulma = to hear")
print("tundma = to feel/know")
print("sulatama = to melt")
print("tõusma = to rise")
print("kaotama = to lose")
print("võitlema = to fight")
print("otsima = to search")
print("alustama = to start")
print("katma = to cover")
print("laulma = to sing")
print("unustama = to forget")
print("andeks andma = to forgive")
print("looma = to create")
print("võima = can/may")
print("põgenema = to escape")
print("saatma = to send")
print("langema = to fall")
print("otsustama = to decide")
print("avama = to open")
print("mängima = to play")


print(Fore.RED, "Lesson 13 - Present Simple")

print(Fore.BLUE, "Example for olema = to be, omama = to have, minema = to go")

print(Fore.WHITE, "mina olen - minul on - mina lähen")
print("sina oled - sinul on - sina lähed")
print("tema on - temal on - tema läheb")
print("meie oleme - meil on - meie läheme")
print("teie olete-  teil on - teie lähete")
print("nemad on - nendel on - nemad lähevad")

print(Fore.RED,"Lesson 14 - Numbers from 31-50")

print(Fore.WHITE, "kolmkümmend üks = 31")
print("kolmkümmend kaks = 32")
print("kolmkümmend kolm = 33")
print("kolmkümmend neli = 34")
print("kolmkümmend viis = 35")
print("kolmkümmend kuus = 36")
print("kolmkümmend seitse = 37")
print("kolmkümmend kaheksa = 38")
print("kolmkümmend üheksa = 39")
print("nelikümmend = 40")
print("nelikümmend üks = 41")
print("nelikümmend kaks = 42")
print("nelikümmend kolm = 43")
print("nelikümmend neli = 44")
print("nelikümmend viis = 45")
print("nelikümmend kuus = 46")
print("nelikümmend seitse = 47")
print("nelikümmend kaheksa = 48")
print("nelikümmend üheksa = 49")
print("viiskümmend = 50")


print(Fore.RED, "Lesson 15 - Physical Appearance")

print(Fore.WHITE, "pikk = Tall")
print("lühike = Short (height)")
print("sale = Slim")
print("paks = Fat")
print("lihaseline = Muscular")
print("blond = Blonde (hair)")
print("pruunide juustega = Brown-haired")
print("mustade juustega = Black-haired")
print("lokkis juuksed = Curly Hair")
print("sirged juuksed = Straight Hair")
print("sinised silmad = Blue Eyes")
print("pruunid silmad = Brown Eyes")
print("rohelised silmad = Green Eyes")
print("ilus = Beautiful")
print("nägus = Handsome")
print("kole = Ugly")
print("noor = Young")
print("vana = Old")
print("habe = Beard")
print("hele nahk = Light-skinned")
print("tume nahk = Dark-skinned")
print("tedretähnid = Freckles")
print("kort