import keyboard

import colorama
from colorama import Fore, init
init()

print("1'den 10' a Sayılar")
print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print("üks =?, kaks =?, kolm =?, neil =?, viis =?, kuus =?, seitse =?, kaheksa =?, üheksa =?, kümme =?")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

mesaj = "Karşılık gelen rakamları giriniz:"

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

üks     = input(mesaj)
kaks    = input(mesaj)
kolm    = input(mesaj)
neil    = input(mesaj)
viis    = input(mesaj)
kuus    = input(mesaj)
seitse  = input(mesaj)
kaheksa = input(mesaj)
üheksa  = input(mesaj)
kümme   = input(mesaj)

print("Devam etmek için spacebar'a basınız.")
keyboard.wait("space")
print("")

print("üks = 1, kaks = 2, kolm = 3, neil = 4, viis = 5, kuus = 6, seitse = 7, kaheksa = 8, üheksa = 9, kümme = 10")
print("")
print("Devam etmek için spacebar'a basınız.")
keyboard.wait("space")
print("")

print("İşlemler")

sayi1 = int(input("Birinci sayiyi giriniz:"))
sayi2 = int(input("İkinci sayiyi giriniz:"))

toplam = sayi1 + sayi2

print(toplam)


print(Fore.RED, "Lesson 2 - Greeting")
print("")

print(Fore.WHITE,"Tere = Hello")
print("Kuidas sul laheb = How are you?")
print("Tore sind naha = Nice to see you")
print("Meeldiv tutvuda = Nice to meet you")
print("Naeme homme = See you tomorrow")
print("Tere hommikikust  = Good morning")
print("Tere paevast = Good afternoon")
print("Tere ohtust = Godd evening")
print("Head ööd = Good night")
print("Mis si nimi on ?  = What is your name ?")
print("Minu nimi on ____ = My name is ___")
print("Kus sa elad ? = Where do you live?")
print("Kuts sa parit oled ? = Where are you from?")
print("Kena paeva = Have a nice day")
print("Maeme hiljem = See you later")
print("Head aega = Goodbye")
print("Palun = Please")
print("Aitah = Thank you")
print("")

print("Lessson 3 - Regular Verbs")
print("")
print("tõmbuma = to withdraw / shrink")
print("ütlema = to say / tell")
print("tegema = to do / make")
print("mõtlema = to think")
print("esitlema = to present")
print("helistama = to call (on phone)")
print("küsima = to ask")
print("tunduma = to seem")
print("jätma = to leave (behind)")
print("alustama = to begin / start")
print("viirastuma = to hallucinate (become a mirage)")
print("aitama = to help")
print("mängitama = to let play / cause to play")
print("jooksma = to run")
print("kolima = to move (house)")
print("uskuma = to believe")
print("kirjutama = to write")
print("poseerima = to pose")
print("põrama = to rumble / thunder")
print("jätkuma = to continue")
print("seadma = to set / place")
print("õppima = to study / learn")
print("vahetama = to exchange / change")
print("talutama = to tolerate / endure")
print("jälgima = to observe / monitor")
print("seisatama = to stand (cause to stand)")
print("rääkima = to speak / talk")
print("veetma = to spend (time)")
print("õpetama = to teach")
print("kaalutlema = to weigh / consider")
print("ilmuma = to appear / be published")
print("ostma = to buy")
print("servima = to serve")
print("läkitama = to send (official)")
print("ehitama = to build")
print("pusima = to fumble / tinker (colloquial)")
print("lõikama = to cut")
print("müüma = to sell")
print("tagastama = to return (give back)")
print("seletama = to explain")
print("arenema = to develop")
print("hoidma = to keep / hold")
print("tootma = to produce / manufacture")
print("tarvitama = to use / consume")
print("kaanetama = to bind / cover (books)")

print("Lesson 3.1 - Present Tense")           

print("I = ma")
print("you = sa")
print("he/she/it = ta")
print("we = me")
print("you = te")
print("they = nad")

print("Example for raakima = to speak")

print("ma raagin")
print("sa raagid")
print("te raagib")
print("me raagime")
print("te raagite")
print("nad raagivad")

print(Fore.BLUE, "Lesson 4 = Adjectives")

print(Fore.WHITE, "Õnnelik = Happy")
print("Kurb = Sad")
print("Vihane = Angry")
print("Kartlik = Afraid")
print("Rõõmus = Joy")
print("Üllatunud = Surprised")
print("Rahulik = Calm")
print("Igav = Bored")
print("Lihtne = Easy")
print("Raske = Difficult")
print("Halb = Bad")
print("Hea = Good")
print("Lärmakas = Noisy")
print("Vaikne = Quiet")
print("Tugev = Strong")
print("Nõrk = Weak")
print("Kõva = Hard")
print("Pehme = Soft")
print("Rohkem = More")
print("Vähem = Less")
print("Puhas = Clean")
print("Must = Dirty")
print("Vana = Old")
print("Uus = New")
print("Suur = Big")
print("Väike = Small")
print("Noor = Young")
print("Kõhn = Skinny")
print("Paks = Fat")
print("Ilus = Pretty")
print("Inetu = Ugly")
print("Paks = Thick")
print("Õhuke = Thin")
print("Kare = Rough")
print("Sile = Smooth")
      
print(Fore.RED, "Lesson 5 - Days and Months")

print(Fore.BLUE,"Lesson 5.1 - Days of the week")
print("")

print(Fore.WHITE, "Nädalapäevad = The days of the week")
print("Päev = Day")
print("Nädal = Week")
print("Esmaspäev = Monday")
print("Teisipäev = Tuesday")
print("Kolmapäev = Wednesday")
print("Neljapäev = Thursday")
print("Reede = Friday")
print("Laupäev = Saturday")
print("Pühapäev = Sunday")
print("Nädalavahetus = Weekend")


print(Fore.BLUE,"Lesson 5.2 - Months of the year")
print("")

print(Fore.WHITE, "The months of the year = Kalendrikuud")
print("Kuu = Month")
print("Aasta = Year")
print("Jaanuar = January")
print("Veebruar = February")
print("Märts = March")
print("Aprill = April")
print("Mai = May")
print("Juuni = June")
print("Juuli = July")
print("August = August")
print("September = September")
print("Oktoober = October")
print("November = November")
print("Detsember = December")

print(Fore.RED,"Lesson 6 - Seasons and Weathers")
print("")

print(Fore.WHITE, "Aastaajad = Seasons")
print("Talv = Winter")
print("Suvi = Summer")
print("Kevad = Spring")
print("Sügis = Autumn")
print("Taevas = Sky")
print("Pilv = Cloud")
print("Vikerkaar = Rainbow")
print("Külm = Cold (weather)")
print("Palav = Hot (weather)")
print("On palav = It is hot")
print("On külm = It is cold")
print("On päikesepaisteline = It is sunny")
print("On pilvine = It is cloudy")
print("On niiske = It is humid")
print("Vihma sajab = It is raining")
print("Lund sajab = It is snowing")
print("On tuuline = It is windy")
print("Mis ilm on? = How is the weather?")
print("Hea ilm = Good weather")
print("Halb ilm = Bad weather")
print("Milline temperatuur väljas on? = What is the temperature?")
print("On 24 kraadi = It is 24 degrees")

print(Fore.RED,"Lesson 7 - Colors")
print("")

print(Fore.WHITE, "Must = Black")
print("Sinine = Blue")
print("Pruun = Brown")
print("Roheline = Green")
print("Oranž = Orange")
print("Lilla = Purple")
print("Punane = Red")
print("Valge = White")
print("Kollane = Yellow")
print("Hall = Gray")
print("Kuldne = Gold")
print("Hõbedane = Silver")
print("Mis värvi see on? = What color is it?")
print("Värv on ___ = The color is ___")

print(Fore.RED,"Lesson 8 - Family and Friends")
print("")

print(Fore.BLUE,"Lesson 8.1 - Family members")
print("")

print(Fore.WHITE, "Ema = Mother")
print("Isa = Father")
print("Vend = Brother")
print("Õde = Sister")
print("Poeg = Son")
print("Tütar = Daughter")
print("Vanemad = Parents")
print("Lapsed = Children")
print("Laps = Child")
print("Kasuema = Stepmother")
print("Kasuisa = Stepfather")
print("Poolõde = Stepsister")
print("Poolvend = Stepbrother")
print("Väimees = Son-in-law")
print("Minia = Daughter-in-law")
print("Naine = Wife")
print("Mees = Husband")
print("Vanavanemad = Grandparents")
print("Vanaisa = Grandfather")
print("Vanaema = Grandmother")
print("Lapselaps = Grandson")
print("Lapselaps = Granddaughter")
print("Lapselapsed = Grandchildren")
print("Lapselaps = Grandchild")
print("Tädi = Aunt")
print("Onu = Uncle")
print("Onutütar, täditütar = Cousin (female)")
print("Onupoeg, tädipoeg = Cousin (male)")
print("Vennapoeg = Nephew")
print("Vennatütar = Niece")
print("Äi = Father-in-law")
print("Ämm = Mother-in-law")
print("Mehevend, naisevend = Brother-in-law")
print("Meheõde, naiseõde = Sister-in-law")
print("Sugulane = Relative")
      

print(Fore.BLUE,"Lesson 8.2 - Friends")
print("")

print(Fore.WHITE,"Prl = Miss")
print("Poiss = Boy")
print("Tüdruk = Girl")
print("Beebi = Baby")
print("Naine = Woman")
print("Mees = Man")
print("Sõber = Friend (male)")
print("Sõbranna = Friend (female)")
print("Poiss-sõber = Boyfriend")
print("Tüdruksõber = Girlfriend")
print("Härrasmees = Gentleman")
print("Daam = Lady")
print("Naaber = Neighbor (male)")
print("Naaber = Neighbor (female)")      



print(Fore.BLUE,"Lesson 9 - Numbers from 11 to 30")
print("")

print(Fore.WHITE, "üksteist = 11")
print("kaksteist = 12")
print("kolmteist = 13")
print("neliteist = 14")
print("viisteist = 15")
print("kuusteist = 16")
print("seitseteist = 17")
print("kaheksateist = 18")
print("üheksateist = 19")
print("kakskümmend = 20")
print("kakskümmend üks = 21")
print("kakskümmend kaks = 22")
print("kakskümmend kolm = 23")
print("kakskümmend neli = 24")
print("kakskümmend viis = 25")
print("kakskümmend kuus = 26")
print("kakskümmend seitse = 27")
print("kakskümmend kaheksa = 28")
print("kakskümmend üheksa = 29")
print("kolmkümmend = 30")
      

print(Fore.RED,"Lesson 10 - Prepositions and Useful words")
print("")

print(Fore.BLUE,"Lesson 10.1 - Prepositions")
print("")

print(Fore.WHITE, "Jaoks = For")
print("Alates = From")
print("Sisse, sees = In")
print("Sees = Inside")
print("Sisse = Into")
print("Lähedal = Near")
print("Millest = Of")
print("Välja = Out")
print("Väljas = Outside")
print("All = Under")
print("Koos = With")
print("Ilma = Without")
print("Ülalpool = Above")
print("Üle = Across")
print("Pärast = After")
print("Vastu = Against")
print("Mööda = Along")
print("Ümber = Around")
print("Juures = At")
print("Taga = Behind")
print("Allpool = Below")
print("Kõrval = Beside")
print("Vahel = Between")
print("Kõrval = By")
print("Ajal = During")
print("Välja arvatud = Except")
print("Ja = And")
print("Sest = Because")
print("Aga = But")
print("Või = Or")
print("Igal pool = Everywhere")
print("Igaüks = Everyone")
print("Kõik = Everything")
print("Vähe = Few")
print("Mõni = Some")
print("Palju = Many")   