import keyboard

import colorama
from colorama import Fore, init
init()

print("1'den 10' a Sayılar")
print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print("üks =?, kaks =?, kolm =?, neil =?, viis =?, kuus =?, seitse =?, kaheksa =?, üheksa =?, kümme =?")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

mesaj = "Karşılık gelen rakamları giriniz:"

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

üks     = input(mesaj)
kaks    = input(mesaj)
kolm    = input(mesaj)
neil    = input(mesaj)
viis    = input(mesaj)
kuus    = input(mesaj)
seitse  = input(mesaj)
kaheksa = input(mesaj)
üheksa  = input(mesaj)
kümme   = input(mesaj)

print("Devam etmek için spacebar'a basınız.")
keyboard.wait("space")
print("")

print("üks = 1, kaks = 2, kolm = 3, neil = 4, viis = 5, kuus = 6, seitse = 7, kaheksa = 8, üheksa = 9, kümme = 10")
print("")
print("Devam etmek için spacebar'a basınız.")
keyboard.wait("space")
print("")

print("İşlemler")

sayi1 = int(input("Birinci sayiyi giriniz:"))
sayi2 = int(input("İkinci sayiyi giriniz:"))

toplam = sayi1 + sayi2

print(toplam)


print(Fore.RED, "Lesson 2 - Greeting")
print("")

print(Fore.WHITE,"Tere = Hello")
print("Kuidas sul laheb = How are you?")
print("Tore sind naha = Nice to see you")
print("Meeldiv tutvuda = Nice to meet you")
print("Naeme homme = See you tomorrow")
print("Tere hommikikust  = Good morning")
print("Tere paevast = Good afternoon")
print("Tere ohtust = Godd evening")
print("Head ööd = Good night")
print("Mis si nimi on ?  = What is your name ?")
print("Minu nimi on ____ = My name is ___")
print("Kus sa elad ? = Where do you live?")
print("Kuts sa parit oled ? = Where are you from?")
print("Kena paeva = Have a nice day")
print("Maeme hiljem = See you later")
print("Head aega = Goodbye")
print("Palun = Please")
print("Aitah = Thank you")
print("")

print("Lessson 3 - Regular Verbs")
print("")
print("tõmbuma = to withdraw / shrink")
print("ütlema = to say / tell")
print("tegema = to do / make")
print("mõtlema = to think")
print("esitlema = to present")
print("helistama = to call (on phone)")
print("küsima = to ask")
print("tunduma = to seem")
print("jätma = to leave (behind)")
print("alustama = to begin / start")
print("viirastuma = to hallucinate (become a mirage)")
print("aitama = to help")
print("mängitama = to let play / cause to play")
print("jooksma = to run")
print("kolima = to move (house)")
print("uskuma = to believe")
print("kirjutama = to write")
print("poseerima = to pose")
print("põrama = to rumble / thunder")
print("jätkuma = to continue")
print("seadma = to set / place")
print("õppima = to study / learn")
print("vahetama = to exchange / change")
print("talutama = to tolerate / endure")
print("jälgima = to observe / monitor")
print("seisatama = to stand (cause to stand)")
print("rääkima = to speak / talk")
print("veetma = to spend (time)")
print("õpetama = to teach")
print("kaalutlema = to weigh / consider")
print("ilmuma = to appear / be published")
print("ostma = to buy")
print("servima = to serve")
print("läkitama = to send (official)")
print("ehitama = to build")
print("pusima = to fumble / tinker (colloquial)")
print("lõikama = to cut")
print("müüma = to sell")
print("tagastama = to return (give back)")
print("seletama = to explain")
print("arenema = to develop")
print("hoidma = to keep / hold")
print("tootma = to produce / manufacture")
print("tarvitama = to use / consume")
print("kaanetama = to bind / cover (books)")

print("Lesson 3.1 - Present Tense")           

print("I = ma")
print("you = sa")
print("he/she/it = ta")
print("we = me")
print("you = te")
print("they = nad")

print("Example for raakima = to speak")

print("ma raagin")
print("sa raagid")
print("te raagib")
print("me raagime")
print("te raagite")
print("nad raagivad")

print(Fore.BLUE, "Lesson 4 = Adjectives")

print(Fore.WHITE, "Õnnelik = Happy")
print("Kurb = Sad")
print("Vihane = Angry")
print("Kartlik = Afraid")
print("Rõõmus = Joy")
print("Üllatunud = Surprised")
print("Rahulik = Calm")
print("Igav = Bored")
print("Lihtne = Easy")
print("Raske = Difficult")
print("Halb = Bad")
print("Hea = Good")
print("Lärmakas = Noisy")
print("Vaikne = Quiet")
print("Tugev = Strong")
print("Nõrk = Weak")
print("Kõva = Hard")
print("Pehme = Soft")
print("Rohkem = More")
print("Vähem = Less")
print("Puhas = Clean")
print("Must = Dirty")
print("Vana = Old")
print("Uus = New")
print("Suur = Big")
print("Väike = Small")
print("Noor = Young")
print("Kõhn = Skinny")
print("Paks = Fat")
print("Ilus = Pretty")
print("Inetu = Ugly")
print("Paks = Thick")
print("Õhuke = Thin")
print("Kare = Rough")
print("Sile = Smooth")
      
print(Fore.RED, "Lesson 5 - Days and Months")

print(Fore.BLUE,"Lesson 5.1 - Days of the week")
print("")

print(Fore.WHITE, "Nädalapäevad = The days of the week")
print("Päev = Day")
print("Nädal = Week")
print("Esmaspäev = Monday")
print("Teisipäev = Tuesday")
print("Kolmapäev = Wednesday")
print("Neljapäev = Thursday")
print("Reede = Friday")
print("Laupäev = Saturday")
print("Pühapäev = Sunday")
print("Nädalavahetus = Weekend")


print(Fore.BLUE,"Lesson 5.2 - Months of the year")
print("")

print(Fore.WHITE, "The months of the year = Kalendrikuud")
print("Kuu = Month")
print("Aasta = Year")
print("Jaanuar = January")
print("Veebruar = February")
print("Märts = March")
print("Aprill = April")
print("Mai = May")
print("Juuni = June")
print("Juuli = July")
print("August = August")
print("September = September")
print("Oktoober = October")
print("November = November")
print("Detsember = December")

print(Fore.RED,"Lesson 6 - Colors")
print("")

print(Fore.WHITE, "Must = Black")
print("Sinine = Blue")
print("Pruun = Brown")
print("Roheline = Green")
print("Oranž = Orange")
print("Lilla = Purple")
print("Punane = Red")
print("Valge = White")
print("Kollane = Yellow")
print("Hall = Gray")
print("Kuldne = Gold")
print("Hõbedane = Silver")
print("Mis värvi see on? = What color is it?")
print("Värv on ___ = The color is ___")