import keyboard

import colorama
from colorama import Fore, init
init()
print(Fore.RED,"1'den 10' a Sayılar")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print(Fore.WHITE,"une =?, deux =?, trois =?, quatre =?, cinq =?, six =?, sept =?, huit =?, neuf =?, dix =?")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

mesaj = "Karşılık gelen rakamları giriniz:"
print("")

une    = input(mesaj)
deux   = input(mesaj)
trois  = input(mesaj)
quatre = input(mesaj)
cincq  = input(mesaj)
six    = input(mesaj)
sept   = input(mesaj)
huit   = input(mesaj)
neuf   = input(mesaj)
dix    = input(mesaj)
print("")

print("Devam etmek için spacebar'a basınız.")
keyboard.wait("space")
print("")

print("une = 1, deux = 2, trois = 3, quatre = 4, cincq = 5, six = 6, sept = 7, huit = 8, neuf = 9, dix = 10")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print("İşlemler")
print("")

sayi1 = int(input("Birinci sayiyi giriniz:"))
sayi2 = int(input("İkinci sayiyi giriniz:"))

toplam = sayi1 + sayi2

print(toplam)

print(Fore.RED, "Lesson 2 - Greeting")
print("")
print(Fore.WHITE,"Salut = Hello")
print("Comment allez-vous = How are you?")
print("Content de vous voir = Nice to see you")
print("Enchante = Nice to meet you")
print("A demani = See you tomorrow")
print("Bonjoir  = Good morning")
print("Bonne apres-midi = Good afternoon")
print("Bonsoir = Godd evening")
print("Bonne nuit = Good night")
print("Cuel est ton nom  = What is your name ?")
print("Mon nom est____ = My name is ___")
print("Ou habites-tu ? = Where do you live?")
print("D'ou venez-vous ? = Where are you from?")
print("Bonne journee = Have a nice day")
print("A la prochaine = See you later")
print("Au revoir = Goodbye")
print("S'il vous plait = Please")
print("Merci = Thank you")

print(Fore.RED, "Lesson_3 = Regular Verbs,")

print(Fore.WHITE,"Regular verbs are divided into 3 categories")

print(Fore.BLUE, "1. -Er Verbs")

print(Fore.WHITE, "abaisser	= to lower, to push/pull down")
print("abîmer = to ruin")
print("aimer = to like, to love")
print("arriver = to arrive, to happen")
print("bouger** = to move")
print("brosser = to brush")
print("changer** = to change")
print("chanter = to sing")
print("chercher = to look for")
print("commencer** = to begin, start")
print("corriger**	= to correct")
print("danser = to dance")
print("demander = to ask for")
print("détester = to hate")
print("donner = to give")
print("écouter = to listen to")
print("effacer** = to erase")
print("étudier	= to study")
print("féliciter = to congratulate")
print("fêter  = to celebrate")
print("gagner = to win, to earn")
print("glisser = to slide")
print("habiter = to live")
print("jouer = to play")
print("manger** = to eat")
print("manquer = to miss")
print("marcher	= to walk, to function")
print("monter = to climb")
print("nager**	= to swim")
print("parler = to talk, to speak")
print("partager** = to share")
print("penser = to think")
print("regarder = to watch, to look at")
print("skier = to ski")
print("travailler = to work")
print("trouver	= to find")
print("visiter	= to visit (a place)")
print("voyager** = to travel")