import keyboard

import colorama
from colorama import Fore, init
init()
print(Fore.RED,"1'den 10' a Sayılar")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print(Fore.WHITE,"une =?, deux =?, trois =?, quatre =?, cinq =?, six =?, sept =?, huit =?, neuf =?, dix =?")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

mesaj = "Karşılık gelen rakamları giriniz:"
print("")

une    = input(mesaj)
deux   = input(mesaj)
trois  = input(mesaj)
quatre = input(mesaj)
cincq  = input(mesaj)
six    = input(mesaj)
sept   = input(mesaj)
huit   = input(mesaj)
neuf   = input(mesaj)
dix    = input(mesaj)
print("")

print("Devam etmek için spacebar'a basınız.")
keyboard.wait("space")
print("")

print("une = 1, deux = 2, trois = 3, quatre = 4, cincq = 5, six = 6, sept = 7, huit = 8, neuf = 9, dix = 10")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print("İşlemler")
print("")

sayi1 = int(input("Birinci sayiyi giriniz:"))
sayi2 = int(input("İkinci sayiyi giriniz:"))

toplam = sayi1 + sayi2

print(toplam)

print(Fore.RED, "Lesson 2 - Greeting")
print("")
print(Fore.WHITE,"Salut = Hello")
print("Comment allez-vous = How are you?")
print("Content de vous voir = Nice to see you")
print("Enchante = Nice to meet you")
print("A demani = See you tomorrow")
print("Bonjoir  = Good morning")
print("Bonne apres-midi = Good afternoon")
print("Bonsoir = Godd evening")
print("Bonne nuit = Good night")
print("Cuel est ton nom  = What is your name ?")
print("Mon nom est____ = My name is ___")
print("Ou habites-tu ? = Where do you live?")
print("D'ou venez-vous ? = Where are you from?")
print("Bonne journee = Have a nice day")
print("A la prochaine = See you later")
print("Au revoir = Goodbye")
print("S'il vous plait = Please")
print("Merci = Thank you")

print(Fore.RED, "Lesson_3 = Regular Verbs,")

print(Fore.WHITE,"Regular verbs are divided into 3 categories")

print(Fore.BLUE, "1. -Er Verbs")

print(Fore.WHITE, "abaisser	= to lower, to push/pull down")
print("abîmer = to ruin")
print("aimer = to like, to love")
print("arriver = to arrive, to happen")
print("bouger** = to move")
print("brosser = to brush")
print("changer** = to change")
print("chanter = to sing")
print("chercher = to look for")
print("commencer** = to begin, start")
print("corriger**	= to correct")
print("danser = to dance")
print("demander = to ask for")
print("détester = to hate")
print("donner = to give")
print("écouter = to listen to")
print("effacer** = to erase")
print("étudier	= to study")
print("féliciter = to congratulate")
print("fêter  = to celebrate")
print("gagner = to win, to earn")
print("glisser = to slide")
print("habiter = to live")
print("jouer = to play")
print("manger** = to eat")
print("manquer = to miss")
print("marcher	= to walk, to function")
print("monter = to climb")
print("nager**	= to swim")
print("parler = to talk, to speak")
print("partager** = to share")
print("penser = to think")
print("regarder = to watch, to look at")
print("skier = to ski")
print("travailler = to work")
print("trouver	= to find")
print("visiter	= to visit (a place)")
print("voyager** = to travel")

print(Fore.BLUE, "2. -Ir Verbs")

print(Fore.WHITE, "abolir = to abolish")
print("accomplir = to accomplish")
print("agir = to act")
print("agrandir = to enlarge, to increase")
print("avertir = to warn")
print("bâtir = to build")
print("bénir = to bless")
print("blanchir = to whiten, to lighten")
print("choisir = to choose")
print("convertir = to convert")
print("définir = to define")
print("établir = to establish")
print("étourdir = to stun, to deafen, to make dizzy")
print("finir = to finish")
print("franchir = to clear (an obstacle)")
print("grossir = to gain weight, to get fat")
print("guérir = to cure, to heal, to recover")
print("investir = to invest")
print("maigrir = to lose weight, to get thin")
print("nourrir = to feed, to nourish")
print("obéir = to obey")
print("punir = to punish")
print("réfléchir = to reflect, to think")
print("remplir = to fill")
print("réussir = to succeed")
print("rougir = to blush, to turn red")
print("saisir = to seize")
print("vieillir = to age, grow old")

print(Fore.BLUE, "3. -Re Verbs")

print(Fore.WHITE, "attendre = to wait for")
print("confondre = to confuse")
print("correspondre = to correspond")
print("défendre = to defend")
print("dépendre = to depend")
print("descendre = to descend")
print("entendre = to hear, to understand")
print("étendre = to stretch")
print("fondre = to melt")
print("mordre = to bite")
print("pendre = to hang, suspend")
print("perdre = to lose")
print("prétendre = to claim")
print("rendre = to give back, to return")
print("répandre = to spread, to scatter")
print("répondre = to answer")
print("suspendre = to suspend")
print("tordre = to twist")
print("vendre = to sell")

print(Fore.RED,"Lesson 3.1 - Present Tense")           

print(Fore.WHITE,"I = je")
print("you = tu")
print("he/she/it = il/elle/on")
print("we = nouos")
print("you = vouos")
print("they = ils/elles")

print("Example for parler = to speak, finir = to finish and vendre = to sell")

print("je parle - je finis - je vends")
print("tu parles - tu finis - tu vends")
print("il parle - il finit - il vend")
print("nous parlons - nous finissons, nous vendons")
print("vous parlez - vous finissez - vous vendez")
print("elles parlent - elles finissent - elles vendent")

print(Fore.RED, "Lesson 4 - Adjectives")
print("")

print(Fore.WHITE, "Heureux = Happy")
print("Triste = Sad")
print("Énervé = Angry")
print("Peur = Afraid")
print("Joie = Joy")
print("Surpris = Surprised")
print("Calme = Calm")
print("Ennuyé = Bored")
print("Facile = Easy")
print("Difficile = Difficult")
print("Mauvais = Bad")
print("Bon = Good")
print("Bruyant = Noisy")
print("Silencieux = Quiet")
print("Fort = Strong")
print("Faible = Weak")
print("Dur = Hard")
print("Mou = Soft")
print("Plus = More")
print("Moins = Less")
print("Propre = Clean")
print("Sale = Dirty")
print("Vieux = Old")
print("Nouveau = New")
print("Grand = Big")
print("Petit = Small")
print("Jeune = Young")
print("Maigre = Skinny")
print("Gros = Fat")
print("Joli = Pretty")
print("Laid = Ugly")
print("Épais = Thick")
print("Mince = Thin")
print("Rêche = Rough")
print("Lisse = Smooth")

print(Fore.RED, "Lesson 5 - Days and Months")
print("")

print(Fore.BLUE, "Lesson 5.1 - Days of the week")
print("")

print(Fore.WHITE, "Les jours de la semaine = The days of the week") 
print("Jour = Day")
print("Semaine = Week")
print("Lundi = Monday")
print("Mardi = Tuesday")
print("Mercredi = Wednesday")
print("Jeudi = Thursday")
print("Vendredi = Friday")
print("Samedi = Saturday")
print("Dimanche = Sunday")
print("(la) Fin de semaine = Weekend")

print(Fore.RED, "Lesson 5.2 - Months of the year")
print("")

print(Fore.WHITE, "Les mois de l’année = The months of the year")
print("Mois = Month")
print("Année = Year")
print("Janvier = January")
print("Février = February")
print("Mars = March")
print("Avril = April")
print("Mai = May")
print("Juin = June")
print("Juillet = July")
print("Août = August")
print("Septembre = September")
print("Octobre = October")
print("Novembre = November")
print("Décembre = December")

print(Fore.RED, "Lesson 6 - Colors")
print("")

print(Fore.WHITE, "Noir = Black")
print("Bleu = Blue")
print("Marron = Brown")
print("Vert = Green")
print("Orange = Orange")
print("Violet = Purple")
print("Rouge = Red")
print("Blanc = White")
print("Jaune = Yellow")
print("Gris = Gray")
print("Doré = Gold")
print("Argenté = Silver")
print("Quelle couleur est-ce? = What color is it?")
print("C’est ___ = The color is ___")