import keyboard

import colorama
from colorama import Fore, init
init()
print(Fore.RED,"1'den 10' a Sayılar")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print(Fore.WHITE,"une =?, deux =?, trois =?, quatre =?, cinq =?, six =?, sept =?, huit =?, neuf =?, dix =?")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

mesaj = "Karşılık gelen rakamları giriniz:"
print("")

une    = input(mesaj)
deux   = input(mesaj)
trois  = input(mesaj)
quatre = input(mesaj)
cincq  = input(mesaj)
six    = input(mesaj)
sept   = input(mesaj)
huit   = input(mesaj)
neuf   = input(mesaj)
dix    = input(mesaj)
print("")

print("Devam etmek için spacebar'a basınız.")
keyboard.wait("space")
print("")

print("une = 1, deux = 2, trois = 3, quatre = 4, cincq = 5, six = 6, sept = 7, huit = 8, neuf = 9, dix = 10")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print("İşlemler")
print("")

sayi1 = int(input("Birinci sayiyi giriniz:"))
sayi2 = int(input("İkinci sayiyi giriniz:"))

toplam = sayi1 + sayi2

print(toplam)

print(Fore.RED, "Lesson 2 - Greeting")
print("")
print(Fore.WHITE,"Salut = Hello")
print("Comment allez-vous = How are you?")
print("Content de vous voir = Nice to see you")
print("Enchante = Nice to meet you")
print("A demani = See you tomorrow")
print("Bonjoir  = Good morning")
print("Bonne apres-midi = Good afternoon")
print("Bonsoir = Godd evening")
print("Bonne nuit = Good night")
print("Cuel est ton nom  = What is your name ?")
print("Mon nom est____ = My name is ___")
print("Ou habites-tu ? = Where do you live?")
print("D'ou venez-vous ? = Where are you from?")
print("Bonne journee = Have a nice day")
print("A la prochaine = See you later")
print("Au revoir = Goodbye")
print("S'il vous plait = Please")
print("Merci = Thank you")

print(Fore.RED, "Lesson_3 = Regular Verbs,")

print(Fore.WHITE,"Regular verbs are divided into 3 categories")

print(Fore.BLUE, "1. -Er Verbs")

print(Fore.WHITE, "abaisser	= to lower, to push/pull down")
print("abîmer = to ruin")
print("aimer = to like, to love")
print("arriver = to arrive, to happen")
print("bouger** = to move")
print("brosser = to brush")
print("changer** = to change")
print("chanter = to sing")
print("chercher = to look for")
print("commencer** = to begin, start")
print("corriger**	= to correct")
print("danser = to dance")
print("demander = to ask for")
print("détester = to hate")
print("donner = to give")
print("écouter = to listen to")
print("effacer** = to erase")
print("étudier	= to study")
print("féliciter = to congratulate")
print("fêter  = to celebrate")
print("gagner = to win, to earn")
print("glisser = to slide")
print("habiter = to live")
print("jouer = to play")
print("manger** = to eat")
print("manquer = to miss")
print("marcher	= to walk, to function")
print("monter = to climb")
print("nager**	= to swim")
print("parler = to talk, to speak")
print("partager** = to share")
print("penser = to think")
print("regarder = to watch, to look at")
print("skier = to ski")
print("travailler = to work")
print("trouver	= to find")
print("visiter	= to visit (a place)")
print("voyager** = to travel")

print(Fore.BLUE, "2. -Ir Verbs")

print(Fore.WHITE, "abolir = to abolish")
print("accomplir = to accomplish")
print("agir = to act")
print("agrandir = to enlarge, to increase")
print("avertir = to warn")
print("bâtir = to build")
print("bénir = to bless")
print("blanchir = to whiten, to lighten")
print("choisir = to choose")
print("convertir = to convert")
print("définir = to define")
print("établir = to establish")
print("étourdir = to stun, to deafen, to make dizzy")
print("finir = to finish")
print("franchir = to clear (an obstacle)")
print("grossir = to gain weight, to get fat")
print("guérir = to cure, to heal, to recover")
print("investir = to invest")
print("maigrir = to lose weight, to get thin")
print("nourrir = to feed, to nourish")
print("obéir = to obey")
print("punir = to punish")
print("réfléchir = to reflect, to think")
print("remplir = to fill")
print("réussir = to succeed")
print("rougir = to blush, to turn red")
print("saisir = to seize")
print("vieillir = to age, grow old")

print(Fore.BLUE, "3. -Re Verbs")

print(Fore.WHITE, "attendre = to wait for")
print("confondre = to confuse")
print("correspondre = to correspond")
print("défendre = to defend")
print("dépendre = to depend")
print("descendre = to descend")
print("entendre = to hear, to understand")
print("étendre = to stretch")
print("fondre = to melt")
print("mordre = to bite")
print("pendre = to hang, suspend")
print("perdre = to lose")
print("prétendre = to claim")
print("rendre = to give back, to return")
print("répandre = to spread, to scatter")
print("répondre = to answer")
print("suspendre = to suspend")
print("tordre = to twist")
print("vendre = to sell")

print(Fore.RED,"Lesson 3.1 - Present Tense")           

print(Fore.WHITE,"I = je")
print("you = tu")
print("he/she/it = il/elle/on")
print("we = nouos")
print("you = vouos")
print("they = ils/elles")

print("Example for parler = to speak, finir = to finish and vendre = to sell")

print("je parle - je finis - je vends")
print("tu parles - tu finis - tu vends")
print("il parle - il finit - il vend")
print("nous parlons - nous finissons, nous vendons")
print("vous parlez - vous finissez - vous vendez")
print("elles parlent - elles finissent - elles vendent")

print(Fore.RED, "Lesson 4 - Adjectives")
print("")

print(Fore.WHITE, "Heureux = Happy")
print("Triste = Sad")
print("Énervé = Angry")
print("Peur = Afraid")
print("Joie = Joy")
print("Surpris = Surprised")
print("Calme = Calm")
print("Ennuyé = Bored")
print("Facile = Easy")
print("Difficile = Difficult")
print("Mauvais = Bad")
print("Bon = Good")
print("Bruyant = Noisy")
print("Silencieux = Quiet")
print("Fort = Strong")
print("Faible = Weak")
print("Dur = Hard")
print("Mou = Soft")
print("Plus = More")
print("Moins = Less")
print("Propre = Clean")
print("Sale = Dirty")
print("Vieux = Old")
print("Nouveau = New")
print("Grand = Big")
print("Petit = Small")
print("Jeune = Young")
print("Maigre = Skinny")
print("Gros = Fat")
print("Joli = Pretty")
print("Laid = Ugly")
print("Épais = Thick")
print("Mince = Thin")
print("Rêche = Rough")
print("Lisse = Smooth")

print(Fore.RED, "Lesson 5 - Days and Months")
print("")

print(Fore.BLUE, "Lesson 5.1 - Days of the week")
print("")

print(Fore.WHITE, "Les jours de la semaine = The days of the week") 
print("Jour = Day")
print("Semaine = Week")
print("Lundi = Monday")
print("Mardi = Tuesday")
print("Mercredi = Wednesday")
print("Jeudi = Thursday")
print("Vendredi = Friday")
print("Samedi = Saturday")
print("Dimanche = Sunday")
print("(la) Fin de semaine = Weekend")

print(Fore.RED, "Lesson 5.2 - Months of the year")
print("")

print(Fore.WHITE, "Les mois de l’année = The months of the year")
print("Mois = Month")
print("Année = Year")
print("Janvier = January")
print("Février = February")
print("Mars = March")
print("Avril = April")
print("Mai = May")
print("Juin = June")
print("Juillet = July")
print("Août = August")
print("Septembre = September")
print("Octobre = October")
print("Novembre = November")
print("Décembre = December")


print(Fore.RED,"Lesson 6 - Seasons and Weathers")
print("")

print(Fore.WHITE, "Les saisons = Seasons")
print("(le) Hiver = Winter")
print("(le) Été = Summer")
print("(le) Printemps = Spring") 
print("(le) Automne = Autumn")
print("Ciel = Sky")
print("Nuage = Cloud")  
print("Arc-en-ciel = Rainbow") 
print("Cold (weather) = Froid") 
print("Hot (weather) = Chaud")
print("Il fait chaud = It is hot")
print("Il fait froid = It is cold")
print("Il y a du soleil = It is sunny") 
print("Il fait nuageux = It is cloudy")
print("Il fait humide = It is humid")
print("Il pleut = It is raining")
print("Il neige = It is snowing")
print("Il y a du vent = It is windy") 
print("Quel temps fait-il?=  How is the weather?")
print("Beau temps = Good weather")
print("Mauvais temps = Bad weather") 
print("Quelle température fait-il? = What is the temperature?")
print("Il fait 24 degrés = It is 24 degrees")


print(Fore.RED, "Lesson 7 - Colors")
print("")

print(Fore.WHITE, "Noir = Black")
print("Bleu = Blue")
print("Marron = Brown")
print("Vert = Green")
print("Orange = Orange")
print("Violet = Purple")
print("Rouge = Red")
print("Blanc = White")
print("Jaune = Yellow")
print("Gris = Gray")
print("Doré = Gold")
print("Argenté = Silver")
print("Quelle couleur est-ce? = What color is it?")
print("C’est ___ = The color is ___")


print(Fore.RED,"Lesson 8 - Family and Friends")
print("")

print(Fore.BLUE,"Lesson 8.1 - Family members")
print("")

print(Fore.WHITE, "(la) Mère = Mother")
print("(le) Père = Father")
print("(le) Frère = Brother") 
print("(la) Sœur = Sister")
print("(le) Fils = Son")
print("(la) Fille = Daughter") 
print("Parents = Parents")
print("Enfants = Children")
print("Enfant = Child")
print("(la) Belle-mère = Stepmother") 
print("(le) Beau-père = Stepfather")
print("(la) Demi-sœur = Stepsister")
print("(le) Demi-frère = Stepbrother") 
print("Gendre = Son-in-law")
print("Daughter-in-law = Belle-fille")  
print("(la) Épouse = Wife")
print("(le) Mari = Husband")
print("Grands-parents = Grandparents") 
print("Grand-père = Grandfather")
print("Grand-mère = Grandmother")
print("Petit-fils = Grandson")
print("Petite-fille = Granddaughter")
print("Petits-enfants = Grandchildren") 
print("Petit enfant = Grandchild")
print("(la) Tante = Aunt")
print("(le) Oncle = Uncle")
print("(la) Cousine = Cousin (female)")
print("(le) Cousin = Cousin (male)")
print("(le) Neveu = Nephew")
print("(la) Nièce = Niece")
print("(le) Beau-père = Father-in-law")
print("(la) Belle-mère = Mother-in-law")
print("(le) Beau-frère = Brother-in-law")
print("(la) Belle-sœur = Sister-in-law")
print("Proche = Relative")


print(Fore.BLUE,"Lesson 8.2 - Friends")
print("")

print(Fore.WHITE, "Mademoiselle = Miss")
print("(le) Garçon = Boy")
print("(la) Fille = Girl")
print("Bébé = Baby")
print("(la) Femme = Woman")
print("(le) Homme = Man")
print("Ami = Friend (male)")
print("(la) Amie = Friend (female)")
print("(le) Petit ami = Boyfriend")
print("(la) Petite amie = Girlfriend")
print("Monsieur = Gentleman")
print("Dame = Lady")
print("Voisin = Neighbor (male)")
print("(la) Voisine = Neighbor (female)")
      

print(Fore.BLUE,"Lesson 9 - Numbers from 11 to 30")
print("")

print(Fore.WHITE, "Onze = 11")
print("Douze = 12")
print("Treize = 13")
print("Quatorze = 14") 
print("Quinze = 15")
print("Seize = 16")
print("Dix-sept = 17") 
print("Dix-huit = 18")
print("Dix-neuf = 19")
print("Vingt = 20")
print("Vingt et un = 21") 
print("Vingt-deux = 22")
print("Vingt-trois = 23")
print("Vingt-quatre = 24")
print("Vingt-cinq = 25")
print("Vingt-six = 26")
print("Vingt-sept = 27")
print("Vingt-huit = 28")
print("Vingt-neuf = 29")
print("Trente = 30")


print(Fore.RED,"Lesson 10 - Prepositions and Useful words")
print("")

print(Fore.BLUE,"Lesson 10.1 - Prepositions")
print("")

print(Fore.WHITE, "Pour = For")
print("Depuis = From")
print("Dans = In")
print("À l’intérieur = Inside") 
print("Dans = Into")
print("Près = Near")   
print("De = Of")
print("Hors = Out")
print("À l’extérieur = Outside")
print("À = To")
print("Sous = Under")
print("Avec = With")
print("Sans = Without") 
print("Au-dessus = Abo")    
print("De l'autre côté = Across")     
print("Après = After")
print("Contre = Against")   
print("Le long = Along") 
print("Autour = Around")    
print("À = At")
print("Derrière = Behind")    
print("En-dessous = Below")    
print("À côté de = Beside")   
print("Entre = Between")
print("Près = By")
print("Pendant = During")     
print("Sauf = Except") 
print("Et = And")
print("Parce que = Because")   
print("Mais = But")
print("Ou = Or")
print("Partout = Everywhere")    
print("Tout le monde = Everyone")    
print("Tout = Everything")    
print("Peu = Few")
print("Certains = Some")     
print("Beaucoup = Many")


print(Fore.BLUE,"Lesson 10.2 - Useful Words")
print("")

print(Fore.WHITE, "Question = Question")   
print("Réponse = Answer")
print("Vérité = Truth")
print("Mensonge = Lie")  
print("Rien = Nothing")  
print("Quelque chose = Something")    
print("Le même = Same")
print("Different = Différent")
print("Tirer = Pull")
print("Pousser = Push")    
print("Long = Long")
print("Court = Short")   
print("Froid = Cold") 
print("Chaud = Hot")
print("Clair = Light")   
print("Foncé = Dark") 
print("Mouillé = Wet")   
print("Sec = Dry") 
print("Vide = Empty")     
print("Plein = Full")   
print("Comment? = How?")    
print("Quoi? = What?")
print("Quand? = When?")   
print("Où? = Where?")
print("Lequel? = Which?")   
print("Qui? = Who?")
print("Pourquoi? = Why?")    
print("Combien de temps? = How long?")     
print("Combien? = How much?")


print(Fore.RED,"Lesson 11 - Drinks and Meals")

print(Fore.BLUE,"Lesson 11.1 - Drinks")

print(Fore.WHITE, "(le) Café = Coffee")
print("(le) Thé = Tea")
print("(la) Boisson gazeuse = Soft drink")
print("(la) Eau = Water")
print("(la) Limonade = Lemonade")
print("Jus = Juice")
print("(le) Jus d’orange = Orange juice")
print("Je voudrais un verre d’eau, s’il vous plaît = I would like a glass of water please")
print("Avec glaçons = With ice")

print(Fore.BLUE,"Lesson 11.2 - Dairy Products")

print(Fore.WHITE, "(le) Lait = Milk")
print("(la) Glace = Ice cream")
print("(le) Beurre = Butter")
print("(le) Fromage = Cheese")
print("Fromage cottage = Cottage cheese")
print("(la) Crème = Cream")
print("Crème fraîche = Sour cream")
print("(le) Yaourt = Yogurt")
print("Oeufs = Eggs")
print("Crème chantilly = Whipping cream")
print("(la) Boulangerie-pâtisserie = Bakery")
print("(la) Baguett = Baguette")
print("(le) Beignet = Doughnut")
print("(le) Petit gâteau = Cookie")
print("(le) Petit pain = Roll")
print("(le) Dessert = Dessert")
print("(le) Gâteau = Cake")
print("(le) Pain = Bread")
print("Tarte = Pie")

print(Fore.BLUE,"Lesson 11.3 - Meats")

print(Fore.WHITE, "(le) Bœuf = Beef")
print("(le) Veau = Veal")
print("(le) Jambon = Ham")
print("(le) Poulet = Chicken")
print("(la) Dinde = Turkey")
print("(le) Canard = Duck")
print("(le) Lard = Bacon")
print("(le) Porc = Pork")
print("Filet mignon = Filet mignon")
print("(la) Saucisse = Sausage")
print("(la) Côtelette d’agneau = Lamb chop")
print("(la) Côtelette de porc = Pork chop")
print("Viande = Meat")

print(Fore.BLUE,"Lesson 11.4 - Seafoods")

print(Fore.WHITE, "(le) Poisson = Fish")
print("(les) Fruits de mer = Shellfish")
print("(la) Perche = Bass")
print("(le) Saumon = Salmon")
print("(le) Homard = Lobster")
print("Crabe = Crab")
print("(la) Moule = Mussel")
print("(la) Huître = Oyster")
print("(le) Cabillaud = Cod")
print("(la) Palourde = Clam")
print("(la) Crevette = Shrimp")
print("(le) Thon = Tuna")
print("(la) Truite = Trout")
print("(la) Sole = Sole")
print("Requin = Shark")
print("Carpe = Carp")
print("Tilapia = Tilapia")
print("Anguille = Eel")
print("Poisson-chat = Catfish")
print("Espadon = Swordfish")

print(Fore.BLUE,"Lesson 11.5 - Herbs and Spices")

print(Fore.WHITE, "Sel = Salt")
print("(le) Poivre = Pepper")
print("Carvi = Caraway")
print("(le) Ail = Garlic")
print("Basilic = Basil")
print("Coriandre = Coriander")
print("Fenouil = Fennel")
print("Marjolaine = Marjoram")
print("Origan = Oregano")
print("Persil = Parsley")
print("Romarin = Rosemary")
print("Sauge = Sage")
print("Thym = Thyme")
print("Muscade = Nutmeg")
print("Paprika = Paprika")
print("Cayenne = Cayenne")
print("Gingembre = Ginger")

print(Fore.BLUE,"Lesson 11.6 - Vegetables")

print(Fore.WHITE, "(le) Céleri = Celery")
print("(la) Aubergine = Eggplant")
print("(la) Courgette = Zucchini")
print("(le) Oignon = Onion")
print("(les) Épinards = Spinach")
print("(la) Salade = Salad")
print("(les) Haricots verts = Green beans")
print("(le) Concombre = Cucumber")
print("(le) Radis = Radish")
print("(le) Chou = Cabbage")
print("(les) Champignons = Mushrooms")
print("(la) Laitue = Lettuce")
print("(le) Maïs = Corn")
print("(les) Pommes de terre = Potatoes")
print("(la) Tomate = Tomato")
print("(la) Carotte = Carrot")
print("(la) Banane plantain = Plantain")
print("(les) Haricots = Beans")
print("Poireau = Leek")
print("Racine de lotus = Lotus root")
print("Pousse de bambou = Bamboo shoot")
print("Artichaut = Artichoke")
print("Asperge = Asparagus")
print("Choux de bruxelles = Brussels sprouts")
print("Brocoli = Broccoli")
print("Pois = Peas")
print("Chou-fleur = Cauliflower")
print("Piment = Chili pepper")

print(Fore.BLUE,"Lesson 11.7 - Fruits")

print(Fore.WHITE, "(les) Cerises = Cherries")
print("Framboises = Raspberries")
print("Myrtilles = Blueberries")
print("(les) Fraises = Strawberries")
print("(le) Citron = Lemon")
print("Citron vert = Lime")
print("(la) Pomme = Apple")
print("(la) Orange = Orange")
print("(la) Poire = Pear")
print("(la) Banane = Banana")
print("(les) Raisins = Grapes")
print("(le) Pamplemousse = Grapefruit")
print("(la) Pastèque = Watermelon")
print("(le) Ananas = Pineapple")
print("(la) Prune = Plum")
print("Pêche = Peach")
print("Mangue = Mango")
print("Abricot = Apricot")
print("Grenade = Pomegranate")
print("Kaki = Persimmon")
print("Kiwi = Kiwi")
print("Litchi = Litchi")
print("Longane = Longan")
print("Melon amer = Balsam pear")
print("Fruit de la passion = Passion fruit")
print("(le) Avocat = Avocado")
print("Noix de coco = Coconut")


print(Fore.RED,"Lesson 12 - Irregular Verbs")

print(Fore.BLUE,"Lesson 12.1 - -Re Verbs")

print(Fore.WHITE, "être = to be")
print("être couché	= to lie down")
print("dire = to say")
print("comprendre = to understand")
print("prendre = to take")
print("écrire = to write")
print("entendre = to hear")
print("commencer = to begin")
print("casser = to break")
print("construire = to build")
print("choisir = to choose")
print("faire = to do/make")
print("conduire = to drive")
print("oublier = to forget")
print("obtenir = to get")
print("entendre = to hear")
print("tenir = to hold")
print("partir = to leave")
print("rencontrer = to meet")
print("payer = to pay")
print("mettre = to put")
print("lire = to read")
print("courir = to run")
print("voir = to see")
print("envoyer = to send")
print("dormir = to sleep")
print("parler = to speak")
print("passer = to spend (time)")
print("nager = to swim")
print("enseigner = to teach")
print("raconter = to tell")
print("penser = to think")
print("jeter = to throw")
print("gagner = to win")


print(Fore.RED,"Lesson 12.2 - -Er Verbs")

print(Fore.WHITE, "boire = to drink")
print("aller = to go")
print("donner = to give")
print("manger = to eat")
print("trouver = to find")
print("tomber = to fall")
print("apporter = to bring")
print("commencer = to begin")
print("casser = to break")
print("rencontrer = to meet")
print("payer = to pay")
print("parler = to speak")
print("passer = to spend (time)")
print("oublier = to forget")
print("envoyer = to send")
print("nager = to swim")
print("enseigner = to teach")
print("raconter = to tell")
print("penser = to think")
print("jeter = to throw")
print("gagner = to win")
print("apporter = to bring")

print(Fore.RED,"Lesson 12.3 - Ir Verbs")

print(Fore.WHITE, "avoir = to have")
print("venir = to come")
print("voir = to see")
print("savoir = to know (fact)")
print("vouloir = to want")
print("courir = to run")
print("s'asseoir = to sit")
print("se tenir debout = to stand")
print("obtenir = to get")
print("choisir = to choose")
print("tenir = to hold")
print("partir = to leave")
print("courir = to run")
print("voir = to see")
print("dormir = to sleep")

print(Fore.RED,"Lesson 13 - Present Simple")

print(Fore.WHITE) 

print(Fore.RED,"Lesson 14 - Numbers from 31-50")

print(Fore.WHITE, "trente et un = 31")
print("trente-deux = 32")
print("trente-trois = 33")
print("trente-quatre = 34")
print("trente-cinq = 35")
print("trente-six = 36")
print("trente-sept = 37")
print("trente-huit = 38")
print("trente-neuf = 39")
print("quarante = 40")
print("quarante et un = 41")
print("quarante-deux = 42")
print("quarante-trois = 43")
print("quarante-quatre = 44")
print("quarante-cinq = 45")
print("quarante-six = 46")
print("quarante-sept = 47")
print("quarante-huit = 48")
print("quarante-neuf = 49")
print("cinquante = 50")


print(Fore.RED,"Lesson 15 - Physical Appearance")
print(Fore.WHITE)

print(Fore.RED,"Lesson  16 - Occupations")
print(Fore.WHITE)
print(Fore.RED,"Lesson 17 - Sports")
print(Fore.WHITE)



