import keyboard

import colorama
from colorama import Fore, init
init()
print(Fore.RED,"1'den 10' a Sayılar")
print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print(Fore.WHITE,"eins = ?, zwei = ?, drei = ?, vier = ?, fünf = ?, sechs = ?, sieben = ?, acht = ?, neun = ?, zehn = ?")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")
mesaj = "Karşılık gelen rakamları giriniz:"
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

eins   = input(mesaj)
zwei   = input(mesaj)
drei   = input(mesaj)
vier   = input(mesaj)
fünf   = input(mesaj)
sechs  = input(mesaj)
sieben = input(mesaj)
acht   = input(mesaj)
neun   = input(mesaj)
zehn   = input(mesaj)
print("")

print("Devam etmek için spacebar'a basınız.")
keyboard.wait("space")

print("")

print("eins = 1, zwei = 2, drei  = 3, vier = 4, fünf = 5, sechs = 6, sieben = 7, acht = 8, neun = 9, zehn = 10")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print("İşlemler")

print("")
sayi1 = int(input("Birinci sayiyi giriniz:"))
sayi2 = int(input("İkinci sayiyi giriniz:"))
print("")

toplam = sayi1 + sayi2
print("")
print(toplam)
print("")

print(Fore.RED, "Lesson 2 - Greetings")
print("")

print(Fore.WHITE,"Hallo = Hello")
print("Wie geht es Ihnen = How are you?")
print("Freut mich, Sie kennen zu lernen = Nice to meet you")
print("Bis morgen = See you tomorrow")
print("Guten Morgen = Good morning")
print("Guten Machmittag = Good afternoon")
print("Guten Abend = Good Evening")
print("Gute Nacht = Good night")
print("Wie heissen sie ? = What is your name ?")
print("Mein name ist____ = My name is ___")
print("Wo wohnst du ? = Where do you live?")
print("Woher kommen Sie ? = Where are you from?")
print("Freut mich, Sie zu sehen = Nice to see you")
print("İch wünsche Ihnen einen schönen Tag = Have a nice day")
print("Bis spater = See you later")
print("Auf Wiedersehen = Goodbye")
print("Biyye = Please")
print("Danke = Thank you")

print(Fore.RED, "Lessson 3 - Regular Verbs")
print("")
print(Fore.WHITE, "arbeiten = to work")
print("lernen = to learn")
print("leben = to live")
print("spielen = to play")
print("fragen = to ask")
print("machen = to do / make")
print("sagen = to say")
print("kaufen = to buy")
print("hören = to hear / listen")
print("wohnen = to live (reside)")
print("lieben = to love")
print("reden = to talk")
print("lernen = to learn")
print("öffnen = to open")
print("warten = to wait")
print("zeigen = to show")
print("brauchen = to need")
print("tanzen = to dance")
print("glauben = to believe")
print("spielen = to play")
print("arbeiten = to work")
print("reisen = to travel")

print(Fore.RED,"Lesson 3.1 - Present Tense")           

print(Fore.WHITE,"I = ich")
print("you = du")
print("he/she/it = er/sie/es")
print("we = wir")
print("you = ihr")
print("they = Sie")

print("Example for lernen = to learn")

print("ich lerne")
print("du lernst")
print("er/sie/es lernt")
print("wir lernen")
print("ihr lernt")
print("Sie lernen")

print(Fore.BLUE, "Lesson 4 = Adjectives")

print(Fore.WHITE, "Glücklich = Happy")
print("Traurig = Sad")
print("Wütend = Angry")
print("Angst = Afraid")
print("Freude = Joy")
print("Überrascht = Surprised")
print("Ruhig = Calm")
print("Gelangweilt = Bored")
print("Leicht = Easy")
print("Schwer = Difficult")
print("Schlecht = Bad")
print("Gut = Good")
print("Laut = Noisy")
print("Leise = Quiet")
print("Stark = Strong")
print("Schwach = Weak")
print("Hart = Hard")
print("Weich = Soft")
print("Mehr = More")
print("Weniger = Less")
print("Sauber = Clean")
print("Schmutzig = Dirty")
print("Alt = Old")
print("Neu = New")
print("Groß = Big")
print("Klein = Small")
print("Jung = Young")
print("Dünn = Skinny")
print("Dick = Fat")
print("Hübsch = Pretty")
print("Hässlich = Ugly")
print("Dick = Thick")
print("Dünn = Thin")
print("Rau = Rough")
print("Glatt = Smooth")

print(Fore.RED,"Lesson 5 - Days and Months")
print("")

print(Fore.BLUE,"Lesson 5.1 - Days of the week")
print("")

print(Fore.WHITE, "Die Wochentage = The days of the week")
print("(der) Tag = Day")
print("(die) Woche = Week")
print("Montag = Monday")
print("Dienstag = Tuesday")
print("Mittwoch = Wednesday")
print("Donnerstag = Thursday")
print("Freitag = Friday")
print("Samstag = Saturday")
print("Sonntag = Sunday")
print("(das) Wochenende = Weekend")

print(Fore.RED, "Lesson 5.2 - Months of the year")
print("")

print(Fore.WHITE, "Die Monate des Jahres = The months of the year")
print("(der)Monat = Month")
print("(das)Jahr = Year")
print("Januar = January")
print("Februar = February")
print("März = March")
print("April = April")
print("Mai = May")
print("Juni = June")
print("Juli = July")
print("August = August")
print("September = September")
print("Oktober = October")
print("November = November")
print("Dezember = December")

print(Fore.RED,"Lesson 6 - Seasons and Weathers")
print("")

print(Fore.WHITE, "Jahreszeiten = Seasons")
print("(der) Winter = Winter")
print("(der) Sommer = Summer")
print("(der) Frühling = Spring") 
print("(der) Herbst = Autumn")
print("(der) Himmel = Sky")
print("(die)Wolke = Cloud")
print("(der) Regenbogen = Rainbow")
print("Kalt = Cold (weather)")
print("Heiß = Hot (weather)")
print("Es ist heiß = It is hot")
print("Es ist kalt = It is cold")
print("Es ist sonnig = It is sunny")
print("Es ist bewölkt = It is cloudy")
print("Es ist schwül = It is humid")
print("Es regnet = It is raining")
print("Es schneit = It is snowing")
print("Es ist windig = It is windy")
print("Wie ist das Wetter? = How is the weather?")
print("Gutes Wetter = Good weather")
print("Schlechtes Wetter = Bad weather")
print("Wie viel Grad ist es? = What is the temperature")
print("Es ist vierundzwanzig Grad = It is 24 degrees")
          
print(Fore.RED,"Lesson 7 - Colors")
print("")

print(Fore.WHITE, "Schwarz = Black")
print("Blau = Blue")
print("Braun = Brown")
print("Grün = Green")
print("Orange = Orange")
print("Lila = Purple")
print("Rot = Red")
print("Weiß = White")
print("Gelb = Yellow")
print("Grau = Gray")
print("Gold = Gold")
print("Silber = Silver")
print("Welche Farbe ist das? = What color is it?")
print("Das ist ___ = The color is ___")
      
print(Fore.RED,"Lesson 8 - Family and Friends")
print("")

print(Fore.BLUE,"Lesson 8.1 - Family members")
print("")

print(Fore.WHITE, "(die) Mutter = Mother")
print("(der) Vater = Father")
print("(der) Bruder = Brother")
print("(die) Schwester = Sister")
print("(der) Sohn = Son")
print("(die) Tochter = Daughter")
print("(die) Eltern = Parents")
print("(die) Kinder = Children")
print("(das) Kind = Child")
print("(die) Stiefmutter = Stepmother")
print("(der) Stiefvater = Stepfather")
print("(die) Stiefschwester = Stepsister")
print("(der) Stiefbruder = Stepbrother")
print("(der) Schwiegersohn = Son-in-law")
print("(die) Schwiegertochter = Daughter-in-law")
print("(die) Ehefrau = Wife")
print("(der) Ehemann = Husband")
print("(die) Großeltern = Grandparents")
print("(der) Opa = Grandfather")
print("(die) Oma = Grandmother")
print("(der) Enkel = Grandson")
print("(die) Enkelin = Granddaughter")
print("(die) Enkelkinder = Grandchildren")
print("(das) Enkelkind  Grandchild")
print("(die) Tante = Aunt")
print("(der) Onkel = Uncle")
print("(die) Cousine = Cousin (female)")
print("(der) Cousin = Cousin (male)")
print("(der) Neffe = Nephew")
print("(die) Nichte = Niece")
print("(der) Schwiegervater = Father-in-law")
print("(die) Schwiegermutter = Mother-in-law")
print("(der) Schwager = Brother-in-law")
print("(die) Schwägerin = Sister-in-law")
print("(der) Verwandter = Relative")

print(Fore.BLUE,"Lesson 8.2 - Friends")
print("")

print(Fore.WHITE, "Fräulein = Miss")
print("(der) Junge = Boy")
print("(das) Mädchen = Girl")
print("(das) Baby = Baby")
print("(die) Frau = Woman")
print("(der) Mann = Man")
print("(der) Freund = Friend (male)")
print("(die) Freundin = Friend (female)")
print("(der) Freund = Boyfriend")
print("(die) Freundin = Girlfriend")
print("(der) Gentleman = Gentleman")
print("(die) Dame = Lady")
print("(der) Nachbar = Neighbor (male)")
print("(die) Nachbarin = Neighbor (female)")


print(Fore.BLUE,"Lesson 9 - Numbers from 11 to 30")
print("")

print(Fore.WHITE, "Elf = 11")
print("Zwölf = 12")
print("Dreizehn = 13")
print("Vierzehn = 14")
print("Fünfzehn = 15")
print("Sechzehn = 16")
print("Siebzehn = 17")
print("Achtzehn = 18")
print("Neunzehn = 19")
print("Zwanzig = 20")
print("Einundzwanzig = 21")
print("Zweiundzwanzig = 22")
print("Dreiundzwanzig = 23")
print("Vierundzwanzig = 24")
print("Fünfundzwanzig = 25")
print("Sechsundzwanzig = 26")
print("Siebenundzwanzig = 27")
print("Achtundzwanzig = 28")
print("Neunundzwanzig = 29")
print("Dreißig = 30")
