import keyboard

import colorama
from colorama import Fore, init
init()
print(Fore.RED,"1'den 10' a Sayılar")
print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print(Fore.WHITE,"eins = ?, zwei = ?, drei = ?, vier = ?, fünf = ?, sechs = ?, sieben = ?, acht = ?, neun = ?, zehn = ?")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")
mesaj = "Karşılık gelen rakamları giriniz:"
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

eins   = input(mesaj)
zwei   = input(mesaj)
drei   = input(mesaj)
vier   = input(mesaj)
fünf   = input(mesaj)
sechs  = input(mesaj)
sieben = input(mesaj)
acht   = input(mesaj)
neun   = input(mesaj)
zehn   = input(mesaj)
print("")

print("Devam etmek için spacebar'a basınız.")
keyboard.wait("space")

print("")

print("eins = 1, zwei = 2, drei  = 3, vier = 4, fünf = 5, sechs = 6, sieben = 7, acht = 8, neun = 9, zehn = 10")
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")

print("İşlemler")

print("")
sayi1 = int(input("Birinci sayiyi giriniz:"))
sayi2 = int(input("İkinci sayiyi giriniz:"))
print("")

toplam = sayi1 + sayi2
print("")
print(toplam)
print("")

print(Fore.RED, "Lesson 2 - Greetings")
print("")

print(Fore.WHITE,"Hallo = Hello")
print("Wie geht es Ihnen = How are you?")
print("Freut mich, Sie kennen zu lernen = Nice to meet you")
print("Bis morgen = See you tomorrow")
print("Guten Morgen = Good morning")
print("Guten Machmittag = Good afternoon")
print("Guten Abend = Good Evening")
print("Gute Nacht = Good night")
print("Wie heissen sie ? = What is your name ?")
print("Mein name ist____ = My name is ___")
print("Wo wohnst du ? = Where do you live?")
print("Woher kommen Sie ? = Where are you from?")
print("Freut mich, Sie zu sehen = Nice to see you")
print("İch wünsche Ihnen einen schönen Tag = Have a nice day")
print("Bis spater = See you later")
print("Auf Wiedersehen = Goodbye")
print("Biyye = Please")
print("Danke = Thank you")

print(Fore.RED, "Lessson 3 - Regular Verbs")
print("")
print(Fore.WHITE, "arbeiten = to work")
print("lernen = to learn")
print("leben = to live")
print("spielen = to play")
print("fragen = to ask")
print("machen = to do / make")
print("sagen = to say")
print("kaufen = to buy")
print("hören = to hear / listen")
print("wohnen = to live (reside)")
print("lieben = to love")
print("reden = to talk")
print("lernen = to learn")
print("öffnen = to open")
print("warten = to wait")
print("zeigen = to show")
print("brauchen = to need")
print("tanzen = to dance")
print("glauben = to believe")
print("spielen = to play")
print("arbeiten = to work")
print("reisen = to travel")

print(Fore.RED,"Lesson 3.1 - Present Tense")           

print(Fore.WHITE,"I = ich")
print("you = du")
print("he/she/it = er/sie/es")
print("we = wir")
print("you = ihr")
print("they = Sie")

print("Example for lernen = to learn")

print("ich lerne")
print("du lernst")
print("er/sie/es lernt")
print("wir lernen")
print("ihr lernt")
print("Sie lernen")

print(Fore.BLUE, "Lesson 4 = Adjectives")

print(Fore.WHITE, "Glücklich = Happy")
print("Traurig = Sad")
print("Wütend = Angry")
print("Angst = Afraid")
print("Freude = Joy")
print("Überrascht = Surprised")
print("Ruhig = Calm")
print("Gelangweilt = Bored")
print("Leicht = Easy")
print("Schwer = Difficult")
print("Schlecht = Bad")
print("Gut = Good")
print("Laut = Noisy")
print("Leise = Quiet")
print("Stark = Strong")
print("Schwach = Weak")
print("Hart = Hard")
print("Weich = Soft")
print("Mehr = More")
print("Weniger = Less")
print("Sauber = Clean")
print("Schmutzig = Dirty")
print("Alt = Old")
print("Neu = New")
print("Groß = Big")
print("Klein = Small")
print("Jung = Young")
print("Dünn = Skinny")
print("Dick = Fat")
print("Hübsch = Pretty")
print("Hässlich = Ugly")
print("Dick = Thick")
print("Dünn = Thin")
print("Rau = Rough")
print("Glatt = Smooth")

print(Fore.RED,"Lesson 5 - Days and Months")
print("")

print(Fore.BLUE,"Lesson 5.1 - Days of the week")
print("")

print(Fore.WHITE, "Die Wochentage = The days of the week")
print("(der) Tag = Day")
print("(die) Woche = Week")
print("Montag = Monday")
print("Dienstag = Tuesday")
print("Mittwoch = Wednesday")
print("Donnerstag = Thursday")
print("Freitag = Friday")
print("Samstag = Saturday")
print("Sonntag = Sunday")
print("(das) Wochenende = Weekend")

print(Fore.RED, "Lesson 5.2 - Months of the year")
print("")

print(Fore.WHITE, "Die Monate des Jahres = The months of the year")
print("(der)Monat = Month")
print("(das)Jahr = Year")
print("Januar = January")
print("Februar = February")
print("März = March")
print("April = April")
print("Mai = May")
print("Juni = June")
print("Juli = July")
print("August = August")
print("September = September")
print("Oktober = October")
print("November = November")
print("Dezember = December")