import keyboard

import colorama
from colorama import Fore, init
init()
print(Fore.RED,"1'den 10' a Sayılar")
print(Fore.WHITE,"viens =?, divi =?, tris =?, cetri =?, pieci =?, sesi =?, septini =?, ostoni =?, devini =?, desmit =?")
print("Devam etmek için spacebar'a basınız.")
keyboard.wait("space")
print("")

mesaj = "Karşılık gelen rakamları giriniz:"

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")

viensn  = input(mesaj)
divi    = input(mesaj)
trīs    = input(mesaj)
četri   = input(mesaj)
pieci   = input(mesaj)
seši    = input(mesaj)
septiņi = input(mesaj)
astoņi  = input(mesaj)
deviņi  = input(mesaj)
desmit  = input(mesaj)

print("viensn = 1, divi = 2, trīs = 3, četri = 4, pieci = 5, seši = 6, septiņi = 7, astoņi = 8, deviņi = 9, desmit = 10")

print(Fore.RED, "Lesson 2 - Greetings")
print("")

print(Fore.WHITE, "Sveiki = Hello")
print("Ka jums klajas ? = How are you?")
print("Prieks iepazities = Nice to meet you")
print("Tiksimies rit = See you tomorrow")
print("Labrit = Good morning")
print("Labdien = Good afternoon")
print("Labrakar = Good evening")
print("Ar labu nakti = Good night")
print("Kads ir jusu vards ?  = What is your name ?")
print("Mani sauc ____ = My name is ___")
print("Kur tu dzivo ? = Where do you live?")
print("No kurienes jus esat ? = Where are you from?")
print("Patikami jus redzet = Nice to see you")
print("Novelu jums jauku dienu = Have a nice day")
print("Tiksimies velak = See you later")
print("UZ redzesanos = Goodbye")
print("Ludzu = Please")
print("Paldies = Thank you")


print(Fore.RED, "Lesson 3 - Regular Verbs")
print("")

print(Fore.WHITE,"Regular verbs are divided into 6 categories")

print(Fore.BLUE, "1. -Āt Verbs")

print(Fore.WHITE, "runāt = to speak")
print("strādāt = to work")
print("domāt = to think")
print("dziedāt = to sing")
print("mēģināt = to try")
print("pārdomāt = to reflect")
print("uzaicināt = to invite")

print(Fore.BLUE, "2. -Īt Verbs")

print(Fore.WHITE, "lasīt = to read")
print("smaidīt = to smile")
print("mācīt = to teach")
print("uzrakstīt = to write")
print("nosūtīt = to send")
print("pierakstīt = to note")
print("apskatīt = to look at")

print(Fore.BLUE, "3. Ot Verbs")

print(Fore.WHITE, "dzīvot = to live")
print("gatavot	= to cook")
print("ceļot = to travel")
print("vērot = to observe")
print("izskaidrot = to explain")
print("paskaidrot = to explain")
print("novērot = to monitor")	

print(Fore.BLUE, "4. -Ties Verbs")

print(Fore.WHITE,"skatīties = to watch")
print("mācīties = to learn")
print("klausīties = to listen")
print("apsēsties = to sit down")

print(Fore.BLUE, "5. -Ēt Verbs")

print(Fore.WHITE,"peldēt = to swim")
print("meklēt = to search")
print("vēlēt = to wish")
print("zīmēt = to draw")
print("gulēt = to sleep")
print("apmeklēt = to attend")
print("atbildēt = to answer")

print(Fore.BLUE, "6. -T Verbs")

print(Fore.WHITE, "lūgt = to ask")
print("saprast = to understand")
print("braukt = to drive/go")
print("sajust = to feel")
print("aizvērt = to close")
print("uzdot = to assign")
print("pārtraukt = to interrupt")

print("Lesson 3.1 - Present Tense")           

print("I = Es")
print("you = Tu/jus")
print("he/she/it = vins/vina")
print("we = mes")
print("you = Jus")
print("they = vini")

print("Example for stradat = to work, lasit = to read, dzivot = to live, skatities = to look, gulet = to sleep")

print("1. Example = Stradat\n,Es strādāju\n, Tu strādā\n, Vins/vina strādā\n, Mes strādājam\n, Jus strādājat\n, Vini strādā\n")
print("2. Example = Lasit\n, Es lasu\n, Tu lasi\n, Vins/vina lasa\n, Mes lasām\n, Jus lasāt\n, Vini lasa\n")
print("3. Example = dzivot\n, Es dzīvoju\n, Tu dzīvo\n, Vins/vina dzīvo\n, Mes dzīvojam\n, Jus dzīvojat\n Vini  dzīvo\n")
print("4. Example = Skatites\n, Es skatos\n, Tu skaties\n, Vins/vina skatās\n, Mes skatāmies\n,	Jus skatāties\n, Vini skatās\n")
print("5. Exapmle = Gulet\n, Es guļu\n, Tu guli\n, Vins/vina guļ\n, Mes guļam\n, Jus guļat\n, Vini guļ") 

print(Fore.RED, "Lesson 4 - Adjectives")
print("")

print(Fore.WHITE, "Laimīgs = Happy")
print("Bēdīgs = Sad")
print("Dusmīgs = Angry")
print("Nobijies = Afraid")
print("Prieks = Joy")
print("Pārsteigts = Surprised")
print("Mierīgs = Calm")
print("Garlaikots = Bored")
print("Viegli = Easy")
print("Grūti = Difficult")
print("Slikts = Bad")
print("Labs = Good")
print("Skaļš = Noisy")
print("Kluss = Quiet")
print("Spēcīgs = Strong") 
print("Vājš = Weak")
print("Ciets = Hard")
print("Mīksts = Soft")
print("Vairāk = More")
print("Mazāk = Less")
print("Tīrs = Clean")
print("Netīrs = Dirty")
print("Jauns = New")
print("Liels = Big")
print("Mazs = Small")
print("Jauns = Young")
print("Vecs = Old")
print("Tievs = Skinny")
print("Resns = Fat")
print("Glīts = Pretty")
print("Neglīts = Ugly")
print("Biezs = Thick")
print("Plāns = Thin")
print("Rupjš = Rough")
print("Gluds = Smooth")

print(Fore.RED, "Lesson 5 - Days and Months")
print("")

print(Fore.BLUE, "Lesson 5.1 - Days of the week")
print("")

print(Fore.WHITE, "Nedēļas dienas = The days of the week")
print("Diena = Day")
print("Nedēļa = Week")
print("Pirmdiena = Monday")
print("Otrdiena = Tuesday")
print("Trešdiena = Wednesday")
print("Ceturtdiena = Thursday")
print("Piektdiena = Friday")
print("Sestdiena = Saturday")
print("Svētdiena = Sunday")
print("Nedēļas nogale = Weekend")


print(Fore.RED, "Lesson 5.2 - Months of the year")
print("")

print(Fore.WHITE, "Gada mēneši = The months of the year")
print("Mēnesis = Month")
print("Gads = Year")
print("Janvāris = January")
print("Februāris = February")
print("Marts = March")
print("Aprīlis = April")
print("Maijs = May")
print("Jūnijs = June")
print("Jūlijs = July")
print("Augusts = August")
print("Septembris = September")
print("Oktobris = October")
print("Novembris = November")
print("Decembris = December")


print(Fore.RED,"Lesson 6 - Colors")
print("")

print(Fore.WHITE, "Melns = Black")
print("Zils = Blue")
print("Brūns = Brown")
print("Zaļš = Green")
print("Oranžs = Orange")
print("Purpurs = Purple")
print("Sarkans = Red")
print("Balts = White")
print("Dzeltens = Yellow")
print("Pelēks = Gray")
print("Zelts = Gold")
print("Sudrabs = Silver")
print("Kādā krāsā tas ir? = What color is it?")
print("Krāsa ir ___  = The color is ___")