import keyboard

import colorama
from colorama import Fore, init
init()
print(Fore.RED,"1'den 10' a Sayılar")
print(Fore.WHITE,"viens =?, divi =?, tris =?, cetri =?, pieci =?, sesi =?, septini =?, ostoni =?, devini =?, desmit =?")
print("Devam etmek için spacebar'a basınız.")
keyboard.wait("space")
print("")

mesaj = "Karşılık gelen rakamları giriniz:"

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")

viensn  = input(mesaj)
divi    = input(mesaj)
trīs    = input(mesaj)
četri   = input(mesaj)
pieci   = input(mesaj)
seši    = input(mesaj)
septiņi = input(mesaj)
astoņi  = input(mesaj)
deviņi  = input(mesaj)
desmit  = input(mesaj)

print("viensn = 1, divi = 2, trīs = 3, četri = 4, pieci = 5, seši = 6, septiņi = 7, astoņi = 8, deviņi = 9, desmit = 10")

print(Fore.RED, "Lesson 2 - Greetings")
print("")

print(Fore.WHITE, "Sveiki = Hello")
print("Ka jums klajas ? = How are you?")
print("Prieks iepazities = Nice to meet you")
print("Tiksimies rit = See you tomorrow")
print("Labrit = Good morning")
print("Labdien = Good afternoon")
print("Labrakar = Good evening")
print("Ar labu nakti = Good night")
print("Kads ir jusu vards ?  = What is your name ?")
print("Mani sauc ____ = My name is ___")
print("Kur tu dzivo ? = Where do you live?")
print("No kurienes jus esat ? = Where are you from?")
print("Patikami jus redzet = Nice to see you")
print("Novelu jums jauku dienu = Have a nice day")
print("Tiksimies velak = See you later")
print("UZ redzesanos = Goodbye")
print("Ludzu = Please")
print("Paldies = Thank you")


print(Fore.RED, "Lesson 3 - Regular Verbs")
print("")

print(Fore.WHITE,"Regular verbs are divided into 6 categories")

print(Fore.BLUE, "1. -Āt Verbs")

print(Fore.WHITE, "runāt = to speak")
print("strādāt = to work")
print("domāt = to think")
print("dziedāt = to sing")
print("mēģināt = to try")
print("pārdomāt = to reflect")
print("uzaicināt = to invite")

print(Fore.BLUE, "2. -Īt Verbs")

print(Fore.WHITE, "lasīt = to read")
print("smaidīt = to smile")
print("mācīt = to teach")
print("uzrakstīt = to write")
print("nosūtīt = to send")
print("pierakstīt = to note")
print("apskatīt = to look at")

print(Fore.BLUE, "3. Ot Verbs")

print(Fore.WHITE, "dzīvot = to live")
print("gatavot	= to cook")
print("ceļot = to travel")
print("vērot = to observe")
print("izskaidrot = to explain")
print("paskaidrot = to explain")
print("novērot = to monitor")	

print(Fore.BLUE, "4. -Ties Verbs")

print(Fore.WHITE,"skatīties = to watch")
print("mācīties = to learn")
print("klausīties = to listen")
print("apsēsties = to sit down")

print(Fore.BLUE, "5. -Ēt Verbs")

print(Fore.WHITE,"peldēt = to swim")
print("meklēt = to search")
print("vēlēt = to wish")
print("zīmēt = to draw")
print("gulēt = to sleep")
print("apmeklēt = to attend")
print("atbildēt = to answer")

print(Fore.BLUE, "6. -T Verbs")

print(Fore.WHITE, "lūgt = to ask")
print("saprast = to understand")
print("braukt = to drive/go")
print("sajust = to feel")
print("aizvērt = to close")
print("uzdot = to assign")
print("pārtraukt = to interrupt")

print("Lesson 3.1 - Present Tense")           

print("I = Es")
print("you = Tu/jus")
print("he/she/it = vins/vina")
print("we = mes")
print("you = Jus")
print("they = vini")

print("Example for stradat = to work, lasit = to read, dzivot = to live, skatities = to look, gulet = to sleep")

print("1. Example = Stradat\n,Es strādāju\n, Tu strādā\n, Vins/vina strādā\n, Mes strādājam\n, Jus strādājat\n, Vini strādā\n")
print("2. Example = Lasit\n, Es lasu\n, Tu lasi\n, Vins/vina lasa\n, Mes lasām\n, Jus lasāt\n, Vini lasa\n")
print("3. Example = dzivot\n, Es dzīvoju\n, Tu dzīvo\n, Vins/vina dzīvo\n, Mes dzīvojam\n, Jus dzīvojat\n Vini  dzīvo\n")
print("4. Example = Skatites\n, Es skatos\n, Tu skaties\n, Vins/vina skatās\n, Mes skatāmies\n,	Jus skatāties\n, Vini skatās\n")
print("5. Exapmle = Gulet\n, Es guļu\n, Tu guli\n, Vins/vina guļ\n, Mes guļam\n, Jus guļat\n, Vini guļ") 

print(Fore.RED, "Lesson 4 - Adjectives")
print("")

print(Fore.WHITE, "Laimīgs = Happy")
print("Bēdīgs = Sad")
print("Dusmīgs = Angry")
print("Nobijies = Afraid")
print("Prieks = Joy")
print("Pārsteigts = Surprised")
print("Mierīgs = Calm")
print("Garlaikots = Bored")
print("Viegli = Easy")
print("Grūti = Difficult")
print("Slikts = Bad")
print("Labs = Good")
print("Skaļš = Noisy")
print("Kluss = Quiet")
print("Spēcīgs = Strong") 
print("Vājš = Weak")
print("Ciets = Hard")
print("Mīksts = Soft")
print("Vairāk = More")
print("Mazāk = Less")
print("Tīrs = Clean")
print("Netīrs = Dirty")
print("Jauns = New")
print("Liels = Big")
print("Mazs = Small")
print("Jauns = Young")
print("Vecs = Old")
print("Tievs = Skinny")
print("Resns = Fat")
print("Glīts = Pretty")
print("Neglīts = Ugly")
print("Biezs = Thick")
print("Plāns = Thin")
print("Rupjš = Rough")
print("Gluds = Smooth")

print(Fore.RED, "Lesson 5 - Days and Months")
print("")

print(Fore.BLUE, "Lesson 5.1 - Days of the week")
print("")

print(Fore.WHITE, "Nedēļas dienas = The days of the week")
print("Diena = Day")
print("Nedēļa = Week")
print("Pirmdiena = Monday")
print("Otrdiena = Tuesday")
print("Trešdiena = Wednesday")
print("Ceturtdiena = Thursday")
print("Piektdiena = Friday")
print("Sestdiena = Saturday")
print("Svētdiena = Sunday")
print("Nedēļas nogale = Weekend")


print(Fore.RED, "Lesson 5.2 - Months of the year")
print("")

print(Fore.WHITE, "Gada mēneši = The months of the year")
print("Mēnesis = Month")
print("Gads = Year")
print("Janvāris = January")
print("Februāris = February")
print("Marts = March")
print("Aprīlis = April")
print("Maijs = May")
print("Jūnijs = June")
print("Jūlijs = July")
print("Augusts = August")
print("Septembris = September")
print("Oktobris = October")
print("Novembris = November")
print("Decembris = December")

print(Fore.RED,"Lesson 6 - Seasons and Weathers")
print("")

print(Fore.WHITE, "Gadalaiki = Seasons")
print("Ziema = Winter")
print("Vasara = Summer")
print("Pavasaris = Spring")
print("Rudens = Autumn")
print("Debesis = Sky")
print("Mākonis = Cloud")
print("Varavīksne = Rainbow")
print("Auksts = Cold (weather)")
print("Karsts = Hot (weather)")
print("Ir karsts = It is hot")
print("Ir auksts = It is cold")
print("Ir saulains = It is sunny")
print("Ir mākoņains = It is cloudy")
print("Ir mitrs = It is humid")
print("Līst = It is raining")
print("Snieg = It is snowing")
print("Ir vējains = It is windy")
print("Kāds ir laiks? = How is the weather?")
print("Labs laiks = Good weather")
print("Slikts laiks = Bad weather")
print("Kāda ir temperatūra? = What is the temperature?")
print("Ārā ir 24 grādi = It is 24 degrees")


print(Fore.RED,"Lesson 7 - Colors")
print("")

print(Fore.WHITE, "Melns = Black")
print("Zils = Blue")
print("Brūns = Brown")
print("Zaļš = Green")
print("Oranžs = Orange")
print("Purpurs = Purple")
print("Sarkans = Red")
print("Balts = White")
print("Dzeltens = Yellow")
print("Pelēks = Gray")
print("Zelts = Gold")
print("Sudrabs = Silver")
print("Kādā krāsā tas ir? = What color is it?")
print("Krāsa ir ___  = The color is ___")

print(Fore.RED,"Lesson 8 - Family and Friends")
print("")

print(Fore.BLUE,"Lesson 8.1 - Family members")
print("")

print(Fore.WHITE, "Māte = Mother")
print("Tēvs = Father")
print("Brālis = Brother")
print("Māsa = Sister")
print("Dēls = Son")
print("Meita = Daughter")
print("Vecāki = Parents")
print("Bērni = Children")
print("Bērns = Child")
print("Pamāte = Stepmother")
print("Patēvs = Stepfather")
print("Pusmāsa = Stepsister")
print("Pusbrālis = Stepbrother")
print("Znots = Son-in-law")
print("Vedekla = Daughter-in-law")
print("Sieva = Wife")
print("Vīrs = Husband")
print("Vecvecāki = Grandparents")
print("Vectēvs = Grandfather")
print("Vecmāmiņa = Grandmother")
print("Mazdēls = Grandson")
print("Mazmeita = Granddaughter")
print("Mazbērni = Grandchildren")
print("Mazbērns = Grandchild")
print("Tante = Aunt")
print("Tēvocis = Uncle")
print("Māsīca = Cousin (fmale)")
print("Brālēns = Cousin (male)")
print("Brāļadēls = Nephew")
print("Brāļameita = Niece")
print("Vīratēvs = Father-in-law")
print("Vīramāte = Mother-in-law")
print("Svainis = Brother-in-law")
print("Svaine = Sister-in-law")
print("Radinieks = Relative")

print(Fore.BLUE,"Lesson 8.2 - Friends")
print("")

print(Fore.WHITE, "Jaunkundze = Miss")
print("Zēns = Boy")
print("Meitene = Girl")
print("Mazulis = Baby")
print("Sieviete = Woman")
print("Vīrietis = Man")
print("Draugs = Friend (male)")
print("Draudzene = Friend (female)")
print("Draugs = Boyfriend")
print("Draudzene = Girlfriend")
print("Kungs = Gentleman")
print("Dāma = Lady")
print("Kaimiņš = Neighbor (male)")
print("Kaimiņiene = Neighbor (female)")

print(Fore.BLUE,"Lesson 9 - Numbers from 11 to 30")
print("")

print(Fore.WHITE, "11  = Vienpadsmit")
print("Divpadsmit = 12")
print("Trīspadsmit = 13")
print("Četrpadsmit = 14")
print("Piecpadsmit = 15")
print("Sešpadsmit = 16")
print("Septiņpadsmit = 17") 
print("Astoņpadsmit = 18")
print("Deviņpadsmit = 19")
print("Divdesmit = 20")
print("Divdesmit viens = 21")  
print("Divdesmit divi = 22")
print("Divdesmit trīs = 23")
print("Divdesmit četri = 24") 
print("Divdesmit pieci = 25")
print("Divdesmit seši = 26")
print("Divdesmit septiņi = 27")  
print("Divdesmit astoņi = 28")
print("Divdesmit deviņi = 29")
print("Trīsdesmit = 30")

print(Fore.RED,"Lesson 10 - Prepositions and Useful words")
print("")

print(Fore.BLUE,"Lesson 10.1 - Prepositions")
print("")

print(Fore.WHITE, "Par = For")
print("No = From")
print("Iekšā = In")
print("Iekšā = Inside")
print("Iekšā = Into")
print("Tuvu = Near")
print("No = Of")
print("Ārā = Out")
print("Ārpus = Outside")
print("Uz = To")
print("Zem = Under")
print("Ar = With")
print("Bez = Without")
print("Virs = Above")
print("Pāri = Across")
print("Pēc = After")
print("Pret = Against")
print("Līdzās = Along")
print("Apkārt = Around")
print("Pie = At")
print("Aiz = Behind")
print("Apakšā = Below")
print("Blakus = Beside")
print("Starp = Between")
print("Blakus = By")
print("Laikā = During")
print("Izņemot = Except")
print("Un = And")
print("Jo = Because")
print("Bet = But")
print("Vai = Or")
print("Visur = Everywhere")
print("Ikviens = Everyone")
print("Viss = Everything")
print("Maz = Few")
print("Daži = Some")
print("Daudz = Many")
      

print(Fore.BLUE,"Lesson 10.2 - Useful Words")
print("")

print(Fore.WHITE, "Jautājums = Question")
print("Atbilde = Answer")
print("Patiesība = Truth")
print("Meli = Lie")
print("Nekas = Nothing")
print("Kaut kas = Something")
print("Tas pats = Same")
print("Atšķirīgs = Different")
print("Vilkt = Pull")
print("Stumt = Push")
print("Garš = Long")
print("Īss = Short")
print("Auksts = Cold")
print("Karsts = Hot")
print("Gaišs = Light")
print("Tumšs = Dark")
print("Slapjš = Wet")
print("Sauss = Dry")
print("Tukšs = Empty")
print("Pilns = Full")
print("Kā? = How?")
print("Kas? = What?")
print("Kad? = When?")
print("Kur? = Where?")
print("Kurš? = Which?")
print("Kas? = Who?")
print("Kāpēc? = Why?")
print("Cik ilgi? = How long?")
print("Cik daudz? = How much?")
       

print(Fore.RED,"Lesson 11 - Drinks and Meals")
print("")

print(Fore.BLUE,"Lesson 11.1 - Drinks")
print("")

print(Fore.WHITE, "Kafija = Coffee")
print("Tēja = Tea")
print("Gāzēts dzēriens = Soft drink")
print("Ūdens = Water")
print("Limonāde = Lemonade")
print("Sula = Juice")
print("Apelsīnu sula = Orange juice")
print("Es gribētu glāzi ūdens, lūdzu = I would like a glass of water please")
print("Ar ledu = With ice")


print(Fore.BLUE,"Lesson 11.2 - Dairy Products")
print("")

print(Fore.WHITE, "Piens = Milk")
print("Saldējums = Ice cream")
print("Sviests = Butter")
print("Siers = Cheese")
print("Biezpiens = Cottage cheese")
print("Krēms = Cream")
print("Skābais krējums = Sour cream")
print("Jogurts = Yogurt")
print("Olas = Eggs")
print("Putukrējums = Whipping cream")
print("Maiznīca = Bakery")
print("Bagete = Baguette")
print("Virtulis = Doughnut")
print("Cepums = Cookie")
print("Rullītis = Roll")
print("Deserts = Dessert")
print("Kūka = Cake")
print("Maize = Bread")
print("Pīrāgs = Pie")
      

print(Fore.BLUE,"Lesson 11.3 - Meats")
print("")

print(Fore.WHITE, "Liellopu gaļa = Beef")
print("Teļa gaļa = Veal")
print("Šķiņķis = Ham")
print("Cālis = Chicken")
print("Tītars = Turkey")
print("Pīle = Duck")
print("Bekons = Bacon")
print("Cūkgaļa = Pork")
print("Liellopa gaļas medaljons = Filet mignon")
print("Desa = Sausage")
print("Jēra karbonāde = Lamb chop")
print("Karbonāde = Pork chop")
print("Gaļa = Meat")


print(Fore.BLUE,"Lesson 11.4 - Seafoods")
print("")

print(Fore.WHITE, "Zivs = Fish")
print("Vēžveidīgie = Shellfish")
print("Asaris = Bass")
print("Lasis = Salmon")
print("Omārs = Lobster")
print("Krabis = Crab")
print("Gliemene = Mussel")
print("Austere = Oyster")
print("Menca = Cod")
print("Gliemezis = Clam")
print("Garnele = Shrimp")
print("Tuncis = Tuna")
print("Forele = Trout")
print("Zole = Sole")
print("Haizivs = Shark")
print("Karpa = Carp")
print("Tilapija = Tilapia")
print("Zutis = Eel")
print("Sams = Catfish")
print("Zobenzivs = Swordfish")


print(Fore.BLUE,"Lesson 11.5 - Herbs and Spices")
print("")

print(Fore.WHITE, "Sāls = Salt")
print("Pipari = Pepper")
print("Ķimenes = Caraway")
print("Ķiploki = Garlic")
print("Baziliks = Basil")
print("Koriandrs = Coriander")
print("Fenhelis = Fennel")
print("Majorāns = Marjoram")
print("Oregano = Oregano")
print("Pētersīļi = Parsley")
print("Rozmarīns = Rosemary")
print("Salvija = Sage")
print("Timiāns = Thyme")
print("Muskatrieksts = Nutmeg")
print("Paprika = Paprika")
print("Kajēnas pipari = Cayenne")
print("Ingvers = Ginger")


print(Fore.BLUE,"Lesson 11.6 - Vegetables")
print("")

print(Fore.WHITE, "Selerijas = Celery")
print("Baklažāns = Eggplant")
print("Cukīni = Zucchini")
print("Sīpols = Onion")
print("Spināti = Spinach")
print("Salāti = Salad")
print("Pākšu pupiņas = Green beans")
print("Gurķis = Cucumber")
print("Redīss = Radish")
print("Kāposti = Cabbage")
print("Sēnes = Mushrooms")
print("Salāti = Lettuce")
print("Kukurūza = Corn")
print("Kartupeļi = Potatoes")
print("Tomāts = Tomato")
print("Burkāns = Carrot")
print("Plantāns = Plantain")
print("Pupas = Beans")
print("Puravi = Leek")
print("Lotosa saknes = Lotus root")
print("Bambusa atvases = Bamboo shoot")
print("Artišoks = Artichoke")
print("Sparģeļi = Asparagus")
print("Briseles kāposti = Brussels sprouts")
print("Brokoļi = Broccoli")
print("Zirņi = Peas")
print("Ziedkāposti = Cauliflower")
print("Čili pipari = Chili pepper")


print(Fore.BLUE,"Lesson 11.7 - Fruits")
print("")

print(Fore.WHITE, "Ķirši = Cherries")
print("Avenes = Raspberries")
print("Mellenes = Blueberries")
print("Zemenes = Strawberries")
print("Citrons = Lemon")
print("Laims = Lime")
print("Ābols = Apple")
print("Apelsīns = Orange")
print("Bumbieris = Pear")
print("Banāns = Banana")
print("Vīnogas = Grapes")
print("Greipfrūts = Grapefruit")
print("Arbūzs = Watermelon")
print("Ananass = Pineapple")
print("Plūme = Plum")
print("Persiks = Peach")
print("Mango = Mango")
print("Aprikoze = Apricot")
print("Granātābols = Pomegranate")
print("Hurma = Persimmon")
print("Kivi = Kiwi")
print("Ķīniešu plūmes = Litchi")
print("Longans = Longan")
print("Balzambumbieris = Balsam pear")
print("Marakuja = Passion fruit")
print("Avokado = Avocado")
print("Kokosrieksts = Coconut")

print(Fore.RED,"Lesson 12 - Numbers from 31-50")

print(Fore.WHITE, "trīsdesmit viens = 31")
print("trīsdesmit divi = 32")
print("trīsdesmit trīs = 33")
print("trīsdesmit četri = 34")
print("trīsdesmit pieci = 35")
print("trīsdesmit seši = 36")
print("trīsdesmit septiņi = 37")
print("trīsdesmit astoņi = 38")
print("trīsdesmit deviņi = 39")
print("četrdesmit = 40")
print("četrdesmit viens = 41")
print("četrdesmit divi = 42")
print("četrdesmit trīs = 43")
print("četrdesmit četri = 44")
print("četrdesmit pieci = 45")
print("četrdesmit seši = 46")
print("četrdesmit septiņi = 47")
print("četrdesmit astoņi = 48")
print("četrdesmit deviņi = 49")
print("piecdesmit = 50")

print(Fore.RED,"Lesson 13 - Irregular Verbs")

print(Fore.WHITE, "būt = to be")
print("iet	= to go")
print("varēt = can, be able to")
print("darīt = to do")
print("braukt = to drive/go")
print("ēst = to eat")
print("nākt = to come")
print("dot = to give")
print("gribēt = to want")
print("sākt = to start")
print("zināt = to know")
print("teikt = to say")
print("saprast = to understand")
print("likt = to put")
print("atrast = to find")
print("sēdēt = to sit")
print("zvanīt = to call")
print("palīdzēt = to help")
print("aizmirst = to forget")
print("atbildēt = to answer")
print("ņemt = to take")
print("skriet = to run")
print("kļūt = to become")
print("dziedāt = to sing")
print("aizmirst = to forget")
print("paslēpt = to hide")
print("turpināt = to continue")
print("paskaidrot = to explain")
print("sagaidīt = to wait for")
print("sapņot = to dream")
print("nosūtīt = to send")
print("apstāties = to stop")
print("uzkāpt = to climb")
print("izvēlēties = to choose")
print("uzvarēt = to win")
print("zaudēt = to lose")
print("degt = to burn")
print("apsēsties = to sit down")
print("paņemt = to take (quickly)")
print("uzdot = to assign")
print("risināt = to solve")
print("glābt = to save (rescue)")
print("aizvērt = to close")
print("pagatavot = to prepare")
print("uzbūvēt = to build")
print("izrotāt = to decorate")
print("sapulcēt = to gather")
print("sacerēt = to compose")


print(Fore.RED,"Lesson 14 - Present Simple")

print(Fore.BLUE, "Example for būt = to be, ēst = to eat and iet	= to go")

print(Fore.WHITE, "es esmu - es ēdu - es eju")
print("tu esi - tu ēd - tu ej")
print("viņš/viņa ir - viņš/viņa ēd - viņš/viņa iet")
print("viņš/viņa ir - mēs ēdam, mēs ejam")
print("jūs esat - jūs ēdat - jūs ejat")
print("viņi/viņas ir - viņi/viņas ēd - viņi/viņas iet")

print(Fore.RED,"Lesson 15 - Physical Appearance")

print(Fore.WHITE, "garš = Tall")
print("īss = Short (height)")
print("slaids = Slim")
print("resns = Fat")
print("muskuļots = Muscular")
print("blonds = Blonde (hair)")
print("brūni mati = Brown-haired")
print("melni mati = Black-haired")
print("cirtaini mati = Curly Hair")
print("taisni mati = Straight Hair")
print("zilas acis = Blue Eyes")
print("brūnas acis = Brown Eyes")
print("zaļas acis = Green Eyes")
print("skaists = Beautiful")
print("izskatīgs = Handsome")
print("neglīts = Ugly")
print("jauns = Young")
print("vecs = Old")
print("bārda = Beard")
print("gaiša āda = Light-skinned")
print("tumša āda = Dark-skinned")
print("vasaras raibumi = Freckles")
print("krunkas = Wrinkles")
print("kails = Bald")
print("spalvains = Hairy (body)")
print("taisns deguns = Straight Nose")
print("liels deguns = Big Nose")
print("mazs deguns = Small Nose")
print("plānas lūpas = Thin Lips")
print("pilnas lūpas = Full Lips")
print("plati pleci = Broad Shoulders")
print("šauri pleci = Narrow Shoulders")
print("iedegusi āda = Tanned Skin")
print("bāla āda = Pale Skin")
print("viļņaini mati = Wavy Hair")
print("zirgaste = Ponytail")
print("bizītes = Braids")
print("bārda un ūsas = Beard and Mustache")

print(Fore.RED,"Lesson  16 - Occupations")

print(Fore.WHITE, "ārsts = Doctor")
print("skolotājs = Teacher")
print("inženieris = Engineer")
print("jurists = Lawyer")
print("pārdevējs = Salesperson")
print("policists = Police Officer")
print("ugunsdzēsējs = Firefighter")
print("programmētājs = Programmer")
print("pavārs = Cook/Chef")
print("žurnālists = Journalist")
print("medmāsa = Nurse")
print("arhitekts = Architect")
print("grāmatvedis = Accountant")
print("farmaceits = Pharmacist")
print("vadītājs = Driver")
print("mehāniķis = Mechanic")
print("zinātnieks = Scientist")
print("zobārsts = Dentist")
print("mūziķis = Musician")
print("aktieris = Actor")
print("mākslinieks = Artist")
print("pilots = Pilot")
print("zemnieks = Farmer")
print("fotogrāfs = Photographer")
print("viesmīlis = Waiter/Waitress")

print(Fore.RED,"Lesson 17 - Sports")

print(Fore.WHITE, "futbols = Football / Soccer")
print("basketbols = Basketball")
print("volejbols = Volleyball")
print("teniss = Tennis")
print("peldēšana = Swimming")
print("skriešana / vieglatlētika = Running / Athletics")
print("hokejs = Ice Hockey")
print("slēpošana = Skiing")
print("riteņbraukšana = Cycling")
print("bokss = Boxing")
print("cīņas mākslas = Martial Arts")
print("golfs = Golf")
print("galda teniss = Table Tennis")
print("cīņa = Wrestling")
print("handbols = Handball")
print("beisbols = Baseball")
print("sērfošana = Surfing")
print("slidošana = Skating")
print("jāšana = Horse Riding")
print("lēkšana ūdenī = Diving")
print("krikets = Cricket")
print("regbijs = Rugby")
print("balets = Ballet")
print("boulinga = Bowling")
print("svarcelšana = Weightlifting")
print("vindsērfings = Windsurfing")
print("slidošana = Ice Skating")
print("akadēmiskais airēšana = Rowing")
print("loka šaušana = Archery")
print("kāpšana = Climbing")

print(Fore.RED,"Lesson 18 - Numbers 51-75") 

print(Fore.WHITE, "	piecdesmit viens = 51")
print("piecdesmit divi = 52")
print("piecdesmit trīs = 53")
print("piecdesmit četri = 54")
print("piecdesmit pieci = 55")
print("piecdesmit seši = 56")
print("piecdesmit septiņi = 57")
print("piecdesmit astoņi = 58")
print("piecdesmit deviņi = 59")
print("sešdesmit = 60")
print("sešdesmit viens = 61")
print("sešdesmit divi = 62")
print("sešdesmit trīs = 63")
print("sešdesmit četri = 64")
print("sešdesmit pieci = 65")
print("sešdesmit seši = 66")
print("sešdesmit septiņi = 67")
print("sešdesmit astoņi = 68")
print("sešdesmit deviņi = 69")
print("septiņdesmit = 70")
print("septiņdesmit viens = 71")
print("septiņdesmit divi = 72")
print("septiņdesmit trīs = 73")
print("septiņdesmit četri = 74")
print("septiņdesmit pieci = 75")

print(Fore.RED,"Lesson 19 - Clothing")

print(Fore.WHITE, "krekls = Shirt")
print("T-krekls = T-shirt")
print("blūze = Blouse")
print("džemperis = Sweater / Jumper")
print("jaka = Jacket")
print("mētelis = Coat")
print("kleita = Dress")
print("svārki = Skirt (plural)")
print("bikses = Pants / Trousers (plural)")
print("šorti = Shorts (plural)")
print("kurpes = Shoes (plural)")
print("zābaki = Boots (plural)")
print("kedas = Sneakers (plural)")
print("sandales = Sandals (plural)")
print("cepure = Hat / Cap")
print("šalle = Scarf")
print("cimdi = Gloves (plural)")
print("josta = Belt")
print("zeķes = Socks (plural)")
print("ziemas mētelis = Winter Coat")
print("vilnas cepure = Wool Hat")
print("šalle = Scarf")
print("cimdi = Gloves")
print("sniega zābaki = Snow Boots")
print("peldkostīms = Swimsuit")
print("saulesbrilles = Sunglasses")
print("iešļūcenes = Flip-flops")
print("šorti = Shorts")
print("tops = Tank Top")
print("uzvalks = Suit")
print("kaklasaite = Tie")
print("žakete = Blazer")
print("augstpapēžu kurpes = High Heels")
print("vakarkleita = Evening Dress")
print("melns = Black")
print("balts = White")
print("sarkans = Red")
print("zils = Blue")
print("zaļš = Green")
print("kokvilna = Cotton")
print("vilna = Wool")
print("āda = Leather")
print("zīds = Silk")
print("lina = Linen")

print(Fore.RED,"Lesson 20 - Avderbs")

print(Fore.WHITE, "ātri = quickly")
print("lēnām = slowly")
print("vienmēr = always")
print("nekad = never")
print("bieži = often")
print("dažreiz = sometimes")
print("reti = rarely")
print("jau = already")
print("vēl joprojām = still")
print("vēl = yet")
print("drīz = soon")
print("tagad = now")
print("vēlāk = later")
print("šodien = today")
print("rīt = tomorrow")
print("vakar = yesterday")
print("skaidri = clearly")
print("kopā = together")
print("šķirti = apart")
print("uz visiem laikiem = forever")

print(Fore.RED,"Lesson 21 - Animals")

print(Fore.WHITE, "suns = dog")
print("kaķis = cat")
print("zirgs = horse")
print("govs = cow")
print("aita = sheep")
print("cūka = pig")
print("kaza = goat")
print("vista = chicken")
print("pīle = duck")
print("putns = bird")
print("trušs = rabbit")
print("pele = mouse")
print("lauva = lion")
print("tīģeris = tiger")
print("lācis = bear")
print("zilonis = elephant")
print("pērtiķis = monkey")
print("lapsa = fox")
print("vilks = wolf")
print("brieži = deer")

print(Fore.RED,"Lesson 22 - Place in town")

print(Fore.WHITE, "skola = school")
print("slimnīca = hospital")
print("banka = bank")
print("restorāns = restaurant")
print("bibliotēka = library")
print("lielveikals = supermarket")
print("kinoteātris = cinema")
print("pasta nodaļa = post office")
print("policijas iecirknis = police station")
print("parks = park")
print("muzejs =  museum")
print("teātris = theatre")
print("viesnīca = hotel")
print("stadions = stadium")
print("baznīca = church")
print("aptieka = pharmacy")
print("maiznīca = bakery")
print("gaļas veikals = butcher")
print("tirgus = market")
print("frizieris = hairdresser")

print(Fore.RED,"Lesson 23 - School Supplies")

print(Fore.WHITE, "Baltā tāfele = whiteboard")
print("Krausts = compass")
print("Tratraktors = protractor")
print("Segmašīna = binder")
print("Pildspalvu turētājs = pen holder")
print("Piezīmju lapiņas = sticky notes")
print("Projektors = projector")
print("Tāfele = chalkboard")
print("Skolas soma = schoolbag")
print("Platforma = clipboard")
print("Perforators = hole punch")
print("Lente = tape")
print("Skavotājs = stapler")
print("Klēpjdators = laptop")
print("Printeris = printer")

print(Fore.RED,"Lesson 24 - Transportation")

print(Fore.WHITE, "automašīna = car")
print("autobuss = bus")
print("vilciens = train")
print("velosipēds = bicycle")
print("motocikls = motorcycle")
print("lidmašīna = airplane")
print("laiva = boat")
print("tramvajs = tram")
print("taksometrs = taxi")
print("metro = subway")
print("prāmis = ferry")
print("jahta = yacht")
print("gaisa balons = hot air balloon")
print("kosmosa kuģis = spaceship")
print("rikša = rickshaw")
print("gondola = gondola")
print("cepelīns = zeppelin")
print("skrituļslidas = rollerblades")
print("kanoe laiva = canoe")
print("zemūdene = submarine")

print(Fore.BLUE,"Lesson 25 - Numbers 76 - 110")

print(Fore.RED,"Lesson 26 - ")
print(Fore.WHITE)

