import keyboard

import colorama
from colorama import Fore, init
init()
print(Fore.RED,"1'den 10' a Sayılar")
print(Fore.WHITE,"viens =?, divi =?, tris =?, cetri =?, pieci =?, sesi =?, septini =?, ostoni =?, devini =?, desmit =?")
print("Devam etmek için spacebar'a basınız.")
keyboard.wait("space")
print("")

mesaj = "Karşılık gelen rakamları giriniz:"

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")

viensn  = input(mesaj)
divi    = input(mesaj)
trīs    = input(mesaj)
četri   = input(mesaj)
pieci   = input(mesaj)
seši    = input(mesaj)
septiņi = input(mesaj)
astoņi  = input(mesaj)
deviņi  = input(mesaj)
desmit  = input(mesaj)

print("viensn = 1, divi = 2, trīs = 3, četri = 4, pieci = 5, seši = 6, septiņi = 7, astoņi = 8, deviņi = 9, desmit = 10")

print(Fore.RED, "Lesson 2 - Greetings")
print("")

print(Fore.WHITE, "Sveiki = Hello")
print("Ka jums klajas ? = How are you?")
print("Prieks iepazities = Nice to meet you")
print("Tiksimies rit = See you tomorrow")
print("Labrit = Good morning")
print("Labdien = Good afternoon")
print("Labrakar = Good evening")
print("Ar labu nakti = Good night")
print("Kads ir jusu vards ?  = What is your name ?")
print("Mani sauc ____ = My name is ___")
print("Kur tu dzivo ? = Where do you live?")
print("No kurienes jus esat ? = Where are you from?")
print("Patikami jus redzet = Nice to see you")
print("Novelu jums jauku dienu = Have a nice day")
print("Tiksimies velak = See you later")
print("UZ redzesanos = Goodbye")
print("Ludzu = Please")
print("Paldies = Thank you")


print(Fore.RED, "Lesson 3 - Regular Verbs")
print("")

print(Fore.WHITE, "darīt = to do / make")
print("ēst = to eat")
print("mācīties = to learn (by studying)")
print("gribēt = to want")
print("sākt = to begin / start")
print("zināt = to know")
print("dzīvot = to live (reside)")
print("domāt = to think")
print("redzēt = to see")
print("lasīt = to read")
print("rakstīt = to write")
print("pirkt = to buy")
print("dzert = to drink")
print("strādāt = to work")
print("veseļoties = to recover (get well)")
print("gulēt = to sleep")
print("saprast = to understand")
print("gaidīt = to wait")
print("krist = to fall")
print("sacīt = to tell / say")
print("skatīties = to look / watch")
print("jautāt = to ask")
print("atrast = to find")
print("sēdēt = to sit")
print("zvanīt = to phone / call")
print("palīdzēt = to help")
print("ticēt = to believe")
print("aizmirst = to forget")
print("atbildēt = to answer")
print("spēlēt = to play")
print("ņemt = to take")
print("skriet = to run")
print("apskatīt = to look over / view")
print("satikt = to meet")
print("patikt = to like")
print("dziedāt = to sing")
print("mēģināt = to try / attempt")
print("beigt = to finish / end")
print("mācīt = to teach")