import keyboard

import colorama
from colorama import Fore, init
init()
print(Fore.RED,"1'den 10' a Sayılar")
print(Fore.WHITE,"jeden =?, dwa =?, trzy =?, cztery =?, piec =?, szesc =?, siedem =?, osiem =?, dziewiec =?, dziesiec =?")
print("")
print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")
mesaj = "Karşılık gelen rakamları giriniz:"

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")
jeden     = input(mesaj)
dwa       = input(mesaj)
trzy      = input(mesaj)
cztery    = input(mesaj)
piec      = input(mesaj)
szesc     = input(mesaj)
siedem    = input(mesaj)
osiem     = input(mesaj)
dziewiec  = input(mesaj)
deziesiec = input(mesaj)
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")
print("jeden = 1, dwa = 2, trzy = 3, cztery = 4, pięć = 5, sześć = 6, siedem = 7, osiem = 8, dziewięć = 9, dziesięć = 10")


print(Fore.RED, "Lesson 2 - Greeting")
print("")
print(Fore.WHITE,"Czesc = Hello")
print("Jak sie masz = How are you?")
print("Milo cie poznac = Nice to meet you")
print("Do zobaczenia jutro = See you tomorrow")
print("Dzien dobry = Good morning")
print("Dzien dobry = Good afternoon")
print("Dobry wieczor = Good evening")
print("Dobranoc = Good night")
print("Kaj masz na imic ? = What is your name ?")
print("Nazywam sie ____ = My name is ___")
print("Gdzie mieszkasz ? = Where do you live?")
print("Skad pochodzisz ? = Where are you from?")
print("Milo cie widziec = Nice to see you")
print("Milego dnia = Have a nice day")
print("Do zobaczenia = See you later")
print("Do widzenia = Goodbye")
print("Prosze = Please")
print("Dziekuje = Thank you")

print(Fore.RED, "Lesson_3 = Regular Verbs,")

print(Fore.WHITE,"Regular verbs are divided into 5 categories")

print(Fore.BLUE, "1. -AĆ Verbs")

print(Fore.WHITE, "czytać = to read")
print("kochać = to love")
print("oglądać	= to watch")
print("grać = to play")
print("tańczyć	= to dance")
print("mieszkać = to live")
print("słuchać	= to listen")
print("płakać = to cry")
print("czekać = to wait")
print("pytać = to ask")
print("jechać = to go/ride")
print("pchać = to push")
print("ciągać = to drag")
print("łapać = to catch")
print("dmuchać = to blow")

print(Fore.BLUE, "2. -YĆ SIĘ Verbs")

print(Fore.WHITE, "uczyć się = to learn")
print("cieszyć się = to be happy")
print("martwić się = to worry")
print("śmiać się = to laugh")
print("nudzić się = to be bored")
print("golić się = to shave")
print("kąpać się = to bathe")
print("czesać się = to comb")
print("ubierać się = to dress")
print("spieszyć się = to hurry")

print(Fore.BLUE, "3. -EĆ Verbs")

print(Fore.WHITE, "myśleć = to think")
print("liczyć = to count")
print("siedzieć = to sit")
print("widzieć = to see")
print("sądzić = to judge")
print("boleć = to hurt")
print("zawodzić = to fail")
print("krzyczeć = to shout")
print("płowieć = to fade")
print("drżeć = to tremble")

print(Fore.BLUE, "4. -IĆ Verbs")

print(Fore.WHITE, "mówić = to speak")
print("robić = to do")
print("chodzić = to walk")
print("nosić = to wear")
print("kończyć = to finish")
print("prosić = to request")
print("karmić = to feed")
print("obudzić = to wake up")
print("wpuścić = to let in")
print("głosić = to announce")

print(Fore.BLUE, "5. -OWAĆ Verbs")

print(Fore.WHITE, "pracować = to work")
print("gotować = to cook")
print("telefonować = to phone")
print("dziękować = to thank")
print("studiować = to study")
print("ratować = to rescue")
print("malować = to paint")
print("kupować = to buy")
print("planować = to plan")
print("organizować = to organize")

print("Lesson 3.1 - Present Tense")           

print("I = Ja")
print("you = Pan")
print("he/she = on/ona")
print("we = my")
print("you = wy")
print("they = oni")

print("Example for czytać = to read\n, mówić = to speak\n, uczyć się = to learn\n, myśleć = to think\n, pracować = to work")

print("1. Example = czytac\n, ją czytam\n, Pan czytasz\n, On/Ona czyta\n, My czytamy\n, Wy czytacie?n, Oni czyta\n")

print("2. Examle = momic\n, Ja mówię\n, Pan mówisz\n, On/ona mówi\n, My mówimy\n, Wy mówicie\n, Oni mówią\n")

print("3. exapmle = uczyc sie\n, Ja uczę się\n,	Pan uczysz się\n, On/ona uczy się\n, My uczymy się\n, Wy uczycie się\n, Oni uczą się\n")

print("4. example = mysiec\n, ja myślę\n, Pan myślisz\n, On/oni myśli\n, My myślimy\n, Wy myślicie\n, Oni myślą\n")

print("5. Example = Pracowac\n, Ja pracuję\n, Pan pracujesz\n, On/ona pracuje\n, My pracujemy\n, Wy pracujecie\n, Oni pracują\n")

print(Fore.BLUE, "Lesson 4 = Adjectives")

print(Fore.WHITE, "Szczęśliwy = Happy")
print("Smutny = Sad")
print("Zły = Angry")
print("Przestraszony = Afraid")
print("Radość = Joy")
print("Zaskoczony = Surprised")
print("Spokojny = Calm")
print("Znudzony = Bored")
print("Łatwy = Easy")
print("Trudny = Difficult")
print("Zły = Bad")
print("Dobry = Good")
print("Hałaśliwy = Noisy") 
print("Cichy = Quiet")
print("Silny = Strong")
print("Słaby = Weak")
print("Twardy = Hard")
print("Miękki = Soft")
print("Więcej = More")
print("Mniej = Less") 
print("Czysty = Clean")
print("Brudny = Dirty")
print("Stary = Old")
print("Nowy = New")
print("Duży = Big")
print("Mały = Small")
print("Młody = Young")
print("Stary = Old")
print("Chudy = Skinny")
print("Gruby = Fat")
print("Ładny = Pretty")
print("Brzydki = Ugly")
print("Gruby = Thick")
print("Cienki  =Thin")
print("Szorstki = Rough")
print("Gładki = Smooth")


print(Fore.RED, "Lesson 5 - Days and Months")

print(Fore.BLUE,"Lesson 5.1 - Days of the week")
print("")

print(Fore.WHITE, "Dni tygodnia  The days of the week")
print("Dzień = Day")
print("Tydzień = Week")
print("Poniedziałek = Monday")
print("Tuesday = Wtorek")
print("Środa = Wednesday")
print("Czwartek = Thursday")
print("Piątek = Friday")
print("Sobota = Saturday")
print("Niedziela = Sunday")
print("Weekend = Weekend")
      

print(Fore.BLUE,"Lesson 5.2 - Months of the year")
print("")

print(Fore.WHITE, "The months of the year = Miesiące w roku") 
print("Miesiąc = Month")
print("Rok = Year")
print("Styczeń = January")
print("February = Luty")
print("Marzec = March")
print("Kwiecień = April")
print("Maj = May")
print("Czerwiec = June")
print("Lipiec = July")
print("Sierpień = August")
print("Wrzesień = September")
print("Październik = October")
print("Listopad = November")
print("Grudzień = December")
      
print(Fore.RED,"Lesson 6 - Seasons and Weathers")
print("")

print(Fore.WHITE, "Pory roku = Seasons")
print("Zima = Winter")
print("Lato = Summer")
print("Wiosna = Spring")
print("Jesień = Autumn")
print("Niebo = Sky")
print("Chmura = Cloud")
print("Tęcza = Rainbow")
print("Zimno = Cold (weather)")
print("Gorąco = Hot (weather)")
print("Jest gorąco = It is hot")
print("Jest zimno = It is cold")
print("Jest słonecznie = It is sunny")
print("Jest pochmurnie = It is cloudy")
print("Jest wilgotnie = It is humid")
print("Pada deszcz = It is raining")
print("Pada śnieg = It is snowing")
print("Jest wietrznie = It is windy")
print("Jaka jest pogoda? = How is the weather?")
print("Dobra pogoda = Good weather")
print("Zła pogoda = Bad weather")
print("Jaka jest temperatura? = What is the temperature?")
print("Mamy 24 stopnie = It is 24 degrees")

print(Fore.RED,"Lesson 7 - Colors")
print("")

print(Fore.WHITE, "Czarny = Black")
print("Niebieski = Blue")
print("Brązowy = Brown")
print("Zielony = Green")
print("Pomarańczowy = Orange")
print("Fioletowy = Purple")
print("Czerwony = Red")
print("Biały = White")
print("Żółty = Yellow")
print("Szary = Gray")
print("Złoty = Gold")
print("Srebrny = Silver")
print("Jaki to kolor = What color is it?")
print("Ten kolor to __ = The color is ___")
      
print(Fore.RED,"Lesson 8 - Family and Friendsa")
print("")

print(Fore.BLUE,"Lesson 8.1 - Family members")
print("")

print(Fore.WHITE, "Matka = Mother")
print("Ojciec = Father")
print("Brat = Brother")
print("Siostra = Sister")
print("Syn = Son")
print("Córka = Daughter")
print("Rodzice = Parents")
print("Dzieci = Children")
print("Dziecko = Child")
print("Macocha = Stepmother")
print("Ojczym = Stepfather")
print("Siostra przyrodnia = Stepsister")
print("Brat przyrodni = Stepbrother")
print("Zięć = Son-in-law")
print("Synowa = Daughter-in-law")
print("Żona = Wife")
print("Mąż = Husband")
print("Dziadkowie = Grandparents")
print("Dziadek = Grandfather")
print("Babcia = Grandmother")
print("Wnuczek = Grandson")
print("Wnuczka = Granddaughter")
print("Wnuki = Grandchildren")
print("Wnuk = Grandchild")
print("Ciotka = Aunt")
print("Wujek = Uncle")
print("Kuzynka = Cousin (female)")
print("Kuzyn = Cousin (male)")
print("Siostrzeniec = Nephew")
print("Siostrzenica = Niece")
print("Teść = Father-in-law")
print("Teściowa = Mother-in-law")
print("Szwagier = Brother-in-law")
print("Szwagierka = Sister-in-law")
print("Krewny = Relative")

print(Fore.BLUE,"Lesson 8.2 - Friends")
print("")

print(Fore.WHITE, "Pan = Mr")
print("Pani = Mrs")
print("Panna = Miss")
print("Chłopak = Boy")
print("Dziewczyna = Girl")
print("Niemowlę = Baby")
print("Kobieta = Woman")
print("Mężczyzna = Man")
print("Przyjaciel = Friend (male)")
print("Przyjaciółka = Friend (female)")
print("Chłopak = Boyfriend")
print("Dziewczyna = Girlfriend")
print("Dżentelmen = Gentleman")
print("Dama = Lady")
print("Sąsiad = Neighbor (male)")
print("Sąsiadka = Neighbor (female)")

print(Fore.BLUE,"Lesson 9 - Numbers from 11 to 30")
print("")

print(Fore.WHITE, "Jedenaście = 11")
print("Dwanaście = 12")
print("Trzynaście = 13")
print("Czternaście = 14")
print("Piętnaście = 15")
print("Szesnaście = 16")
print("Siedemnaście = 17")
print("Osiemnaście = 18")
print("Dziewiętnaście = 19")
print("Dwadzieścia = 20")
print("Dwadzieścia jeden = 21")
print("Dwadzieścia dwa = 22")
print("Dwadzieścia trzy = 23")
print("Dwadzieścia cztery = 24")
print("Dwadzieścia pięć = 25")
print("Dwadzieścia sześć = 26")
print("Dwadzieścia siedem = 27")
print("Dwadzieścia osiem = 28")
print("Dwadzieścia dziewięć = 29")
print("Trzydzieści = 30")