import keyboard

import colorama
from colorama import Fore, init
init()
print(Fore.RED,"1'den 10' a Sayılar")
print(Fore.WHITE,"jeden =?, dwa =?, trzy =?, cztery =?, piec =?, szesc =?, siedem =?, osiem =?, dziewiec =?, dziesiec =?")
print("")
print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")
mesaj = "Karşılık gelen rakamları giriniz:"

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")
jeden     = input(mesaj)
dwa       = input(mesaj)
trzy      = input(mesaj)
cztery    = input(mesaj)
piec      = input(mesaj)
szesc     = input(mesaj)
siedem    = input(mesaj)
osiem     = input(mesaj)
dziewiec  = input(mesaj)
deziesiec = input(mesaj)
print("")

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")
print("")
print("jeden = 1, dwa = 2, trzy = 3, cztery = 4, pięć = 5, sześć = 6, siedem = 7, osiem = 8, dziewięć = 9, dziesięć = 10")


print(Fore.RED, "Lesson 2 - Greeting")
print("")
print(Fore.WHITE,"Czesc = Hello")
print("Jak sie masz = How are you?")
print("Milo cie poznac = Nice to meet you")
print("Do zobaczenia jutro = See you tomorrow")
print("Dzien dobry = Good morning")
print("Dzien dobry = Good afternoon")
print("Dobry wieczor = Good evening")
print("Dobranoc = Good night")
print("Kaj masz na imic ? = What is your name ?")
print("Nazywam sie ____ = My name is ___")
print("Gdzie mieszkasz ? = Where do you live?")
print("Skad pochodzisz ? = Where are you from?")
print("Milo cie widziec = Nice to see you")
print("Milego dnia = Have a nice day")
print("Do zobaczenia = See you later")
print("Do widzenia = Goodbye")
print("Prosze = Please")
print("Dziekuje = Thank you")

print(Fore.RED, "Lesson_3 = Regular Verbs,")

print(Fore.WHITE,"Regular verbs are divided into 5 categories")

print(Fore.BLUE, "1. -AĆ Verbs")

print(Fore.WHITE, "czytać = to read")
print("kochać = to love")
print("oglądać	= to watch")
print("grać = to play")
print("tańczyć	= to dance")
print("mieszkać = to live")
print("słuchać	= to listen")
print("płakać = to cry")
print("czekać = to wait")
print("pytać = to ask")
print("jechać = to go/ride")
print("pchać = to push")
print("ciągać = to drag")
print("łapać = to catch")
print("dmuchać = to blow")

print(Fore.BLUE, "2. -YĆ SIĘ Verbs")

print(Fore.WHITE, "uczyć się = to learn")
print("cieszyć się = to be happy")
print("martwić się = to worry")
print("śmiać się = to laugh")
print("nudzić się = to be bored")
print("golić się = to shave")
print("kąpać się = to bathe")
print("czesać się = to comb")
print("ubierać się = to dress")
print("spieszyć się = to hurry")

print(Fore.BLUE, "3. -EĆ Verbs")

print(Fore.WHITE, "myśleć = to think")
print("liczyć = to count")
print("siedzieć = to sit")
print("widzieć = to see")
print("sądzić = to judge")
print("boleć = to hurt")
print("zawodzić = to fail")
print("krzyczeć = to shout")
print("płowieć = to fade")
print("drżeć = to tremble")

print(Fore.BLUE, "4. -IĆ Verbs")

print(Fore.WHITE, "mówić = to speak")
print("robić = to do")
print("chodzić = to walk")
print("nosić = to wear")
print("kończyć = to finish")
print("prosić = to request")
print("karmić = to feed")
print("obudzić = to wake up")
print("wpuścić = to let in")
print("głosić = to announce")

print(Fore.BLUE, "5. -OWAĆ Verbs")

print(Fore.WHITE, "pracować = to work")
print("gotować = to cook")
print("telefonować = to phone")
print("dziękować = to thank")
print("studiować = to study")
print("ratować = to rescue")
print("malować = to paint")
print("kupować = to buy")
print("planować = to plan")
print("organizować = to organize")

print("Lesson 3.1 - Present Tense")           

print("I = Ja")
print("you = Pan")
print("he/she = on/ona")
print("we = my")
print("you = wy")
print("they = oni")

print("Example for czytać = to read\n, mówić = to speak\n, uczyć się = to learn\n, myśleć = to think\n, pracować = to work")

print("1. Example = czytac\n, ją czytam\n, Pan czytasz\n, On/Ona czyta\n, My czytamy\n, Wy czytacie?n, Oni czyta\n")

print("2. Examle = momic\n, Ja mówię\n, Pan mówisz\n, On/ona mówi\n, My mówimy\n, Wy mówicie\n, Oni mówią\n")

print("3. exapmle = uczyc sie\n, Ja uczę się\n,	Pan uczysz się\n, On/ona uczy się\n, My uczymy się\n, Wy uczycie się\n, Oni uczą się\n")

print("4. example = mysiec\n, ja myślę\n, Pan myślisz\n, On/oni myśli\n, My myślimy\n, Wy myślicie\n, Oni myślą\n")

print("5. Example = Pracowac\n, Ja pracuję\n, Pan pracujesz\n, On/ona pracuje\n, My pracujemy\n, Wy pracujecie\n, Oni pracują\n")

print(Fore.BLUE, "Lesson 4 = Adjectives")

print(Fore.WHITE, "Szczęśliwy = Happy")
print("Smutny = Sad")
print("Zły = Angry")
print("Przestraszony = Afraid")
print("Radość = Joy")
print("Zaskoczony = Surprised")
print("Spokojny = Calm")
print("Znudzony = Bored")
print("Łatwy = Easy")
print("Trudny = Difficult")
print("Zły = Bad")
print("Dobry = Good")
print("Hałaśliwy = Noisy") 
print("Cichy = Quiet")
print("Silny = Strong")
print("Słaby = Weak")
print("Twardy = Hard")
print("Miękki = Soft")
print("Więcej = More")
print("Mniej = Less") 
print("Czysty = Clean")
print("Brudny = Dirty")
print("Stary = Old")
print("Nowy = New")
print("Duży = Big")
print("Mały = Small")
print("Młody = Young")
print("Stary = Old")
print("Chudy = Skinny")
print("Gruby = Fat")
print("Ładny = Pretty")
print("Brzydki = Ugly")
print("Gruby = Thick")
print("Cienki  =Thin")
print("Szorstki = Rough")
print("Gładki = Smooth")


print(Fore.RED, "Lesson 5 - Days and Months")

print(Fore.BLUE,"Lesson 5.1 - Days of the week")
print("")

print(Fore.WHITE, "Dni tygodnia  The days of the week")
print("Dzień = Day")
print("Tydzień = Week")
print("Poniedziałek = Monday")
print("Tuesday = Wtorek")
print("Środa = Wednesday")
print("Czwartek = Thursday")
print("Piątek = Friday")
print("Sobota = Saturday")
print("Niedziela = Sunday")
print("Weekend = Weekend")
      

print(Fore.BLUE,"Lesson 5.2 - Months of the year")
print("")

print(Fore.WHITE, "The months of the year = Miesiące w roku") 
print("Miesiąc = Month")
print("Rok = Year")
print("Styczeń = January")
print("February = Luty")
print("Marzec = March")
print("Kwiecień = April")
print("Maj = May")
print("Czerwiec = June")
print("Lipiec = July")
print("Sierpień = August")
print("Wrzesień = September")
print("Październik = October")
print("Listopad = November")
print("Grudzień = December")
      
print(Fore.RED,"Lesson 6 - Seasons and Weathers")
print("")

print(Fore.WHITE, "Pory roku = Seasons")
print("Zima = Winter")
print("Lato = Summer")
print("Wiosna = Spring")
print("Jesień = Autumn")
print("Niebo = Sky")
print("Chmura = Cloud")
print("Tęcza = Rainbow")
print("Zimno = Cold (weather)")
print("Gorąco = Hot (weather)")
print("Jest gorąco = It is hot")
print("Jest zimno = It is cold")
print("Jest słonecznie = It is sunny")
print("Jest pochmurnie = It is cloudy")
print("Jest wilgotnie = It is humid")
print("Pada deszcz = It is raining")
print("Pada śnieg = It is snowing")
print("Jest wietrznie = It is windy")
print("Jaka jest pogoda? = How is the weather?")
print("Dobra pogoda = Good weather")
print("Zła pogoda = Bad weather")
print("Jaka jest temperatura? = What is the temperature?")
print("Mamy 24 stopnie = It is 24 degrees")

print(Fore.RED,"Lesson 7 - Colors")
print("")

print(Fore.WHITE, "Czarny = Black")
print("Niebieski = Blue")
print("Brązowy = Brown")
print("Zielony = Green")
print("Pomarańczowy = Orange")
print("Fioletowy = Purple")
print("Czerwony = Red")
print("Biały = White")
print("Żółty = Yellow")
print("Szary = Gray")
print("Złoty = Gold")
print("Srebrny = Silver")
print("Jaki to kolor = What color is it?")
print("Ten kolor to __ = The color is ___")
      
print(Fore.RED,"Lesson 8 - Family and Friendsa")
print("")

print(Fore.BLUE,"Lesson 8.1 - Family members")
print("")

print(Fore.WHITE, "Matka = Mother")
print("Ojciec = Father")
print("Brat = Brother")
print("Siostra = Sister")
print("Syn = Son")
print("Córka = Daughter")
print("Rodzice = Parents")
print("Dzieci = Children")
print("Dziecko = Child")
print("Macocha = Stepmother")
print("Ojczym = Stepfather")
print("Siostra przyrodnia = Stepsister")
print("Brat przyrodni = Stepbrother")
print("Zięć = Son-in-law")
print("Synowa = Daughter-in-law")
print("Żona = Wife")
print("Mąż = Husband")
print("Dziadkowie = Grandparents")
print("Dziadek = Grandfather")
print("Babcia = Grandmother")
print("Wnuczek = Grandson")
print("Wnuczka = Granddaughter")
print("Wnuki = Grandchildren")
print("Wnuk = Grandchild")
print("Ciotka = Aunt")
print("Wujek = Uncle")
print("Kuzynka = Cousin (female)")
print("Kuzyn = Cousin (male)")
print("Siostrzeniec = Nephew")
print("Siostrzenica = Niece")
print("Teść = Father-in-law")
print("Teściowa = Mother-in-law")
print("Szwagier = Brother-in-law")
print("Szwagierka = Sister-in-law")
print("Krewny = Relative")

print(Fore.BLUE,"Lesson 8.2 - Friends")
print("")

print(Fore.WHITE, "Pan = Mr")
print("Pani = Mrs")
print("Panna = Miss")
print("Chłopak = Boy")
print("Dziewczyna = Girl")
print("Niemowlę = Baby")
print("Kobieta = Woman")
print("Mężczyzna = Man")
print("Przyjaciel = Friend (male)")
print("Przyjaciółka = Friend (female)")
print("Chłopak = Boyfriend")
print("Dziewczyna = Girlfriend")
print("Dżentelmen = Gentleman")
print("Dama = Lady")
print("Sąsiad = Neighbor (male)")
print("Sąsiadka = Neighbor (female)")

print(Fore.BLUE,"Lesson 9 - Numbers from 11 to 30")
print("")

print(Fore.WHITE, "Jedenaście = 11")
print("Dwanaście = 12")
print("Trzynaście = 13")
print("Czternaście = 14")
print("Piętnaście = 15")
print("Szesnaście = 16")
print("Siedemnaście = 17")
print("Osiemnaście = 18")
print("Dziewiętnaście = 19")
print("Dwadzieścia = 20")
print("Dwadzieścia jeden = 21")
print("Dwadzieścia dwa = 22")
print("Dwadzieścia trzy = 23")
print("Dwadzieścia cztery = 24")
print("Dwadzieścia pięć = 25")
print("Dwadzieścia sześć = 26")
print("Dwadzieścia siedem = 27")
print("Dwadzieścia osiem = 28")
print("Dwadzieścia dziewięć = 29")
print("Trzydzieści = 30")

print(Fore.RED,"Lesson 10 - Prepositions and Useful words")
print("")

print(Fore.BLUE,"Lesson 10.1 - Prepositions")
print("")

print(Fore.WHITE, "Dla = For")
print("Od 0 From")
print("W = In")
print("Wewnątrz = Inside")
print("W = Into")
print("Blisko = Near")
print("Z = Of")
print("Z = Out")
print("Na zewnątrz = Outside")
print("Do = To")
print("Pod = Under")
print("Z = With")
print("Bez = Without")
print("Nad = Above")
print("Po drugiej stronie = Across")
print("Po = After")
print("Pod = Against")
print("Wzdłuż = Along")
print("Wokół = Around")
print("W = At")
print("Za = Behind")
print("Pod = Below")
print("Obok = Beside")
print("Między = Between")
print("Przy = By")
print("Podczas = During")
print("Oprócz = Except")
print("I = And")
print("Ponieważ = Because")
print("Ale = But")
print("Lub = Or")
print("Wszędzie = Everywhere")
print("Wszyscy = Everyone")
print("Wszystko = Everything")
print("Mało = Few")
print("Niektóre = Some")
print("Wiele = Many")


print(Fore.BLUE,"Lesson 10.2 - Useful Words")
print("")

print(Fore.WHITE, "Pytanie = Question")
print("Odpowiedź = Answer")
print("Prawda = Truth")
print("Kłamstwo = Lie")
print("Nic = Nothing")
print("Coś = Something")
print("Tak samo = Same")
print("Inny = Different")
print("Ciągnąć = Pull")
print("Pchać = Push")
print("Długi = Long")
print("Krótki = Short")
print("Zimno = Cold")
print("Gorąco = Hot")
print("Jasny = Light")
print("Ciemny = Dark")
print("Mokro = Wet")
print("Sucho = Dry")
print("Pusty = Empty")
print("Pełny = Full")
print("Jak? = How?")
print("Co? = What?")
print("Kiedy? = When?")
print("Gdzie? = Where?")
print("Która? = Which?")
print("Kto? = Who?")
print("Dlaczego? = Why?")
print("Jak długo? = How long?")
print("Ile? = How much?")


print(Fore.RED,"Lesson 11 - Drinks and Meals")

print(Fore.BLUE,"Lesson 11.1 - Drinks")

print(Fore.WHITE, "Kawa = Coffee")
print("Herbata = Tea")
print("Napój gazowany = Soft drink")
print("Woda = Water")
print("Lemoniada = Lemonade")
print("Sok = Juice")
print("Sok pomarańczowy = Orange juice")
print("Poproszę o szklankę wody = I would like a glass of water please")
print("Z lodem = With ice")

print(Fore.BLUE,"Lesson 11.2 - Dairy Products")
print(Fore.WHITE, "Mleko = Milk")
print("Lody = Ice cream")
print("Masło = Butter")
print("Ser = Cheese")
print("Twarożek = Cottage cheese")
print("Śmietana = Cream")
print("Kwaśna śmietana = Sour cream")
print("Jogurt = Yogurt")
print("Jajka = Eggs")
print("Bita śmietana = Whipping cream")
print("Piekarnia = Bakery")
print("Bagietka = Baguette")
print("Pączek = Doughnut")
print("Ciastko = Cookie")
print("Bułka = Roll")
print("Deser = Dessert")
print("Ciasto = Cake")
print("Chleb = Bread")
print("Placek = Pie")

print(Fore.BLUE,"Lesson 11.3 - Meats")

print(Fore.WHITE, "Wołowina = Beef")
print("Cielęcina = Veal")
print("Szynka = Ham")
print("Kurczak = Chicken")
print("Indyk = Turkey")
print("Kaczka = Duck")
print("Boczek = Bacon")
print("Wieprzowina = Pork")
print("Filet z polędwicy = Filet mignon")
print("Kiełbasa = Sausage")
print("Kotlet z jagnięciny = Lamb chop")
print("Kotlet schabowy = Pork chop")
print("Mięso = Meat")

print(Fore.BLUE,"Lesson 11.4 - Seafoods")

print(Fore.WHITE, "Ryba = Fish")
print("Skorupiak = Shellfish")
print("Okoń = Bass")
print("Łosoś = Salmon")
print("Homar = Lobster")
print("Krab = Crab")
print("Małże = Mussel")
print("Ostryga = Oyster")
print("Dorsz = Cod")
print("Małż = Clam")
print("Krewetka = Shrimp")
print("Tuńczyk = Tuna")
print("Pstrąg = Trout")
print("Sola = Sole")
print("Rekin = Shark")
print("Karp = Carp")
print("Tilapia = Tilapia")
print("Węgorz = Eel")
print("Sum = Catfish")
print("Miecznik = Swordfish")

print(Fore.BLUE,"Lesson 11.5 - Herbs and Spices")

print(Fore.WHITE, "Sól = Salt")
print("Pieprz = Pepper")
print("Kminek = Caraway")
print("Czosnek = Garlic")
print("Bazylia = Basil")
print("Kolendra = Coriander")
print("Fenkuł = Fennel")
print("Majeranek = Marjoram")
print("Oregano = Oregano")
print("Pietruszka = Parsley")
print("Rozmaryn = Rosemary")
print("Szałwia = Sage")
print("Tymianek = Thyme")
print("Gałka muszkatołowa = Nutmeg")
print("Papryka = Paprika")
print("Pieprz cayenne = Cayenne")
print("Imbir = Ginger")

print(Fore.BLUE,"Lesson 11.6 - Vegetables")

print(Fore.WHITE, "Seler = Celery")
print("Bakłażan = Eggplant")
print("Cukinia = Zucchini")
print("Cebula = Onion")
print("Szpinak = Spinach")
print("Sałatka = Salad")
print("Zielona fasola = Green beans")
print("Ogórek = Cucumber")
print("Rzodkiewka = Radish")
print("Kapusta = Cabbage")
print("Grzyby = Mushrooms")
print("Sałata = Lettuce")
print("Kukurydza = Corn")
print("Ziemniaki = Potatoes")
print("Pomidor = Tomato")
print("Marchew = Carrot")
print("Banan = Plantain")
print("Fasola = Beans")
print("Por = Leek")
print("Korzeń lotosu = Lotus root")
print("Pędy bambusa = Bamboo shoot")
print("Karczoch = Artichoke")
print("Szparag = Asparagus")
print("Brukselka = Brussels sprouts")
print("Brokuły = Broccoli")
print("Groszek = Peas")
print("Kalafior = Cauliflower")
print("Papryka chili = Chili pepper")

print(Fore.BLUE,"Lesson 11.7 - Fruits")

print(Fore.WHITE, "Wiśnie = Cherries")
print("Maliny = Raspberries")
print("Jagody = Blueberries")
print("Truskawki = Strawberries")
print("Cytryna = Lemon")
print("Limonka = Lime")
print("Jabłko = Apple")
print("Pomarańcza = Orange")
print("Gruszka = Pear")
print("Banan = Banana")
print("Winogrona = Grapes")
print("Grejpfrut = Grapefruit")
print("Arbuz = Watermelon")
print("Ananas = Pineapple")
print("Śliwka = Plum")
print("Brzoskwinia = Peach")
print("Mango = Mango")
print("Morela = Apricot")
print("Granat = Pomegranate")
print("Persymona = Persimmon")
print("Kiwi = Kiwi")
print("Liczi = Litchi")
print("Longan = Longan")
print("Przepękla ogórkowata = Balsam pear")
print("Marakuja = Passion fruit")
print("Awokado = Avocado")
print("Orzech kokosowy = Coconut")


print(Fore.RED,"Lesson 12 - Irregular Verbs")

print(Fore.WHITE, "być = to be")
print("mieć = to have")
print("iść = to go")
print("przyjść	to come")
print("widzieć	to see")
print("dać	to give")
print("jeść = to eat")
print("pić = to drink")
print("wiedzieć = to know (fact)")
print("chcieć = to want")
print("znaleźć = to find")
print("biec = to run")
print("siedzieć = to sit")
print("leżeć = to lie down")
print("stać = to stand")
print("rozumieć = to understand")
print("powiedzieć = to say")
print("wziąć = to take")
print("pisać = to write")
print("upaść = to fall")
print("zacząć = to begin")
print("złamać = to break")
print("zbudować = to build")
print("wybrać = to choose")
print("robić = to do/make")
print("prowadzić = to drive")
print("zapomnieć = to forget")
print("dostać = to get")
print("słyszeć = to hear")
print("trzymać = to hold")
print("opuścić = to leave")
print("spotkać = to meet")
print("płacić = to pay")
print("położyć = to put")
print("czytać = to read")
print("biec = to run")
print("widzieć = to see")
print("wysłać = to send")
print("spać = to sleep")
print("mówić = to speak")
print("spędzać = to spend (time)")
print("pływać = to swim")
print("uczyć = to teach")
print("opowiedzieć = to tell")
print("myśleć = to think")
print("rzucić = to throw")
print("rozumieć = to understand")
print("wygrać = to win")
print("pisać = to write")
print("przynieść = to bring")


print(Fore.RED,"Lesson 13 - Present Simple")

print(Fore.BLUE, "Example for być = to be, jeść = to eat, iść = to go")

print(Fore.WHITE, "ja jestem - ja jem - ja idę")
print("ty jesteś - ty jesz - ty idziesz")
print("on/ona/ono jest - on/ona je - on/ona/ono idzie")
print("my jesteśmy - my jemy - my idziemy")
print("wy jesteście - wy jecie - wy idziecie")
print("oni/one są - oni/one jedzą - oni/one idą")

print(Fore.RED,"Lesson 14 - Numbers from 31-50")

print(Fore.WHITE, "trzydzieści jeden = 31")
print("trzydzieści dwa = 32")
print("trzydzieści trzy = 33")
print("trzydzieści cztery = 34")
print("trzydzieści pięć = 35")
print("trzydzieści sześć = 36")
print("trzydzieści siedem = 37")
print("trzydzieści osiem = 38")
print("trzydzieści dziewięć = 39")
print("czterdzieści = 40")
print("czterdzieści jeden = 41")
print("czterdzieści dwa = 42")
print("czterdzieści trzy = 43")
print("czterdzieści cztery = 44")
print("czterdzieści pięć = 45")
print("czterdzieści sześć = 46")
print("czterdzieści siedem = 47")
print("czterdzieści osiem = 48")
print("czterdzieści dziewięć = 49")
print("pięćdziesiąt = 50")

print(Fore.RED,"Lesson 15 - Physical Appearance")

print(Fore.WHITE, "wysoki = Tall")
print("niski = Short (height)")
print("szczupły = Slim")
print("gruby = Fat")
print("umięśniony = Muscular")
print("blond = Blonde (hair)")
print("brązowe włosy = Brown-haired")
print("czarne włosy = Black-haired")
print("kręcone włosy = Curly Hair")
print("proste włosy = Straight Hair")
print("niebieskie oczy = Blue Eyes")
print("brązowe oczy = Brown Eyes")
print("zielone oczy = Green Eyes")
print("piękny = Beautiful")
print("przystojny = Handsome")
print("brzydki = Ugly")
print("młody = Young")
print("stary = Old")
print("broda = Beard")
print("jasna skóra = Light-skinned")
print("ciemna skóra = Dark-skinned")
print("piegi = Freckles")
print("zmarszczki = Wrinkles")
print("łysy = Bald")
print("owłosiony = Hairy (body)")
print("prosty nos = Straight Nose")
print("duży nos = Big Nose")
print("mały nos = Small Nose")
print("cienkie usta = Thin Lips")
print("pełne usta = Full Lips")
print("szerokie ramiona = Broad Shoulders")
print("wąskie ramiona = Narrow Shoulders")
print("opalona skóra = Tanned Skin")
print("blada skóra = Pale Skin")
print("falowane włosy = Wavy Hair")
print("koński ogon = Ponytail")
print("warkocze = Braids")
print("broda i wąsy = Beard and Mustache")

print(Fore.RED,"Lesson  16 - Occupations")

print(Fore.WHITE, "lekarz = Doctor")
print("nauczyciel = Teacher")
print("inżynier = Engineer")
print("prawnik = Lawyer")
print("sprzedawca = Salesperson")
print("policjant = Police Officer")
print("strażak = Firefighter")
print("programista = Programmer")
print("kucharz = Cook/Chef")
print("dziennikarz = Journalist")
print("pielęgniarka = Nurse")
print("architekt = Architect")
print("księgowy = Accountant")
print("farmaceuta = Pharmacist")
print("kierowca = Driver")
print("mechanik = Mechanic")
print("naukowiec = Scientist")
print("dentysta = Dentist")
print("muzyk = Musician")
print("aktor = Actor")
print("artysta = Artist")
print("pilot = Pilot")
print("rolnik = Farmer")
print("fotograf = Photographer")
print("kelner/kelnerka = Waiter/Waitress")

print(Fore.RED,"Lesson 17 - Sports")

print(Fore.WHITE, "piłka nożna = Football / Soccer")
print("koszykówka = Basketball")
print("siatkówka = Volleyball")
print("tenis = Tennis")
print("pływanie = Swimming")
print("bieganie / lekkoatletyka = Running / Athletics")
print("hokej = Ice Hockey")
print("narciarstwo = Skiing")
print("kolarstwo = Cycling")
print("boks = Boxing")
print("sztuki walki = Martial Arts")
print("golf = Golf")
print("tenis stołowy = Table Tennis")
print("zapasy = Wrestling")
print("piłka ręczna = Handball")
print("baseball = Baseball")
print("surfowanie = Surfing")
print("jazda na łyżwach = Skating")
print("jazda konna = Horse Riding")
print("nurkowanie = Diving")
print("krykiet = Cricket")
print("rugby = Rugby")
print("balet = Ballet")
print("kręgle = Bowling")
print("podnoszenie ciężarów = Weightlifting")
print("windsurfing = Windsurfing")
print("jazda na łyżwach = Ice Skating")
print("wioślarstwo = Rowing")
print("łucznictwo = Archery")
print("wspinaczka = Climbing")

print(Fore.RED,"Lesson 18 - Numbers 51-75")

print(Fore.WHITE, "pięćdziesiąt jeden = 51")
print("pięćdziesiąt dwa = 52")
print("pięćdziesiąt trzy = 53")
print("pięćdziesiąt cztery = 54")
print("pięćdziesiąt pięć = 55")
print("pięćdziesiąt sześć = 56")
print("pięćdziesiąt siedem = 57")
print("pięćdziesiąt osiem = 58")
print("pięćdziesiąt dziewięć = 59")
print("sześćdziesiąt = 60")
print("sześćdziesiąt jeden = 61")
print("sześćdziesiąt dwa = 62")
print("sześćdziesiąt trzy = 63")
print("sześćdziesiąt cztery = 64")
print("sześćdziesiąt pięć = 65")
print("sześćdziesiąt sześć = 66")
print("sześćdziesiąt siedem = 67")
print("sześćdziesiąt osiem = 68")
print("sześćdziesiąt dziewięć = 69")
print("siedemdziesiąt = 70")
print("siedemdziesiąt jeden = 71")
print("siedemdziesiąt dwa = 72")
print("siedemdziesiąt trzy = 73")
print("siedemdziesiąt cztery = 74")
print("siedemdziesiąt pięć = 75")

print(Fore.RED,"Lesson 19 - Clothing")

print(Fore.WHITE, "koszula = Shirt")
print("koszulka = T-shirt")
print("bluzka = Blouse")
print("sweter = Sweater / Jumper")
print("kurtka = Jacket")
print("płaszcz = Coat")
print("sukienka = Dress")
print("spódnica = Skirt")
print("spodnie = Pants / Trousers (plural)")
print("krótkie spodenki = Shorts")
print("buty  = Shoes (plural)")
print("kozaki = Boots (plural)")
print("trampki = Sneakers (plural)")
print("sandały = Sandals (plural)")
print("czapka = Hat / Cap")
print("szalik = Scarf")
print("rękawiczki = Gloves (plural)")
print("pasek = Belt")
print("skarpetki = Socks (plural)")
print("zimowy płaszcz = Winter Coat")
print("wełniana czapka = Wool Hat")
print("szalik = Scarf")
print("rękawiczki = Gloves")
print("buty śniegowe = Snow Boots")
print("kostium kąpielowy = Swimsuit")
print("okulary przeciwsłoneczne = Sunglasses")
print("klapki = Flip-flops")
print("krótkie spodenki = Shorts")
print("top = Tank Top")
print("garnitur = Suit")
print("krawat = Tie")
print("marynarka = Blazer")
print("buty na obcasie = High Heels")
print("suknia wieczorowa = Evening Dress")
print("czarny = Black")
print("biały = White")
print("czerwony = Red")
print("niebieski = Blue")
print("zielony = Green")
print("bawełna = Cotton")
print("wełna = Wool")
print("skóra = Leather")
print("jedwab = Silk")
print("len = Linen")

print(Fore.RED,"Lesson 20 - Adverbs")

print(Fore.WHITE, "szybko = quickly")
print("powoli = slowly")
print("zawsze = always")
print("nigdy = never")
print("często = often")
print("czasami = sometimes")
print("rzadko = rarely")
print("już = already")
print("nadal = still")
print("jeszcze = yet")
print("wkrótce = soon")
print("teraz = now")
print("później = later")
print("dzisiaj = today")
print("jutro = tomorrow")
print("wczoraj = yesterday")
print("wyraźnie = clearly")
print("razem = together")
print("osobno = apart")
print("na zawsze = forever")

print(Fore.RED,"Lesson 21 - Animals")

print(Fore.WHITE, "pies = dog")
print("kot = cat")
print("koń = horse")
print("krowa = cow")
print("owca = sheep")
print("świnia = pig")
print("koza = goat")
print("kurczak = chicken")
print("kaczka = duck")
print("ptak = bird")
print("królik = rabbit")
print("mysz = mouse")
print("lew = lion")
print("tygrys = tiger")
print("niedźwiedź = bear")
print("słoń = elephant")
print("małpa = monkey")
print("lis = fox")
print("wilk = wolf")
print("jeleń = deer")

print(Fore.BLUE,"Lesson 22 - Numbers 76 - 110")

print(Fore.WHITE)

print(Fore.RED,"Lesson 23 - Place in town")

print(Fore.WHITE, "szkoła = school")
print("szpital = hospital")
print("bank = bank")
print("restauracja = restaurant")
print("biblioteka = library")
print("supermarket = supermarket")
print("kino = cinema")
print("poczta = post office")
print("posterunek policji = police station")
print("park = park")
print("muzeum = museum")
print("teatr = theatre")
print("hotel = hotel")
print("stadion = stadium")
print("kościół = church")
print("apteka = pharmacy")
print("piekarnia = bakery")
print("rzeźnik = butcher")
print("targ = market")
print("fryzjer = hairdresser")

print(Fore.RED,"Lesson 24 - School Supplies")

print(Fore.WHITE, "tablica = whiteboard")
print("cyrkiel = compass")
print("kątomierz = protractor")
print("segregator = binder")
print("przybornik = pen holder")
print("karteczki samoprzylepne = sticky notes")
print("rzutnik = projector")
print("tablica kredowa = chalkboard")
print("torba szkolna = schoolbag")
print("podkładka = clipboard")
print("dziurkacz = hole punch")
print("taśma = tape")
print("zszywacz = stapler")
print("laptop = laptop")
print("drukarka = printer")

print(Fore.RED,"Lesson 25 - Transportation")

print(Fore.WHITE, "samochód = car")
print("autobus = bus")
print("pociąg = train")
print("rower = bicycle")
print("motocykl = motorcycle")
print("samolot = airplane")
print("łódź = boat")
print("tramwaj = tram")
print("taksówka = taxi")
print("metro = subway")
print("prom = ferry")
print("jacht = yacht")
print("balon = hot air balloon")
print("statek kosmiczny = spaceship")
print("riksza = rickshaw")
print("gondola = gondola")
print("sterowiec = zeppelin")
print("rolki = rollerblades")
print("kajak = canoe")
print("łódź podwodna = submarine")

print(Fore.RED,"Lesson 26 - Numbers 111 - 150")

print(Fore.WHITE)

print(Fore.RED,"Lesson 27 - Past Simple")

print(Fore.WHITE)

print(Fore.RED,"Lesson 28 - Personality_ Treats")

print(Fore.WHITE)

print(Fore.RED,"Lesson 29 - Present perfect")

print(Fore.WHITE)

print(Fore.RED,"Lesson 30 - Numbers 151 - 190")

print(Fore.WHITE)

print(Fore.RED,"Lesson 31 - Countries")

print(Fore.WHITE)

print(Fore.RED,"Lesson 32 - Ordering")

print(Fore.WHITE)

print(Fore.RED,"Lesson 33 - Shops in town")

print(Fore.WHITE)

print(Fore.RED,"Lesson 34 - Numbers 191 - 230")

print(Fore.WHITE)

print(Fore.RED,"Lesson 35 - Thing in the street")

print(Fore.WHITE)

print(Fore.RED,"Lesson 36 - Instruments")
print(Fore.WHITE)






