import keyboard

import colorama
from colorama import Fore, init
init()
print(Fore.RED,"1'den 10' a Sayılar")
print(Fore.WHITE,"jeden =?, dva =?, tri =?, styri =?, pat =?, sest =?, sedem =?, osem =?, devat =?, desat =?")
print("")
print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")

mesaj = "Karşılık gelen rakamları giriniz:"

print("Devam etmek için enter'a basınız.")
keyboard.wait("enter")

jeden = input(mesaj)
dva   = input(mesaj)
tri   = input(mesaj)
styri = input(mesaj)
pat   = input(mesaj)
sest  = input(mesaj)
sedem = input(mesaj)
osem  = input(mesaj)
devat = input(mesaj)
desat = input(mesaj)

print("Devam etmek için spacebar'a basınız.")
keyboard.wait("space")
print("")

print("jeden = 1, dva = 2, tri = 3, styri = 4, pat = 5, sest = 6, sedem = 7, osem = 8, devat = 9, desat = 10")

sayi1 = int(input("Birinci sayiyi giriniz: "))
sayi2 = int(input("İkinci sayiyi giriniz: "))
sayi3 = int(input("Ucuncu sayiyi giriniz: "))
sayi4 = int(input("Dorduncu sayiyi giriniz: "))

toplam = sayi1 + sayi2 + sayi3 + sayi4

print(toplam)

print(Fore.RED, "Lesson 2 - Greeting")
print("")
print(Fore.WHITE,"Ahoj = Hello")
print("Ako sa mate = How are you?")
print("Rad vas spoznavam = Nice to meet you")
print("Uvidime sa zajtra = See you tomorrow")
print("Dobre rano = Good morning")
print("Dobre den = Good afternoon")
print("Dobry vecer = Good evening")
print("Dobru noc = Good night")
print("Ako sa volate ? = What is your name ?")
print("Moje meno je ____ = My name is ___")
print("kde byvas ? = Where do you live?")
print("Odkial ste ? = Where are you from?")
print("Rad vas opat'vidim = Nice to see you")
print("Pekny den = Have a nice day")
print("Uvidime sa neskor = See you later")
print("Dovidenia = Goodbye")
print("Prosim = Please")
print("Dakujem = Thank you")

print(Fore.RED, "Lesson_3 = Regular Verbs,")

print(Fore.WHITE,"Regular verbs are divided into 3 categories")

print(Fore.BLUE, "1. -AŤ/AŤ sa Verbs")

print(Fore.WHITE, "pýtať = to ask")
print("hrať = to play")
print("čítať = to read")
print("počúvať = to listen")
print("ležať = to lie down")
print("vstávať = to get up")
print("otvárať = to open")
print("zatvárať = to close")
print("zavolať	= to call")
print("hrať sa = to play (refl.)")
print("napísať = to write")
print("smiať sa = to laugh")
print("plakať = to cry")
print("kráčať =to walk")
print("počítavať = to calculate")
print("skúšať = to try")
print("napomínať = to admonish")
print("nosievať = to wear")
print("prechádzať = to walk")
print("používať = to use")
print("predpokladať = to assume")
print("vysnívať = to dream")

print(Fore.BLUE, "2. -OVAŤ Verbs")

print(Fore.WHITE, "pracovať = to work")
print("študovať = to study")
print("milovať = to love")
print("tancovať = to dance")
print("maľovať = to paint")
print("zapisovať = to note down")
print("budovať = to build")

print(Fore.BLUE, "3. -IŤ Verbs")

print(Fore.WHITE,"variť = to cook")
print("učiť = to teach")
print("kresliť = to draw")
print("pocítiť = to feel")
print("čistiť = to clean")
print("riešiť = to solve")
print("žiť = to live")
print("veriť = to believe")
print("tvrdiť = to claim")
print("vlastniť = to own")
print("hodnotiť = to evaluate")

print("Lesson 3.1 - Present Tense")           

print("I = Ja")
print("you = Ty")
print("he/she = on/ona")
print("we = my")
print("you = vy")
print("they = oni")

print("Example for robiť = to do\n, milovať = to love\n, čítať = to read\n")

print("1. Example = robiť\n, Ją robím\n, Ty robíš\n, On/Ona robí\n, My robíme\n, Vy robíte\n, Oni robia\n")

print("2. Examle = milovať\n, Ja milujem\n, Ty miluješ\n, On/ona miluje\n, My milujeme\n, Vy milujete\n, Oni milujú\n")

print("3. exapmle = čítať\n, Ja počúvam\n,	Ty počúvaš\n, On/ona počúva\n, My počúvame\n, Vy počúvate\n, Oni počúvajú\n")

print(Fore.BLUE, "Lesson 4 = Adjectives")

print(Fore.WHITE, "Šťastn = Happyý")
print("Smutný = Sad")
print("Nahnevaný = Angry")  
print("Vystrašený = Afraid") 
print("Radosť = Joy")
print("Prekvapený = Surprised")
print("Pokojný = Calm")
print("Znudený = Bored")
print("Ľahký = Easy") 
print("Ťažký = Difficult")
print("Zlý = Bad")
print("Dobrý = Good")
print("Hlučný = Noisy") 
print("Tichý = Quiet")
print("Silný = Strong")        
print("Slabý = Weak")     
print("Tvrdý = Hard")     
print("Mäkký = Soft")
print("Viac = More") 
print("Menej = Less")     
print("Čistý = Clean")
print("Špinavý = Dirty")  
print("Starý = Old")
print("Nový = New")
print("Veľký = Big")  
print("Malý = Small") 
print("Mladý = Young")     
print("Vychudnutý  = Skinny")
print("Tučný = Fat")
print("Pekný = Pretty") 
print("Škaredý = Ugly") 
print("Hrubý = Thick") 
print("Tenký = Thin")  
print("Drsný = Rough")    
print("Hladký = Smooth")

print(Fore.RED, "Lesson 5 - Days and Months")

print(Fore.BLUE,"Lesson 5.1 - Days of the week")
print("")

print(Fore.WHITE,"Los dias de la semana = The days of the week")
print("Den = day")
print("Týždeň = week")
print("Pondelok = Monday")
print("Utorak = Tuesday")
print("Streda = Wednesday")
print("Stvrtok = Thursday")
print("Piiatok = Friday")
print("Sobota = Saturday")
print("Nedela = Sunday")
print("Vikend = Weekend")     

print(Fore.BLUE,"Lesson 5.2 - Months of the year")
print("")

print(Fore.WHITE,"Mesiace Roka = The months of the year")
print("Mesiac = Months")
print("Rok = Year")
print("Januar = January")
print("Februar = February")
print("Marec = March")
print("April = April")
print("Maj = May")
print("Jun = June")
print("Jul = July")
print("August = August")
print("September = September")
print("Oktober = October")
print("November = November")
print("December = December")
print("")

print(Fore.RED,"Lesson 6 - Seasons and Weathers")
print("")

print(Fore.WHITE, "Ročné obdobia = Seasons")
print("Zima = Winter")
print("Leto = Summer")
print("Jar = Spring")
print("Jeseň = Autumn")
print("Obloha = Sky")
print("Mrak = Cloud")
print("Dúha = Rainbow")
print("Studený = Cold (weather)")
print("Horúci = Hot (weather)")
print("Je horúco = It is hot")
print("Je zima = It is cold")
print("Je slnečno = It is sunny")
print("Je oblačno = It is cloudy")
print("Je vlhko = It is humid")
print("Prší = It is raining")
print("Sneží = It is snowing")
print("Fúka = It is windy")
print("Aké je počasie? = How is the weather?")
print("Dobré počasie = Good weather")
print("Zlé počasie = Bad weather")
print("Aká je teplota? = What is the temperature?")
print("Je 24 stupňov = It is 24 degrees")

print(Fore.RED,"Lesson 7 - Colors")
print("")

print(Fore.WHITE,"Clerny = Black")
print("Mordy = Blue")
print("Hnedy = Brown")
print("Zeleny = Green")
print("Oranzovy = Orange")
print("Purpurovy = Purple")
print("Cerveny = Red")
print("Biely = White")
print("Žltý = Yellow")
print("Sedy = Gray")
print("Zlaty = Gold")
print("Strieborny = Silver")
print("Aku to ma farbu = What color is it?")
print("Farbe je  ___ = The color is ___")
print("")

print(Fore.RED,"Lesson 8 - Family and Friends")
print("")

print(Fore.BLUE,"Lesson 8.1 - Family members")
print("")

print(Fore.WHITE, "Matka = Mother")
print("Otec = Father")
print("Brat = Brother")
print("Sestra = Sister")
print("Syn = Son")
print("Dcéra = Daughter")
print("Rodičia = Parents")
print("Deti = Children")
print("Dieťa = Child")
print("Nevlastná matka = Stepmother")
print("Nevlastný otec = Stepfather")
print("Nevlastná sestra = Stepsister")
print("Nevlastný brat = Stepbrother")
print("Zať = Son-in-law")
print("Nevesta = Daughter-in-law")
print("Manželka = Wife")
print("Manžel = Husband")
print("Starí rodičia = Grandparents")
print("Starý otec = Grandfather")
print("Stará mama = Grandmother")
print("Vnuk = Grandson")
print("Vnučka = Granddaughter")
print("Vnúčatá = Grandchildren")
print("Vnúča = Grandchild")
print("Teta = Aunt")
print("Strýko = Uncle")
print("Sesternica = Cousin (female)")
print("Bratranec = Cousin (male)")
print("Synovec = Nephew")
print("Neter = Niece")
print("Svokor = Father-in-law")
print("Svokra = Mother-in-law")
print("Švagor = Brother-in-law")
print("Švagriná = Sister-in-law")
print("Príbuzný = Relative")

print(Fore.BLUE,"Lesson 8.2 - Friends")
print("")

print(Fore.WHITE, "Pani = Miss")
print("Chlapec = Boy")
print("Dievča = Girl")
print("Dieťa = Baby")
print("Žena = Woman")
print("Muž = Man")
print("Kamarát = Friend (male)")
print("Kamarátka = Friend (female)")
print("Priateľ = Boyfriend")
print("Priateľka = Girlfriend")
print("Pán = Gentleman")
print("Dáma = Lady")
print("Sused = Neighbor (male)")
print("Suseda = Neighbor (female)")

print(Fore.BLUE,"Lesson 9 - Numbers from 11 to 30")
print("")

print(Fore.WHITE, "jedenásť = 11")
print("dvanásť = 12")
print("trinásť = 13")
print("štrnásť = 14")
print("pätnásť = 15")
print("šestnásť = 16")
print("sedemnásť = 17")
print("osemnásť = 18")
print("devätnásť = 19")
print("dvadsať = 20")
print("dvadsaťjeden = 21")
print("dvadsaťdva = 22")
print("dvadsaťtri = 23")
print("dvadsaťštyri = 24")
print("dvadsaťpäť = 25")
print("dvadsaťšesť = 26")
print("dvadsaťsedem = 27")
print("dvadsaťosem = 28")
print("dvadsaťdeväť = 29")
print("tridsať = 30")

print(Fore.RED,"Lesson 10 - Prepositions and Useful words")
print("")

print(Fore.BLUE,"Lesson 10.1 - Prepositions")
print("")

print(Fore.WHITE, "Pre = For")
print("Z = From")
print("V = In")
print("Vnútri = Inside")
print("Do = Into")
print("Najbližšie = Near")
print("Z = Of")
print("Von = Out")
print("Vonku = Outside")
print("Na = To")
print("Pod = Under")
print("S = With")
print("Bez = Without")
print("Vyššie = Above")
print("Naprieč = Across")
print("Po = After")
print("Proti = Against")
print("Pozdĺž = Along")
print("Okolo = Around")
print("V/Na = At")
print("Za = Behind")
print("Nižšie = Below")
print("Vedľa = Beside")
print("Medzi = Between")
print("Podľa = By")
print("Počas = During")
print("Okrem = Except")
print("A = And")
print("Pretože = Because")
print("Ale = But")
print("Alebo = Or")
print("Všade = Everywhere")
print("Všetci = Everyone")
print("Všetko = Everything")
print("Málo = Few")
print("Niektorí = Some")
print("Veľa = Many")
      

print(Fore.BLUE,"Lesson 10.2 - Useful Words")
print("")

print(Fore.WHITE, "Otázka = Question")
print("Odpoveď = Answer")
print("Pravda = Truth")
print("Lož = Lie")
print("Nič = Nothing")
print("Niečo = Something")
print("Rovnaký = Same")
print("Odlišný = Different")
print("Ťahať = Pull")
print("Tlačiť = Push")
print("Dlhý = Long")
print("Krátky = Short")
print("Studený = Cold")
print("Horúci = Hot")
print("Svetlý = Light")
print("Tmavý = Dark")
print("Mokrý = Wet")
print("Suchý = Dry")
print("Prázdny = Empty")
print("Plný = Full")
print("Ako? = How?")
print("Čo? = What?")
print("Kedy? = When?")
print("Kde? = Where?")
print("Ktorý? = Which?")
print("Kto? = Who?")
print("Prečo? = Why?")
print("Ako dlho? = How long?")
print("Koľko? = How much?")