import keyboard

import colorama
from colorama import Fore

#Lesson_1 - "Numbers"

#print(Fore.RED,"Numbers from 1 to 10")
#print(Fore.WHITE,"uno =?, dos =?, tres =?, cuatro =?, cinco =?, seis =?, siete =?, ocho =?, nueve =?, diez =?")
#print("")

#mesaj = "uno: "
#uno    = input(mesaj)
#mesaj = "dos: "
#dos    = input(mesaj)
#mesaj = "tres: "
#tres   = input(mesaj)
#mesaj = "cuatro: "
#cuatro = input(mesaj)
#mesaj = "cinco: "
#cinco  = input(mesaj)
#mesaj = "seis: "
#seis   = input(mesaj)
#mesaj = "siete: "
#siete  = input(mesaj)
##mesaj = "ocho: "
#ocho   = input(mesaj)
#mesaj = "nueve: "
#nueve  = input(mesaj)
#mesaj = "diez: "
#diez   = input(mesaj)

#print("Devam etmek için spacebar'a basınız.")
#keyboard.wait("space")

#print(f"\nGirilen Değerler: \nuno = {uno}, dos = {dos}, tres = {tres}, cuatro = {cuatro}, cinco = {cinco}, seis = {seis}, siete = {siete}, ocho = {ocho}, nueve = {nueve}, diez = {diez}")

#print("\nCevap Anahtarı:\n")
#print("uno = 1\n, dos = 2\n, tres = 3\n, cuatro = 4\n, cinco = 5\n, seis = 6\n, siete = 7\n, ocho = 8\n, nueve = 9\n, diez = 10\n")
#print("İşlemler")

#sayi1 = int(input("Birinci sayiyi giriniz: "))
#sayi2 = int(input("İkinci sayiyi giriniz: "))
#sayi3 = int(input("Üçüncü Sayiyi giriniz: "))

#toplam = sayi1 + sayi2 + sayi3
#carpma = sayi1 * sayi2 * sayi3
#cikarma = sayi1 - sayi2 - sayi3
#bolme = sayi1 / sayi2
#islem = (sayi1 * sayi2 ) - sayi2 * sayi3 / sayi1
#print(toplam) 
#print(carpma) 
#print(cikarma) 
#print(bolme) 
#print(islem)

print(Fore.RED, "Lesson 2 - Greeting")
print("")
print(Fore.WHITE,"Hola = Hello")
print("Como Estas = How are you?")
print("Mucho gusto = Nice to meet you")
print("Encantado de conocerte = Nice to meet you")
print("Hasta manana = See you tomorrow")
print("Buenos días = Good morning")
print("Buenas tardes = Good afternoon")
print("Buenas noches = Good night")
print("Cuál es su nombre ?  = What is your name ?")
print("Me llamo____ = My name is ___")
print("Dónde vives ? = Where do you live?")
print("De dónde eres ? = Where are you from?")
print("Encantado de verte = Nice to see you")
print("Que tengas un buen día = Have a nice day")
print("Hasta luego = See you later")
print("Adiós = Goodbye")
print("Por favor = Please")
print("Gracias = Thank you")

print("Devam etmek için enter' a basınız.")
keyboard.wait("enter")
  
print(Fore.RED, "Lesson_3 = Regular Verbs,")

print(Fore.WHITE,"Regular verbs are divided into 3 categories")

print(Fore.BLUE, "1. -Ar Verbs")

print(Fore.WHITE,"pasar = to pass, to spend (time), to happen\n,quedar = to stay, remain")
print("hablar = to speak")
print("llevar = to carry, bring")	
print("dejar = to leave, abandon, to let, allow")	
print("llamar = to call, to name")
print("tomar = to take, drink")
print("tratar = to treat, handle")	
print("mirar = to watch, look at")	
print("esperar = to wait for, to hope")	
print("entrar =	to enter, go in, come in")	
print("trabajar = to work")
print("terminar = to finish, end")
print("necesitar = to need, require")
print("resultar = to turn out (to be)")
print("cambiar = to change")
print("presentar = to introduce")	
print("crear = to create, to make")	
print("considerar = to consider")
print("acabar = to finish, end")
print("ganar = to win, gain, earn, get, acquire")	
print("formar = to form, shape, fashion, make")
print("aceptar = to accept, approve, to agree to")	
print("lograr = to get, obtain, to achieve, attain")		
print("preguntar = to ask, inquire")		
print("estudiar = to study")
print("ayudar = to help")
print("gustar = to please, be pleasing")		
print("escuchar = to listen, hear")
print("levantar = to raise, to lift")
print("intentar = to try, attempt")
print("usar = to use")
print("olvidar = to forget")
print("ocuoar = to occupy")
print("fijar = to fix, fasten, secure")
print("comprar = to buy, purchase")
print("evitar = to avoid, to prevent")
print("interesar = to interest, be of interest (to)")	
print("echar = to throw, cast, fling")
print("importar = to import, to be important")	
print("observar = to observe")
print("imaginar = to imagine")	
print("desarrollar = to develop, expand, to unroll, unwind, to unfold")	
print("señalar = to point out, indicate, to signal")
print("preparar = to prepare, get (something) ready")
print("faltar = to lack, be lacking, be missing")
print("acompañar = to accompany")
print("desear = to desire, want, wish")	
print("enseñar = to teach, instruct, train, educate")
print("representar = to represent")
print("mandar = to order (give an order), to send")	
print("asegurar = to assure, secure, insure")
print("matar = to kill, slaughter")
print("guardar = to guard, protect, to keep")	
print("iniciar = to initiate, begin, start")
print("bajar = to lower, go down, descend, download")	
print("notar = to note, notice, observe")
print("cortar = to cut")
print("aprovechar = to take advantage of")	
print("apoyar = to support, hold up, to back")	
print("aumentar = to increase, add to, rise")
print("abandonar = to abandon, leave behind, desert, to quit, give up")	
print("quitar = to remove, take away")
print("conservar = to preserve, conserve, to keep, retain")
print("funcionar = to function, to run")
print("anunciar = to announce")
print("comentar = to comment on")	
print("participar = to participate, to share in, to inform")	
print("escapar = to escape")
print("tirar = to throw, to shoot, to throw away, to pull")	
print("contestar = to answer")
print("preocupar = to worry")
print("prestar = to lend")
print("pesar = to weigh, to weigh down")	
print("viajar = to travel, journey")
print("Devam etmek için enter' a basınız.")
print(Fore.RED, "2. -Er Verbs")
print("")
print(Fore.WHITE,"deber = to owe, must, should, ought to")
print("comprender = to understand, comprehend")
print("correr = to run")
print("comer = to eat")
print("suceder = to happen, to succeed, follow")	
print("aprender = to learn")
print("responder = to respond, answer, reply to")
print("vender = to sell")
print("meter = to put (in), place, insert")	
print("pretender = to attempt")
print("corresponder = to correspond with")
print("depender = to depend")

print("Devam etmek için enter' a basınız.")
keyboard.wait("enter")

print(Fore.RED, "3. -Ir Verbs")
print(Fore.WHITE,"vivir = to live")
print("existir = to exist")	
print("ocurrir = to occur, happen")	
print("recibir = to receive, to welcome, greet")	
print("permitir = to permit, allow")
print("partir = to divide, to leave")
print("cumplir = to fulfil, carry out")	
print("decidir = to decide, settle, resolve")
print("subir = to go up, rise, move up, climb, raise up")
print("sufrir = to suffer, to undergo, experience")
print("compartir = to share, to divide (up)")
print("consistir = to consist")
print("insistir = to insist")
print("")

print(Fore.RED,"Lesson 3.1 - Present Tense")           

print(Fore.WHITE,"I = yo")
print("you = tu")
print("he/she/it = el/elle")
print("we = nosotros")
print("you = vosotros")
print("they = ellas/ellos/ustedes")

print("Example for hablar = to speak, comer = to eat and vivir = to live")

print("yo hablo - yo como - yo vivo")
print("tu hablas - tu comes vives")
print("el habla - el come - el vive ")
print("nosotros hablamos - nosotros comemos, nosotros vivimos")
print("vosotros hablais - vosotros comeis - vosotros vivis")
print("ellos halban - ellos comen - ellos viven")

print(Fore.RED,"Lesson 4 - Adjectives")
print("")

print(Fore.WHITE,"Ruidoso = Noisy")
print("Silencioso = Quiet")
print("Fuerte = Strong")
print("Débil = Weak")
print("Duro = Hard")
print("Blando = Soft")
print("Más = More")
print("Menos = Less")
print("Limpio = Clean")
print("Sucio = Dirty")
print("Viejo = Old")
print("Nuevo = New")
print("Grande = Big")
print("Pequeño = Small")
print("Joven = Young")
print("Viejo = Old")
print("Flaco = Skinny")
print("Gordo = Fat")
print("Guapo = Pretty")
print("Feo = Ugly")
print("Grueso = Thick")
print("Delgado = Thin")
print("Áspero = Rough")
print("Liso = Smooth")
print("Feliz = Happy")
print("Triste = Sad")
print("Enfadado = Angry")
print("Asustado = Afraid")
print("Alegría = Joy")
print("Sorprendido = Surprised")
print("Tranquilo = Calm")
print("Aburrido = Bored")
print("Fácil = Easy")
print("Difícil = Difficult")
print("Malo = Bad")
print("Bueno = Good")
print("")

print(Fore.RED,"Lesson 5 - Days and Months")
print("")

print(Fore.BLUE,"Lesson 5.1 - Days of the week")
print("")

print(Fore.WHITE,"Los dias de la semana = The days of the week")
print("Dia = day")
print("(la) semana = week")
print("Lunes = Monday")
print("Martes = Tuesday")
print("Miercoles = Wednesday")
print("Jueves = Thursday")
print("Viernes = Friday")
print("Sabada = Saturday")
print("Domingo = Sunday")
print("(el) Fin de semana = Weekend")

print(Fore.RED,"Lesson 5.2 - Months of the year")
print("")

print(Fore.WHITE,"Los mese del ano = The months of the year")
print("(el) Mes = Months")
print("(el) Ano = Year")
print("Enero = January")
print("Febrero = February")
print("Marzo = March")
print("Abril = April")
print("Mayo = May")
print("Junio = June")
print("Julio = July")
print("Agosto = August")
print("Septiembre = September")
print("Octubre = October")
print("Noviembre = November")
print("Deciembre = December")
print("")

print(Fore.RED,"Lesson 6 - Seasons and Weathers")
print("")

print(Fore.WHITE, "Las estaciones = Seasons")
print("(el) Invierno = Winter")
print("(el) Verano = Summer")
print("(la) Primavera = Spring")  
print("(el) Otoño = Autumn")
print("(el) Cielo = Sky")
print("(la) Nube = Cloud")
print("(el) Arco iris = Rainbow")
print("Frío = Cold (weather)")
print("Cálido = Hot (weather)")
print("Hace calor = It is hot")
print("Hace frío = It is cold")
print("Hace sol = It is sunny")
print("Está nublado = It is cloudy")
print("Hay humedad = It is humid")
print("Está lloviendo = It is raining") 
print("Está nevando = It is snowing")
print("Hace viento = It is windy")
print("¿Qué tiempo hace? = How is the weather?") 
print("Buen tiempo = Good weather")
print("Mal tiempo = Bad weather")
print("¿A qué temperatura estamos? = What is the temperature?")
print("Estamos a 24 grados = It is 24 degrees")

print(Fore.RED,"Lesson 7 - Colors")
print("")

print(Fore.WHITE,"Negro = Black")
print("Azul =Blue")
print("Marrón = Brown")
print("Verde = Green")
print("Naranja = Orange")
print("Morado = Purple")
print("Rojo = Red")
print("Blanco = White")
print("Amarillo = Yellow")
print("Gris = Gray")
print("Oro = Gold")
print("Plata = Silver")
print("¿Qué color es? = What color is it?")
print("El color es el ___ = The color is ___")
print("")

print(Fore.RED,"Lesson 8 - Family and Friends")
print("")

print(Fore.BLUE,"Lesson 8.1 - Family members")
print("")

print(Fore.WHITE,"el/la = the")
print("el = masculine")
print("la = feminine")
print("(la) Madre = Mother")
print("(el) Padre = Father")
print("(el) Hermano = Brother")
print("(la) Hermana = Sister")
print("(el) Hijo = Son")
print("(la) Hija = Daughter")
print("(los) Padres = Parents")
print("(los) Niños = Children")
print("(el) Niño = Child")
print("(la) Madrastra = Stepmother")
print("(el) Padrastro = Stepfather")
print("(la) Hermanastra = Stepsister")
print("(el) Hermanastro = Stepbrother")
print("(el) Yerno = Son-in-law")
print("(la) Nuera = Daughter-in-law")
print("(la) Esposa = Wife")
print("(el) Marido = Husband")
print("(los) Abuelos = Grandparents")
print("(el) Abuelo = Grandfather")
print("(la) Abuela = Grandmother")
print("(el) Nieto = Grandson")
print("(la) Nieta = Granddaughter")
print("(los) Nietos = Grandchildren")
print("(el) Nieto = Grandchild")
print("(la) Tía = Aunt")
print("(el) Tío = Uncle")
print("(la) Prima = Cousin (female)")
print("(el) Primo= Cousin (male)")
print("(el) Sobrino = Nephew")
print("(la) Sobrina = Niece")
print("(el) Suegro = Father-in-law")
print("(la) Suegra = Mother-in-law")
print("(el) Cuñado = Brother-in-law")
print("(la) Cuñada = Sister-in-law")
print("(los) Pariente = Relative")
print("")

print(Fore.BLUE,"Lesson 8.2 - Friends")
print("")

print(Fore.WHITE,"Señorita = Miss")
print("(el) Chico = Boy")
print("(la) Chica = Girl")
print("(el) Bebé = Baby")
print("(la) Mujer = Woman")
print("(el) Hombre = Man")
print("(el) Amigo = Friend (male)")
print("(la) Amiga = Friend (female)")
print("(el) Novio = Boyfriend")
print("(la) Novia = Girlfriend")
print("(el) Caballero = Gentleman")
print("(la) Dama = Lady")
print("(el) Vecino = Neighbor (male)")
print("(la) Vecina = Neighbor (female)") 

print(Fore.BLUE,"Lesson 9 - Numbers from 11 to 30")
print("")

print(Fore.WHITE, "Once = 11")
print("Doce = 12")
print("Trece = 13")
print("Catorce = 14") 
print("Quince = 15")
print("Dieciséis = 16") 
print("Diecisiete = 17")
print("Dieciocho = 18")
print("Diecinueve = 19")
print("Veinte = 20")
print("Veintiuno = 21") 
print("Veintidós = 22")
print("Veintitrés = 23")
print("Veinticuatro = 24") 
print("Veinticinco = 25")
print("Veintiséis = 26")
print("Veintisiete = 27")
print("Veintiocho = 28")
print("Veintinueve = 29")
print("Treinta = 30")


print(Fore.RED,"Lesson 10 - Prepositions and Useful words")
print("")

print(Fore.BLUE,"Lesson 10.1 - Prepositions")
print("")

print(Fore.WHITE, "Para = For")
print("De = From")
print("En = In")
print("Dentro = Inside")
print("En = Into")
print("Cerca = Near")
print("De = Of")
print("Fuera de = Out")
print("Fuera de = Outside")
print("A = To")
print("Debajo de = Under")
print("Con = With")
print("Sin = Without")
print("Encima de = Above")
print("A través de = Across")
print("Después = After")
print("Contra = Against")
print("A lo largo de = Along")
print("Alrededor de = Around")
print("En = At")
print("Detrás = Behind")
print("Debajo = Below")
print("Al lado de = Beside")
print("Entre = Between")
print("Junto a = By")
print("Durante = During")
print("Excepto = Except")
print("Y = And")
print("Porque = Because")
print("Pero = But")
print("O = Or")
print("En todas partes = Everywhere")
print("Todos = Everyone")
print("Todo = Everything")
print("Aquí = here")
print("Pocos = Few")
print("Algunos = Some")
print("Muchos = Many")

print(Fore.BLUE,"Lesson 10.2 - Useful Words")
print("")

print(Fore.WHITE, "(la) Pregunta = Question")
print("(la) Respuesta = Answer")
print("(la) Verdad = Truth")
print("(la) Mentira = Lie")
print("Nada = Nothing")
print("Algo = Something")
print("Igual = Same")
print("Diferente = Different")
print("Tirar = Pull")
print("Empujar = Push")
print("Largo = Long")
print("Corto = Short")
print("Frío = Cold")
print("Caliente = Hot")
print("Luz = Light")
print("Oscuridad = Dark")
print("Mojado = Wet")
print("Seco = Dry")
print("Vacío = Empty")
print("Lleno = Full")
print("¿Cómo? = How?")
print("¿Qué? = What?")
print("¿Cuándo? = When?")
print("¿Dónde? = Where?")
print("¿Cuál? = Which?")
print("¿Quién? = Who?")
print("¿Por qué? = Why?")
print("¿Cuánto tiempo? = How long?")
print("¿Cuánto? = How much?")


